MindWorld: LowDev_LFEntity Class Reference
LowDev_LFEntity Class Reference
Member of pattern Adapter as Adapter and Target. Member of pattern Adapter as Adaptee. Member of pattern Command as Client and Receiver. Redefines and adds to the interface functionality inherited from the classes LifeFormEntity and LowDev_LF.
#include <lowDevLFEntity.h>
Public Member Functions
LowDev_LFEntity (QObject *parent, const char *name, const char *god, LifeFormEntity *father=nullptr, LifeFormEntity *mother=nullptr)
Constructor of class LowDev_LFEntity.
LowDev_LFEntity (LifeFormEntity &copy)
Copy constructor of class LowDev_LFEntity.
LowDev_LFEntity (LowDev_LFEntity &copy)
Copy constructor of class LowDev_LFEntity.
~LowDev_LFEntity ()
Deconstructor of class HighDev_LFEntity.
LowDev_LFEntity & operator= (LowDev_LFEntity &copy)
Overload of the operator =.
virtual void setVisibility (bool v)
Sets the visibility for the life form.
virtual bool isVisible ()
Returns the visibility of the life form.
virtual void init (QOpenGLShaderProgram *p)
Initialises the life form (method runs in current OpenGL context)
virtual void draw ()
Draw life form (method runs in current OpenGL context)
virtual bool solveProblem (LifeFormEntity *lfThatReceives=nullptr)
Randomly chooses how to solve the problem and adds an associated job to the job queue.
virtual int getDevLvl ()
Returns development level of the life form.
void knowSolution ()
Returns solution to a given problem by knowing the solution.
void ignoreProblem ()
Ignores the problem, just a message.
bool guessSolution ()
Returns solution to a given problem by guessing.
void calcNextStep () final
virtual bool solveProblem ()
Solves a given problem..
void addKnownLFE (LifeFormEntity *lf)
Adds lf to the list of known life forms.
void forgetAboutLFE (LifeFormEntity *lf)
Removes lf from the list of known life forms.
void askKnownLFE (LifeFormEntity *lfThatReceives=nullptr)
Adds AskJob to the job queue of the life form if a more developed life form is known.
void meetWith (LifeFormEntity *lf)
Adds MeetJob to the job queue of the life form.
void mateWith (LifeFormEntity *lf)
Adds MateJob to the job queue of the life form.
void receiveAnswer (LifeFormEntity *lf, bool answer)
Outputs console message if the life form receives an answer from lf.
bool moveTowardsDest (CartesianCoordAdapter dest)
bool isOnSamePlanetAs (LifeFormEntity *lf)
Checks if lf is on the same planet as this.
bool isParentOf (LifeFormEntity *lf)
Checks if lf is parent of this.
bool knows (LifeFormEntity *lf)
Checks if lf is known by this.
QString getName ()
Returns name of life form.
QString getGodName ()
Returns name of god that the life form believies in.
unsigned long long getLifetimeInTicks ()
Returns lifetime in ticks of life form.
QVector3D getAbsolutPosition ()
Returns absolute position of the life form.
CartesianCoordAdapter getRelativePos ()
Returns position relative to the planet the life form lives on.
QVector3D getHomePlanetPos ()
Returns absolut position of the planet the life form lives on.
PlanetEntity * getHomePlanetEntity ()
Returns address of the life forms home planet.
LifeFormEntity * getFather ()
Returns adress of the life forms father.
LifeFormEntity * getMother ()
Returns address of the life forms mother.
QVector< LifeFormEntity * > getKnownLFEntities ()
Returns vector of all known life forms.
unsigned long long getGeneration ()
Returns generation of the life form.
QVector3D getLFEColor ()
Returns color of the life form.
void setLFEColor (QVector3D c)
Sets color of the life form.
void inhabitPlanet (PlanetEntity *p, CartesianCoordAdapter *dest=nullptr)
Sets home planet and let's the life form begin it's life.
void resetPlanetRadius ()
Protected Member Functions
CartesianCoordAdapter calcRandDestination ()
Calculates random destination on the home planet.
Protected Attributes
QString lfName
QVector3D lfeColor
QVector< QVector3D > lfVert
QOpenGLVertexArrayObject lfVAO
QOpenGLBuffer lfPositionVBO
QMatrix4x4 model
PlanetEntity * homePlanetEntity
QVector< LifeFormEntity * > knownLFEntities
CartesianCoordAdapter currentRelativePos
unsigned long long lifetimeInTicks
unsigned long long gen
LifeFormEntity * lfFather
LifeFormEntity * lfMother
LFJobHandler * ourJobHandler
DestinyAdapter * ourDestinyAdapter
bool visible
QOpenGLShaderProgram * program
Private Member Functions
CartesianCoordAdapter getPos ()
void addKownLF (LifeForm *)
A life form is added to the list of friends, the calling object has.
bool askKnownLF ()
One of the ways to solve a problem. The problem is "forwarded" to a higher life form.
Planet * getHomePlanet ()
Returns the home planet of the lifeform.
void startLife (Planet *)
The life begins on a planet.
virtual bool solveProblem ()
Here it will be decided, which method to choose to solve a problem.
CartesianCoordAdapter getPos ()
void addKownLF (LifeForm *)
A life form is added to the list of friends, the calling object has.
bool askKnownLF ()
One of the ways to solve a problem. The problem is "forwarded" to a higher life form.
Planet * getHomePlanet ()
Returns the home planet of the lifeform.
void startLife (Planet *)
The life begins on a planet.
Private Attributes
vector< LifeForm * > knownLF
Planet * homePlanet
const char * believerOf
vector< LifeForm * > knownLF
Planet * homePlanet
const char * believerOf
Static Private Attributes
static int Dev_Level = 0
static int Dev_Level = 1
Detailed Description
Member of pattern Adapter as Adapter and Target. Member of pattern Adapter as Adaptee. Member of pattern Command as Client and Receiver. Redefines and adds to the interface functionality inherited from the classes LifeFormEntity and LowDev_LF.
Constructor & Destructor Documentation
LowDev_LFEntity() [1/3]
LowDev_LFEntity::LowDev_LFEntity (QObject * parent, const char * name, const char * god, LifeFormEntity * father = nullptr, LifeFormEntity * mother = nullptr)
Constructor of class LowDev_LFEntity.
Parameters
parent QT parent pointer.
name of the life form.
name of the god that the life form believes in.
father of this life form.
mother of this life form.
Returns
none.
References LifeFormEntity::lfeColor.
LowDev_LFEntity() [2/3]
LowDev_LFEntity::LowDev_LFEntity (LifeFormEntity & copy)
Copy constructor of class LowDev_LFEntity.
Parameters
life form to copy from.
Returns
none.
LowDev_LFEntity() [3/3]
LowDev_LFEntity::LowDev_LFEntity (LowDev_LFEntity & copy)
Copy constructor of class LowDev_LFEntity.
Parameters
life form to copy from.
Returns
none.
~LowDev_LFEntity()
LowDev_LFEntity::~LowDev_LFEntity ()
Deconstructor of class HighDev_LFEntity.
Member Function Documentation
addKnownLFE()
void LifeFormEntity::addKnownLFE (LifeFormEntity * lf) inherited
Adds lf to the list of known life forms.
Parameters
lf to be known.
Returns
none.
References LifeForm::addKownLF(), LifeFormEntity::getName(), LifeFormEntity::isOnSamePlanetAs(), LifeFormEntity::knownLFEntities, LifeFormEntity::knows(), and LifeFormEntity::lfName.
Referenced by LFMeetJob::workOnJob(), and LFMateJob::workOnJob().
addKownLF() [1/2]
void LifeForm::addKownLF (LifeForm * LF) inherited
A life form is added to the list of friends, the calling object has.
\param LF life form to add to the friend list.
Returns
none.
References LifeForm::knownLF.
Referenced by LifeFormEntity::addKnownLFE(), LifeFormEntity::operator=(), and Destiny::rendevouzTwoLF().
addKownLF() [2/2]
void LifeForm::addKownLF (LifeForm * LF) inherited
A life form is added to the list of friends, the calling object has.
\param LF life form to add to the friend list.
Returns
none.
References LifeForm::knownLF.
Referenced by LifeFormEntity::addKnownLFE(), LifeFormEntity::operator=(), and Destiny::rendevouzTwoLF().
askKnownLF() [1/2]
bool LifeForm::askKnownLF (void) inherited
One of the ways to solve a problem. The problem is "forwarded" to a higher life form.
Parameters
none.
Returns
TRUE, if problem solved this way - else FALSE.
References LifeForm::getDevLvl(), LifeForm::knownLF, and LifeForm::solveProblem().
Referenced by HighDev_LF::solveProblem(), MidDev_LF::solveProblem(), LowDev_LF::solveProblem(), solveProblem(), HighDev_LFEntity::solveProblem(), and MidDev_LFEntity::solveProblem().
askKnownLF() [2/2]
bool LifeForm::askKnownLF (void) inherited
One of the ways to solve a problem. The problem is "forwarded" to a higher life form.
Parameters
none.
Returns
TRUE, if problem solved this way - else FALSE.
References LifeForm::getDevLvl(), LifeForm::knownLF, and LifeForm::solveProblem().
Referenced by HighDev_LF::solveProblem(), MidDev_LF::solveProblem(), LowDev_LF::solveProblem(), solveProblem(), HighDev_LFEntity::solveProblem(), and MidDev_LFEntity::solveProblem().
askKnownLFE()
void LifeFormEntity::askKnownLFE (LifeFormEntity * lfThatReceives = nullptr) inherited
Adds AskJob to the job queue of the life form if a more developed life form is known.
Parameters
life form that receives answer (Chain Of Responsibilities).
Returns
none.
References LFJobHandler::addJob(), dist(), LifeFormEntity::getDevLvl(), LifeFormEntity::getHomePlanetEntity(), LifeFormEntity::getName(), LifeFormEntity::isOnSamePlanetAs(), LifeFormEntity::knownLFEntities, LifeFormEntity::lfName, mt(), and LifeFormEntity::ourJobHandler.
Referenced by HighDev_LFEntity::solveProblem(), MidDev_LFEntity::solveProblem(), and solveProblem().
calcNextStep()
void LifeFormEntity::calcNextStep () final virtual inherited
Calculates the next step for the life form by working on the specific job queue Adds filler job if there is no job in the queue (Idle or Move)
Parameters
none.
Returns
none.
Implements Entity.
References LFJobHandler::addJob(), LifeFormEntity::calcRandDestination(), dist(), LifeFormEntity::homePlanetEntity, LifeFormEntity::lfName, LifeFormEntity::lifetimeInTicks, mt(), LifeFormEntity::ourJobHandler, and LFJobHandler::workOnTopJob().
calcRandDestination()
CartesianCoordAdapter LifeFormEntity::calcRandDestination () protected inherited
Calculates random destination on the home planet.
Parameters
none.
Returns
CartesianCoordAdapter.
References dist(), PlanetEntity::getPlanetRadius(), LifeFormEntity::homePlanetEntity, mt(), and rd.
Referenced by LifeFormEntity::calcNextStep(), and LifeFormEntity::LifeFormEntity().
draw()
void LowDev_LFEntity::draw () virtual
Draw life form (method runs in current OpenGL context)
Parameters
none.
Returns
none.
Reimplemented from LifeFormEntity.
Reimplemented in HighDev_LFEntity, and MidDev_LFEntity.
References LifeFormEntity::draw().
Referenced by MidDev_LFEntity::draw().
forgetAboutLFE()
void LifeFormEntity::forgetAboutLFE (LifeFormEntity * lf) inherited
Removes lf from the list of known life forms.
Parameters
lf to be removed.
Returns
none.
References LifeFormEntity::getName(), LifeForm::knownLF, LifeFormEntity::knownLFEntities, LifeFormEntity::knows(), LifeFormEntity::lfFather, LifeFormEntity::lfMother, and LifeFormEntity::lfName.
getAbsolutPosition()
QVector3D LifeFormEntity::getAbsolutPosition () inherited
Returns absolute position of the life form.
Parameters
none.
Returns
three dimensional vector.
References LifeFormEntity::currentRelativePos, PlanetEntity::getCurrentPosition(), PlanetEntity::getRotAngle(), CartesianCoordAdapter::getX(), CartesianCoordAdapter::getY(), CartesianCoordAdapter::getZ(), and LifeFormEntity::homePlanetEntity.
Referenced by LifeFormEntity::draw(), and LifeFormEntity::init().
getDevLvl()
int LowDev_LFEntity::getDevLvl (void) virtual
Returns development level of the life form.
Parameters
none.
Returns
development level.
Reimplemented from LowDev_LF.
Reimplemented in HighDev_LFEntity, and MidDev_LFEntity.
References LowDev_LF::Dev_Level.
getFather()
LifeFormEntity * LifeFormEntity::getFather () inherited
Returns adress of the life forms father.
Parameters
none.
Returns
father.
References LifeFormEntity::lfFather.
Referenced by LifeFormEntity::isParentOf(), and LifeFormEntity::operator=().
getGeneration()
unsigned long long LifeFormEntity::getGeneration () inherited
Returns generation of the life form.
Parameters
none.
Returns
generation.
References LifeFormEntity::gen.
Referenced by LifeFormEntity::LifeFormEntity(), LifeFormEntity::operator=(), and LFMateJob::workOnJob().
getGodName()
QString LifeFormEntity::getGodName () inherited
Returns name of god that the life form believies in.
Parameters
none.
Returns
name of god.
References LifeForm::believerOf.
Referenced by LFMateJob::createChild(), and LifeFormEntity::operator=().
getHomePlanet() [1/2]
Planet * LifeForm::getHomePlanet (void) inherited
Returns the home planet of the lifeform.
Parameters
none.
Returns
The Planet-Object (Client).
References LifeForm::homePlanet.
Referenced by Planet::addLF(), Destiny::devolveLF(), and Destiny::evolveLF().
getHomePlanet() [2/2]
Planet * LifeForm::getHomePlanet (void) inherited
Returns the home planet of the lifeform.
Parameters
none.
Returns
The Planet-Object (Client).
References LifeForm::homePlanet.
Referenced by Planet::addLF(), Destiny::devolveLF(), and Destiny::evolveLF().
getHomePlanetEntity()
PlanetEntity * LifeFormEntity::getHomePlanetEntity () inherited
Returns address of the life forms home planet.
Parameters
none.
Returns
home planet entity.
References LifeFormEntity::homePlanetEntity.
Referenced by PlanetEntity::addInhabitant(), LifeFormEntity::askKnownLFE(), DestinyAdapter::devolveLFE(), DestinyAdapter::evolveLFE(), LifeFormEntity::isOnSamePlanetAs(), and LFMateJob::workOnJob().
getHomePlanetPos()
QVector3D LifeFormEntity::getHomePlanetPos () inherited
Returns absolut position of the planet the life form lives on.
Parameters
none.
Returns
three dimensional vector.
References PlanetEntity::getCurrentPosition(), and LifeFormEntity::homePlanetEntity.
getKnownLFEntities()
QVector< LifeFormEntity * > LifeFormEntity::getKnownLFEntities () inherited
Returns vector of all known life forms.
Parameters
none.
Returns
vector of known life forms.
References LifeFormEntity::knownLFEntities.
Referenced by LifeFormEntity::operator=().
getLFEColor()
QVector3D LifeFormEntity::getLFEColor () inherited
Returns color of the life form.
Parameters
none.
Returns
rgb vector.
References LifeFormEntity::lfeColor.
Referenced by LifeFormEntity::operator=().
getLifetimeInTicks()
unsigned long long LifeFormEntity::getLifetimeInTicks () inherited
Returns lifetime in ticks of life form.
Parameters
none.
Returns
tick count.
References LifeFormEntity::lifetimeInTicks.
Referenced by LifeFormEntity::operator=().
getMother()
LifeFormEntity * LifeFormEntity::getMother () inherited
Returns address of the life forms mother.
Parameters
none.
Returns
mother.
References LifeFormEntity::lfMother.
Referenced by LifeFormEntity::isParentOf(), and LifeFormEntity::operator=().
getName()
QString LifeFormEntity::getName (void) inherited
Returns name of life form.
Parameters
none.
Returns
name.
References LifeFormEntity::lfName.
Referenced by LifeFormEntity::addKnownLFE(), LifeFormEntity::askKnownLFE(), GodAdapter::challengeLFEs(), DestinyAdapter::devolveLFE(), DestinyAdapter::evolveLFE(), LifeFormEntity::forgetAboutLFE(), LifeFormEntity::mateWith(), LifeFormEntity::meetWith(), LifeFormEntity::operator=(), LifeFormEntity::receiveAnswer(), PlanetEntity::removeInhabitant(), and LFMateJob::workOnJob().
getPos() [1/2]
CartesianCoordAdapter LifeForm::getPos () inherited
getPos() [2/2]
CartesianCoordAdapter LifeForm::getPos () inherited
getRelativePos()
CartesianCoordAdapter LifeFormEntity::getRelativePos () inherited
Returns position relative to the planet the life form lives on.
Parameters
none.
Returns
three dimensional vector.
References LifeFormEntity::currentRelativePos.
Referenced by DestinyAdapter::devolveLFE(), DestinyAdapter::evolveLFE(), LFMeetJob::LFMeetJob(), LifeFormEntity::operator=(), LFMeetJob::operator=(), LFMeetJob::workOnJob(), and LFMateJob::workOnJob().
guessSolution()
bool LowDev_LFEntity::guessSolution (void)
Returns solution to a given problem by guessing.
Parameters
none.
Returns
answer.
References LowDev_LF::guessSolution().
ignoreProblem()
void LowDev_LFEntity::ignoreProblem (void)
Ignores the problem, just a message.
Parameters
none.
Returns
none.
References LowDev_LF::ignoreProblem().
inhabitPlanet()
void LifeFormEntity::inhabitPlanet (PlanetEntity * p, CartesianCoordAdapter * dest = nullptr) inherited
Sets home planet and let's the life form begin it's life.
Parameters
planet to settle on.
destination on the planet where to start life.
Returns
none.
References PlanetEntity::addInhabitant(), DestinyAdapter::addLFE(), LifeFormEntity::currentRelativePos, Coordinates::getHorDeg(), Coordinates::getVerDeg(), LifeForm::homePlanet, LifeFormEntity::homePlanetEntity, LifeFormEntity::ourDestinyAdapter, LifeFormEntity::resetPlanetRadius(), Coordinates::setHorDeg(), and Coordinates::setVerDeg().
Referenced by DestinyAdapter::devolveLFE(), DestinyAdapter::evolveLFE(), and LFMateJob::workOnJob().
init()
void LowDev_LFEntity::init (QOpenGLShaderProgram * p) virtual
Initialises the life form (method runs in current OpenGL context)
Parameters
p shader program to be set.
Returns
none.
Reimplemented from LifeFormEntity.
Reimplemented in HighDev_LFEntity, and MidDev_LFEntity.
References LifeFormEntity::init().
Referenced by MidDev_LFEntity::init().
isOnSamePlanetAs()
bool LifeFormEntity::isOnSamePlanetAs (LifeFormEntity * lf) inherited
Checks if lf is on the same planet as this.
Parameters
life form to test for.
Returns
true if they are on the same planet.
References LifeFormEntity::getHomePlanetEntity(), and LifeFormEntity::homePlanetEntity.
Referenced by LifeFormEntity::addKnownLFE(), LifeFormEntity::askKnownLFE(), LifeFormEntity::mateWith(), and LifeFormEntity::meetWith().
isParentOf()
bool LifeFormEntity::isParentOf (LifeFormEntity * lf) inherited
Checks if lf is parent of this.
Parameters
life form to test for.
Returns
true if lf is parent of this.
References LifeFormEntity::getFather(), and LifeFormEntity::getMother().
isVisible()
bool LowDev_LFEntity::isVisible () virtual
Returns the visibility of the life form.
Parameters
none.
Returns
current visibility.
Reimplemented from LifeFormEntity.
Reimplemented in HighDev_LFEntity, and MidDev_LFEntity.
References LifeFormEntity::isVisible().
knows()
bool LifeFormEntity::knows (LifeFormEntity * lf) inherited
Checks if lf is known by this.
Parameters
lf to test for.
Returns
true if lf is known by this.
References LifeFormEntity::knownLFEntities.
Referenced by LifeFormEntity::addKnownLFE(), and LifeFormEntity::forgetAboutLFE().
knowSolution()
void LowDev_LFEntity::knowSolution (void)
Returns solution to a given problem by knowing the solution.
Parameters
none.
Returns
answer.
References LowDev_LF::knowSolution().
mateWith()
void LifeFormEntity::mateWith (LifeFormEntity * lf) inherited
Adds MateJob to the job queue of the life form.
Parameters
life form to mate with.
Returns
none.
References LFJobHandler::addJob(), LifeFormEntity::getName(), LifeFormEntity::isOnSamePlanetAs(), LifeFormEntity::lfFather, LifeFormEntity::lfMother, LifeFormEntity::lfName, and LifeFormEntity::ourJobHandler.
Referenced by DestinyAdapter::mateTwoLFE().
meetWith()
void LifeFormEntity::meetWith (LifeFormEntity * lf) inherited
Adds MeetJob to the job queue of the life form.
Parameters
life form to meet.
Returns
none.
References LFJobHandler::addJob(), LifeFormEntity::getName(), LifeFormEntity::isOnSamePlanetAs(), LifeFormEntity::lfName, and LifeFormEntity::ourJobHandler.
Referenced by DestinyAdapter::rendevouzTwoLFEs().
moveTowardsDest()
bool LifeFormEntity::moveTowardsDest (CartesianCoordAdapter dest) inherited
Calculates the next movement step and checks if the life form has a certain distance to the destination
Parameters
destination.
Returns
true if dest is reached.
References LifeFormEntity::currentRelativePos, Coordinates::getHorDeg(), Coordinates::getVerDeg(), LifeFormEntity::lfName, Coordinates::setHorDeg(), and Coordinates::setVerDeg().
Referenced by LFMoveJob::workOnJob().
operator=()
LowDev_LFEntity & LowDev_LFEntity::operator= (LowDev_LFEntity & copy)
Overload of the operator =.
Parameters
life form to copy from.
Returns
reference of this.
receiveAnswer()
void LifeFormEntity::receiveAnswer (LifeFormEntity * lf, bool answer) inherited
Outputs console message if the life form receives an answer from lf.
Parameters
life form to receive from.
answer.
Returns
none.
References LifeFormEntity::getName(), and LifeFormEntity::lfName.
Referenced by LFAnswerJob::workOnJob().
resetPlanetRadius()
void LifeFormEntity::resetPlanetRadius () inherited
Sets the relative position radius (polar) to the radius of the currently set home planet Used if radius of the planet could have changed
Parameters
none.
Returns
none.
References LifeFormEntity::currentRelativePos, PlanetEntity::getPlanetRadius(), LifeFormEntity::homePlanetEntity, and Coordinates::setRad().
Referenced by LifeFormEntity::inhabitPlanet().
setLFEColor()
void LifeFormEntity::setLFEColor (QVector3D c) inherited
Sets color of the life form.
Parameters
rgb vector.
Returns
none.
References LifeFormEntity::lfeColor.
setVisibility()
void LowDev_LFEntity::setVisibility (bool v) virtual
Sets the visibility for the life form.
Parameters
v visibility to be set
Returns
none.
Reimplemented from LifeFormEntity.
Reimplemented in HighDev_LFEntity, and MidDev_LFEntity.
References LifeFormEntity::setVisibility().
solveProblem() [1/3]
bool LowDev_LF::solveProblem (void) virtual inherited
Here it will be decided, which method to choose to solve a problem.
Parameters
none
Returns
true, if problem solved. else, no.
Reimplemented from LifeForm.
Reimplemented in HighDev_LF, and MidDev_LF.
References LifeForm::askKnownLF(), LowDev_LF::guessSolution(), LowDev_LF::ignoreProblem(), and LowDev_LF::knowSolution().
solveProblem() [2/3]
bool LifeForm::solveProblem (void) virtual inherited
Solves a given problem..
Parameters
none.
Returns
a status.
Reimplemented in LowDev_LF, HighDev_LF, and MidDev_LF.
Referenced by LifeForm::askKnownLF(), Destiny::createProblemForLifeForm(), and LifeFormEntity::solveProblem().
solveProblem() [3/3]
bool LowDev_LFEntity::solveProblem (LifeFormEntity * lfThatReceives = nullptr) virtual
Randomly chooses how to solve the problem and adds an associated job to the job queue.
Parameters
life form that receives answer (Chain Of Responsibilities).
Returns
answer.
Reimplemented from LifeFormEntity.
Reimplemented in HighDev_LFEntity, and MidDev_LFEntity.
References LFJobHandler::addJob(), LifeForm::askKnownLF(), LifeFormEntity::askKnownLFE(), dist(), LowDev_LF::guessSolution(), LowDev_LF::ignoreProblem(), LowDev_LF::knowSolution(), LifeFormEntity::lfName, mt(), and LifeFormEntity::ourJobHandler.
startLife() [1/2]
void LifeForm::startLife (Planet * planet) inherited
The life begins on a planet.
Parameters
the planet.
Returns
none.
References LifeForm::believerOf, and LifeForm::homePlanet.
Referenced by Planet::addLF(), God::createBigBang(), Destiny::devolveLF(), and Destiny::evolveLF().
startLife() [2/2]
void LifeForm::startLife (Planet * planet) inherited
The life begins on a planet.
Parameters
the planet.
Returns
none.
References LifeForm::believerOf, and LifeForm::homePlanet.
Referenced by Planet::addLF(), God::createBigBang(), Destiny::devolveLF(), and Destiny::evolveLF().
Member Data Documentation
believerOf [1/2]
const char* LifeForm::believerOf protected inherited
Referenced by LifeFormEntity::getGodName(), HighDev_LF::HighDev_LF(), LifeFormEntity::LifeFormEntity(), LowDev_LF::LowDev_LF(), MidDev_LF::MidDev_LF(), LifeFormEntity::operator=(), and LifeForm::startLife().
believerOf [2/2]
const char* LifeForm::believerOf protected inherited
Referenced by LifeFormEntity::getGodName(), HighDev_LF::HighDev_LF(), LifeFormEntity::LifeFormEntity(), LowDev_LF::LowDev_LF(), MidDev_LF::MidDev_LF(), LifeFormEntity::operator=(), and LifeForm::startLife().
currentRelativePos
CartesianCoordAdapter LifeFormEntity::currentRelativePos protected inherited
Referenced by LifeFormEntity::getAbsolutPosition(), LifeFormEntity::getRelativePos(), LifeFormEntity::inhabitPlanet(), LifeFormEntity::LifeFormEntity(), LifeFormEntity::moveTowardsDest(), LifeFormEntity::operator=(), and LifeFormEntity::resetPlanetRadius().
Dev_Level [1/2]
int LowDev_LF::Dev_Level = 1 static protected inherited
< The level of the lifeform (LowDev).
Referenced by LowDev_LF::getDevLvl(), and getDevLvl().
Dev_Level [2/2]
int LifeForm::Dev_Level = 0 static protected inherited
< The level of the lifeform (0).
Referenced by LifeForm::getDevLvl(), and LifeFormEntity::getDevLvl().
gen
unsigned long long LifeFormEntity::gen protected inherited
Referenced by LifeFormEntity::getGeneration(), LifeFormEntity::LifeFormEntity(), and LifeFormEntity::operator=().
homePlanet [1/2]
Planet* LifeForm::homePlanet protected inherited
Referenced by LifeForm::getHomePlanet(), LifeFormEntity::inhabitPlanet(), LifeFormEntity::LifeFormEntity(), LifeFormEntity::operator=(), and LifeForm::startLife().
homePlanet [2/2]
Planet* LifeForm::homePlanet protected inherited
Referenced by LifeForm::getHomePlanet(), LifeFormEntity::inhabitPlanet(), LifeFormEntity::LifeFormEntity(), LifeFormEntity::operator=(), and LifeForm::startLife().
homePlanetEntity
PlanetEntity* LifeFormEntity::homePlanetEntity protected inherited
Referenced by LifeFormEntity::calcNextStep(), LifeFormEntity::calcRandDestination(), LifeFormEntity::draw(), LifeFormEntity::getAbsolutPosition(), LifeFormEntity::getHomePlanetEntity(), LifeFormEntity::getHomePlanetPos(), LifeFormEntity::inhabitPlanet(), LifeFormEntity::isOnSamePlanetAs(), LifeFormEntity::LifeFormEntity(), LifeFormEntity::operator=(), LifeFormEntity::resetPlanetRadius(), and LifeFormEntity::~LifeFormEntity().
knownLF [1/2]
vector<LifeForm*> LifeForm::knownLF protected inherited
Referenced by LifeForm::addKownLF(), LifeForm::askKnownLF(), and LifeFormEntity::forgetAboutLFE().
knownLF [2/2]
vector<LifeForm*> LifeForm::knownLF protected inherited
Referenced by LifeForm::addKownLF(), LifeForm::askKnownLF(), and LifeFormEntity::forgetAboutLFE().
knownLFEntities
QVector<LifeFormEntity*> LifeFormEntity::knownLFEntities protected inherited
Referenced by LifeFormEntity::addKnownLFE(), LifeFormEntity::askKnownLFE(), LifeFormEntity::forgetAboutLFE(), LifeFormEntity::getKnownLFEntities(), LifeFormEntity::knows(), and LifeFormEntity::operator=().
lfeColor
QVector3D LifeFormEntity::lfeColor protected inherited
Referenced by LifeFormEntity::draw(), LifeFormEntity::getLFEColor(), HighDev_LFEntity::HighDev_LFEntity(), LifeFormEntity::LifeFormEntity(), LowDev_LFEntity(), MidDev_LFEntity::MidDev_LFEntity(), LifeFormEntity::operator=(), and LifeFormEntity::setLFEColor().
lfFather
LifeFormEntity* LifeFormEntity::lfFather protected inherited
Referenced by LifeFormEntity::forgetAboutLFE(), LifeFormEntity::getFather(), LifeFormEntity::LifeFormEntity(), LifeFormEntity::mateWith(), and LifeFormEntity::operator=().
lfMother
LifeFormEntity* LifeFormEntity::lfMother protected inherited
Referenced by LifeFormEntity::forgetAboutLFE(), LifeFormEntity::getMother(), LifeFormEntity::LifeFormEntity(), LifeFormEntity::mateWith(), and LifeFormEntity::operator=().
lfName
QString LifeFormEntity::lfName protected inherited
Referenced by LifeFormEntity::addKnownLFE(), LifeFormEntity::askKnownLFE(), LifeFormEntity::calcNextStep(), LifeFormEntity::forgetAboutLFE(), LifeFormEntity::getName(), LifeFormEntity::LifeFormEntity(), LifeFormEntity::mateWith(), LifeFormEntity::meetWith(), LifeFormEntity::moveTowardsDest(), LifeFormEntity::operator=(), LifeFormEntity::receiveAnswer(), MidDev_LFEntity::solveProblem(), solveProblem(), HighDev_LFEntity::solveProblem(), and LifeFormEntity::~LifeFormEntity().
lfPositionVBO
QOpenGLBuffer LifeFormEntity::lfPositionVBO protected inherited
Referenced by LifeFormEntity::draw(), LifeFormEntity::init(), and LifeFormEntity::~LifeFormEntity().
lfVAO
QOpenGLVertexArrayObject LifeFormEntity::lfVAO protected inherited
Referenced by LifeFormEntity::draw(), LifeFormEntity::init(), and LifeFormEntity::~LifeFormEntity().
lfVert
QVector<QVector3D> LifeFormEntity::lfVert protected inherited
Referenced by LifeFormEntity::draw(), and LifeFormEntity::init().
lifetimeInTicks
unsigned long long LifeFormEntity::lifetimeInTicks protected inherited
Referenced by LifeFormEntity::calcNextStep(), LifeFormEntity::getLifetimeInTicks(), LifeFormEntity::LifeFormEntity(), LifeFormEntity::operator=(), and LifeFormEntity::~LifeFormEntity().
model
QMatrix4x4 LifeFormEntity::model protected inherited
Referenced by LifeFormEntity::draw(), LifeFormEntity::LifeFormEntity(), and LifeFormEntity::operator=().
ourDestinyAdapter
DestinyAdapter* LifeFormEntity::ourDestinyAdapter protected inherited
Referenced by LifeFormEntity::inhabitPlanet(), LifeFormEntity::LifeFormEntity(), and LifeFormEntity::~LifeFormEntity().
ourJobHandler
LFJobHandler* LifeFormEntity::ourJobHandler protected inherited
Referenced by LifeFormEntity::askKnownLFE(), LifeFormEntity::calcNextStep(), LifeFormEntity::LifeFormEntity(), LifeFormEntity::mateWith(), LifeFormEntity::meetWith(), LifeFormEntity::operator=(), MidDev_LFEntity::solveProblem(), solveProblem(), HighDev_LFEntity::solveProblem(), LifeFormEntity::solveProblem(), and LifeFormEntity::~LifeFormEntity().
program
QOpenGLShaderProgram* Entity::program protected inherited
Referenced by LifeFormEntity::draw(), SolarSystemEntity::draw(), ViewOfEntities::draw(), UniverseEntity::draw(), PlanetEntity::draw(), Entity::Entity(), LifeFormEntity::init(), SolarSystemEntity::init(), ViewOfEntities::init(), UniverseEntity::init(), and PlanetEntity::init().
visible
bool Entity::visible protected inherited
Referenced by ViewOfEntities::draw(), Entity::Entity(), Entity::isVisible(), and Entity::setVisibility().
The documentation for this class was generated from the following files:
lowDevLFEntity.h
lowDevLFEntity.cpp