MindWorld: CartesianCoordAdapter Class Reference
CartesianCoordAdapter Class Reference
Member of pattern Adapter as Adapter and Target. This class can return polar coordinates and cartesian coordinates. This class has all members of the superclass Coordinates and in addition to this has functions to calculate coordinates of a cartesian system.
#include <cartesianCoordAdapter.h>
Public Member Functions
CartesianCoordAdapter ()
Constructor of class CartesianCoordAdapter.
CartesianCoordAdapter (double, double, double)
Constructor of class CartesianCoordAdapter - overloaded method.
~CartesianCoordAdapter ()
Destructor of class CartesianCoordAdapter.
double getX ()
Calculates the cartesian representation of a point in a 3-dimensional system.
double getY ()
Calculates the cartesian representation of a point in a 3-dimensional system.
double getZ ()
Calculates the cartesian representation of a point in a 3-dimensional system.
bool isEqualTo (CartesianCoordAdapter *other)
double getHorDeg ()
Returns the horizontal angle.
double getVerDeg ()
Returns the vertical angle.
double getRad ()
Returns the radius.
void setHorDeg (double)
Sets the horizontal angle.
void setVerDeg (double)
Sets the vertical angle.
void setRad (double)
Sets the radius.
Protected Attributes
double horDeg
double verDeg
double rad
Detailed Description
Member of pattern Adapter as Adapter and Target. This class can return polar coordinates and cartesian coordinates. This class has all members of the superclass Coordinates and in addition to this has functions to calculate coordinates of a cartesian system.
Constructor & Destructor Documentation
CartesianCoordAdapter() [1/2]
CartesianCoordAdapter::CartesianCoordAdapter ()
Constructor of class CartesianCoordAdapter.
CartesianCoordAdapter() [2/2]
CartesianCoordAdapter::CartesianCoordAdapter (double horDegree, double verDegree, double radius)
Constructor of class CartesianCoordAdapter - overloaded method.
Parameters
horizontal angle
vertical angle
radius
References Coordinates::setHorDeg(), Coordinates::setRad(), and Coordinates::setVerDeg().
~CartesianCoordAdapter()
CartesianCoordAdapter::~CartesianCoordAdapter ()
Destructor of class CartesianCoordAdapter.
Member Function Documentation
getHorDeg()
double Coordinates::getHorDeg (void) inherited
Returns the horizontal angle.
Parameters
none.
Returns
horizontal angle.
References Coordinates::horDeg.
Referenced by getX(), getY(), LifeFormEntity::inhabitPlanet(), isEqualTo(), and LifeFormEntity::moveTowardsDest().
getRad()
double Coordinates::getRad (void) inherited
Returns the radius.
Parameters
none.
Returns
radius.
References Coordinates::rad.
Referenced by getX(), getY(), getZ(), and isEqualTo().
getVerDeg()
double Coordinates::getVerDeg (void) inherited
Returns the vertical angle.
Parameters
none.
Returns
vertical angle.
References Coordinates::verDeg.
Referenced by getX(), getY(), getZ(), LifeFormEntity::inhabitPlanet(), isEqualTo(), and LifeFormEntity::moveTowardsDest().
getX()
double CartesianCoordAdapter::getX (void)
Calculates the cartesian representation of a point in a 3-dimensional system.
Parameters
none
Returns
The first (X) coordinate of the cartesian representation.
References Coordinates::getHorDeg(), Coordinates::getRad(), and Coordinates::getVerDeg().
Referenced by PlanetEntity::calcRotAngles(), LifeFormEntity::getAbsolutPosition(), PlanetEntity::PlanetEntity(), and SolarSystemEntity::SolarSystemEntity().
getY()
double CartesianCoordAdapter::getY (void)
Calculates the cartesian representation of a point in a 3-dimensional system.
Parameters
none
Returns
The second (Y) coordinate of the cartesian representation.
References Coordinates::getHorDeg(), Coordinates::getRad(), and Coordinates::getVerDeg().
Referenced by PlanetEntity::calcRotAngles(), LifeFormEntity::getAbsolutPosition(), PlanetEntity::PlanetEntity(), and SolarSystemEntity::SolarSystemEntity().
getZ()
double CartesianCoordAdapter::getZ (void)
Calculates the cartesian representation of a point in a 3-dimensional system.
Parameters
none
Returns
The third (Z) coordinate of the cartesian representation.
References Coordinates::getRad(), and Coordinates::getVerDeg().
Referenced by PlanetEntity::calcRotAngles(), LifeFormEntity::getAbsolutPosition(), PlanetEntity::PlanetEntity(), and SolarSystemEntity::SolarSystemEntity().
isEqualTo()
bool CartesianCoordAdapter::isEqualTo (CartesianCoordAdapter * other)
References Coordinates::getHorDeg(), Coordinates::getRad(), Coordinates::getVerDeg(), Coordinates::horDeg, Coordinates::rad, and Coordinates::verDeg.
setHorDeg()
void Coordinates::setHorDeg (double _horDeg) inherited
Sets the horizontal angle.
Parameters
horizontal degree.
Returns
none.
References Coordinates::horDeg.
Referenced by CartesianCoordAdapter(), Coordinates::Coordinates(), LifeFormEntity::inhabitPlanet(), and LifeFormEntity::moveTowardsDest().
setRad()
void Coordinates::setRad (double _rad) inherited
Sets the radius.
Parameters
radius.
Returns
none.
References Coordinates::rad.
Referenced by CartesianCoordAdapter(), Coordinates::Coordinates(), and LifeFormEntity::resetPlanetRadius().
setVerDeg()
void Coordinates::setVerDeg (double _verDeg) inherited
Sets the vertical angle.
Parameters
vertical degree.
Returns
none.
References Coordinates::verDeg.
Referenced by CartesianCoordAdapter(), Coordinates::Coordinates(), LifeFormEntity::inhabitPlanet(), and LifeFormEntity::moveTowardsDest().
Member Data Documentation
horDeg
double Coordinates::horDeg protected inherited
Referenced by Coordinates::getHorDeg(), isEqualTo(), and Coordinates::setHorDeg().
rad
double Coordinates::rad protected inherited
Referenced by Coordinates::getRad(), isEqualTo(), and Coordinates::setRad().
verDeg
double Coordinates::verDeg protected inherited
Referenced by Coordinates::getVerDeg(), isEqualTo(), and Coordinates::setVerDeg().
The documentation for this class was generated from the following files:
cartesianCoordAdapter.h
cartesianCoordAdapter.cpp