MindWorld: OldestPartnerFinderStrategy Class Reference
OldestPartnerFinderStrategy Class Reference
Member of pattern Strategy as ConcreteStrategy. Used to find a Woman and a Man for a Partnership. They are searched in the HumanLifeChain and a Human will be created with them.
#include <human.h>
Public Member Functions
Human * searchPartnersAndCreateHuman ()
Detailed Description
Member of pattern Strategy as ConcreteStrategy. Used to find a Woman and a Man for a Partnership. They are searched in the HumanLifeChain and a Human will be created with them.
Member Function Documentation
searchPartnersAndCreateHuman()
Human * OldestPartnerFinderStrategy::searchPartnersAndCreateHuman (void) virtual
Searches the HumanLifeChain for the oldest Woman and Man. It finds partners with similar age. It calls createHuman() of Woman giving her the Man. That creates an Human (Woman or Man randomly). The Human is put into the HumanLifeChain and returned. If no partners are found 0 is returned..
Parameters
none.
Returns
instance of Human.
Implements PartnerFinderStrategy.
References HumanLifeChain::addNewBorn(), Woman::createHuman(), HumanLifeChain::Instance(), HumanLifeChainIterator::isDone(), and HumanLifeChainIterator::nextHuman().
The documentation for this class was generated from the following files:
human.h
human.cpp