MindWorld: Human Class Reference
Human Class Reference abstract
Member of pattern Prototype as Prototype. Subclasses can be clonable ConcretePrototypes.
Member of pattern Iterator as .
#include <human.h>
Public Member Functions
Human ()
Constructor of class Human.
~Human ()
Destructor of class Human.
virtual Human * clone ()=0
string getEyeColor ()
Returns the eye color of the human.
void setEyeColor (string str)
Sets the eye color of the human.
Private Attributes
OwnMW * mMindWorld
string mEyeColor
Static Private Attributes
static int mPossibleEyeColorsLength = 4
static string mPossibleEyeColors [] = {"green", "blue", "brown", "grey"}
Detailed Description
Member of pattern Prototype as Prototype. Subclasses can be clonable ConcretePrototypes.
Member of pattern Iterator as .
Constructor & Destructor Documentation
Human()
Human::Human ()
Constructor of class Human.
References OwnMW::get_Instance(), mEyeColor, mMindWorld, mPossibleEyeColors, mPossibleEyeColorsLength, and OwnMW::ToWrite().
~Human()
Human::~Human ()
Destructor of class Human.
Member Function Documentation
clone()
virtual Human* Human::clone () pure virtual
Implemented in Woman, and Man.
Referenced by HumanBreeder::createClone().
getEyeColor()
string Human::getEyeColor (void)
Returns the eye color of the human.
Parameters
none.
Returns
the eye color (string).
References mEyeColor.
Referenced by Man::clone(), Woman::clone(), God::createBigBang(), and HumanLifeHerold::update().
setEyeColor()
void Human::setEyeColor (string str)
Sets the eye color of the human.
Parameters
the eye color (string).
Returns
none.
References mEyeColor.
Referenced by Man::clone(), and Woman::clone().
Member Data Documentation
mEyeColor
string Human::mEyeColor private
Referenced by getEyeColor(), Human(), and setEyeColor().
mMindWorld
OwnMW* Human::mMindWorld private
Referenced by Human().
mPossibleEyeColors
string Human::mPossibleEyeColors = {"green", "blue", "brown", "grey"} static private
Referenced by Human().
mPossibleEyeColorsLength
int Human::mPossibleEyeColorsLength = 4 static private
< Number of eye colours. Array of names of eye colours.
Referenced by Human().
The documentation for this class was generated from the following files:
human.h
human.cpp