MindWorld: Destiny Class Reference
Destiny Class Reference
Member of pattern Adapter as Adaptee. Member of pattern Singleton. Member of pattern ChainOfresponsibility as Client. This class represents the Destiny in our Universe. In our concept a system has only one instance of Destiny type. It can manage two lifeforms becoming friends evolve and devolve lifeforms. It's most important function is to create problems for life forms.
#include <destiny.h>
Public Member Functions
void createProblemForLifeForm (LifeForm *)
Create a problem for life form LF.
void rendevouzTwoLF (LifeForm *, LifeForm *)
Adds life form LF2 to the list of known life forms of LF1 and the other way around..
bool evolveLF (LifeForm *)
Creates a new lifeform.
bool devolveLF (LifeForm *)
Creates a new lifeform.
Static Public Member Functions
static Destiny * getDestiny ()
Returns the unique Destiny. (Singleton)
Protected Member Functions
Destiny ()
Constructor of class Destiny.
~Destiny ()
Destructor of class Destiny.
Static Protected Attributes
static Destiny * ourDestiny = nullptr
Detailed Description
Member of pattern Adapter as Adaptee. Member of pattern Singleton. Member of pattern ChainOfresponsibility as Client. This class represents the Destiny in our Universe. In our concept a system has only one instance of Destiny type. It can manage two lifeforms becoming friends evolve and devolve lifeforms. It's most important function is to create problems for life forms.
Constructor & Destructor Documentation
Destiny()
Destiny::Destiny () protected
Constructor of class Destiny.
Referenced by getDestiny().
~Destiny()
Destiny::~Destiny () protected
Destructor of class Destiny.
Member Function Documentation
createProblemForLifeForm()
void Destiny::createProblemForLifeForm (LifeForm * LF)
Create a problem for life form LF.
Parameters
LF the life form for which problem is created.
Returns
none.
References LifeForm::solveProblem().
Referenced by God::SimulateTimeStep().
devolveLF()
bool Destiny::devolveLF (LifeForm * LF)
Creates a new lifeform.
Parameters
a pointer of a lifeform.
Returns
FALSE.
References LifeForm::getDevLvl(), LifeForm::getHomePlanet(), NUM_OF_CONCRETE_LIFEFORMS, and LifeForm::startLife().
evolveLF()
bool Destiny::evolveLF (LifeForm * LF)
Creates a new lifeform.
Parameters
a pointer of a lifeform.
Returns
FALSE.
References LifeForm::getDevLvl(), LifeForm::getHomePlanet(), NUM_OF_CONCRETE_LIFEFORMS, and LifeForm::startLife().
getDestiny()
Destiny * Destiny::getDestiny (void) static
Returns the unique Destiny. (Singleton)
Parameters
none.
Returns
The single instance of class Destiny.
References Destiny(), and ourDestiny.
Referenced by God::createBigBang().
rendevouzTwoLF()
void Destiny::rendevouzTwoLF (LifeForm * LF1, LifeForm * LF2)
Adds life form LF2 to the list of known life forms of LF1 and the other way around..
Parameters
LF1 life form that is part of the rendevouz.
LF2 life form that is part of the rendevouz.
Returns
none.
References LifeForm::addKownLF().
Referenced by God::SimulateTimeStep().
Member Data Documentation
ourDestiny
Destiny * Destiny::ourDestiny = nullptr static protected
Is set once, once getDestiny is called.(Singleton)
Referenced by getDestiny().
The documentation for this class was generated from the following files:
destiny.h
destiny.cpp