MindWorld: MindWorld Class Reference
MindWorld Class Reference
Member of pattern Composite as Composite.
Member of pattern ChainOfresponsibility as Client and as ConcreteHandler.
Member of pattern Builder as Director.
Member of pattern Decorator as ConcreteComponent. Is one MindWworld, which the OwnMW of each Human cosnists of. Is the container of Thinkable objects on every level other than first level.
#include <implementations.h>
Public Member Functions
MindWorld (MindWorldComponent *dwc, char *quality, MindWorld *mw=0)
Constructor of MindWorld.
~MindWorld ()
Destructor of MindWorld.
virtual void ToWrite ()
Shows the MindWorld object.
virtual char * get_type ()
Returns the type of the mindworld.
void change (char *text)
Changes the quality of the mindworld.
void add (MindWorldComponent *mwc)
Adds a MindWorldComponent to the MindWorld.
void write_target (std::string type, int min_count)
bool can_write (std::string type, int min_count)
like "HasHelp()" in "Design Patterns" - Chain of Responsibility
void create_thought (ThoughtBuilder *builder)
Creates a thought.
char * get_quality ()
std::vector< MindWorldComponent * > & get_mwc ()
virtual int get_change_count ()
void set_change_count (int new_count)
Private Attributes
std::vector< MindWorldComponent * > _mwc
char * _quality
MindWorld * _parent_mw
int _change_count
Detailed Description
Member of pattern Composite as Composite.
Member of pattern ChainOfresponsibility as Client and as ConcreteHandler.
Member of pattern Builder as Director.
Member of pattern Decorator as ConcreteComponent. Is one MindWworld, which the OwnMW of each Human cosnists of. Is the container of Thinkable objects on every level other than first level.
Constructor & Destructor Documentation
MindWorld()
MindWorld::MindWorld (MindWorldComponent * mwc, char * quality, MindWorld * mw = 0)
Constructor of MindWorld.
Parameters
a pointer of a MindWorldComonent object.
a string.
a pointer of a MindWorld object.
References _mwc, _parent_mw, _quality, and MindWorldComponent::set_change_count().
Referenced by OwnMW::initialize().
~MindWorld()
MindWorld::~MindWorld ()
Destructor of MindWorld.
References _mwc.
Member Function Documentation
add()
void MindWorld::add (MindWorldComponent * mwc)
Adds a MindWorldComponent to the MindWorld.
Parameters
a pointer to a MindWorldComponent object.
Returns
none.
References _mwc.
Referenced by create_thought(), and OwnMW::initialize().
can_write()
bool MindWorld::can_write (std::string type, int min_count)
like "HasHelp()" in "Design Patterns" - Chain of Responsibility
Parameters
a string.
minimum count (a integer).
Returns
true, if the write_target request can be handled from an object in this "MindWorld".
References _mwc.
Referenced by write_target().
change()
void MindWorld::change (char * text) virtual
Changes the quality of the mindworld.
Parameters
a string.
Returns
none.
Implements MindWorldComponent.
References _quality, MindWorldComponent::get_change_count(), and MindWorldComponent::set_change_count().
create_thought()
void MindWorld::create_thought (ThoughtBuilder * builder)
Creates a thought.
Parameters
a ThoughtBuilder.
Returns
none.
References add(), and ThoughtBuilder::create_thought().
Referenced by OwnMW::initialize().
get_change_count()
virtual int MindWorldComponent::get_change_count () inline virtual inherited
Implemented in Explainable.
References MindWorldComponent::_change_count.
Referenced by View::change(), Thought::change(), Feeling::change(), change(), CreatedThought::change(), Thought::ReDo(), and Thought::UnDo().
get_mwc()
std::vector<MindWorldComponent*>& MindWorld::get_mwc () inline
References _mwc.
Referenced by OwnMW::ToWrite().
get_quality()
char* MindWorld::get_quality () inline
References _quality.
get_type()
char * MindWorld::get_type (void) virtual
Returns the type of the mindworld.
Parameters
none.
Returns
a string.
Implements MindWorldComponent.
Reimplemented in OwnMW.
set_change_count()
void MindWorldComponent::set_change_count (int new_count) inline inherited
References MindWorldComponent::_change_count.
Referenced by View::change(), Thought::change(), Feeling::change(), change(), CreatedThought::change(), CreatedThought::CreatedThought(), Feeling::Feeling(), MindWorld(), Thought::ReDo(), Thought::Thought(), Thought::UnDo(), and View::View().
ToWrite()
void MindWorld::ToWrite (void) virtual
Shows the MindWorld object.
Parameters
none.
Returns
none.
Implements Thinkable.
Reimplemented in OwnMW.
References _mwc, and _quality.
write_target()
void MindWorld::write_target (std::string type, int min_count)
like "HandleHelp()" in "Design Patterns" - Chain of Responsibility searches for an "Thinkable"-Object with the same type defined in parameter "type" and with _change_count >= parameter min_count, calls write_target() of its successor, if not found
Parameters
a string.
minimum count (a integer).
Returns
none.
References _parent_mw, can_write(), and write_target().
Referenced by write_target().
Member Data Documentation
_change_count
int MindWorldComponent::_change_count private inherited
Referenced by MindWorldComponent::get_change_count(), and MindWorldComponent::set_change_count().
_mwc
std::vector<MindWorldComponent*> MindWorld::_mwc private
0..*
Referenced by add(), can_write(), get_mwc(), MindWorld(), ToWrite(), and ~MindWorld().
_parent_mw
MindWorld* MindWorld::_parent_mw private
is successor, needed for the Chain of Responsibility Pattern. 0..*
Referenced by MindWorld(), and write_target().
_quality
char* MindWorld::_quality private
Referenced by change(), get_quality(), MindWorld(), and ToWrite().
The documentation for this class was generated from the following files:
implementations.h
implementations.cpp