MindWorld: Jesus_Ex_Factory Class Reference
Jesus_Ex_Factory Class Reference
Member of pattern Factory as ConcreteCreator. This class can create an instance of class Jesus. Jesus_Ex_Factory is the factory for the concrete god Jesus. If this class creates a god, the static variable of Deus_Ex_Factory is set to the god created this way.
#include <jesusExFactory.h>
Public Member Functions
virtual God * createGod ()
Creates an instance of god Jesus, if no god B was created before. Else it returns B.
Static Public Member Functions
static bool getInstanceOfGodCreated ()
Returns the flag if a instance of class God was created.
static void setInstanceOfGodCreated ()
Sets the flag if a instance of class God was created.
static God * getInstanceOfGod ()
Returns the instance of class God.
static void setInstanceOfGod (God *)
Sets a instance of a class God.
Static Private Attributes
static bool InstanceOfGodCreatedYN = false
static God * instance = nullptr
Detailed Description
Member of pattern Factory as ConcreteCreator. This class can create an instance of class Jesus. Jesus_Ex_Factory is the factory for the concrete god Jesus. If this class creates a god, the static variable of Deus_Ex_Factory is set to the god created this way.
Member Function Documentation
createGod()
God * Jesus_Ex_Factory::createGod (void) virtual
Creates an instance of god Jesus, if no god B was created before. Else it returns B.
Parameters
none
Returns
A pointer to the god of our system.
Reimplemented from Deus_Ex_Factory.
References Deus_Ex_Factory::getInstanceOfGod(), and Deus_Ex_Factory::setInstanceOfGod().
getInstanceOfGod()
God * Deus_Ex_Factory::getInstanceOfGod (void) static inherited
Returns the instance of class God.
Parameters
none.
Returns
instance of class God.
References Deus_Ex_Factory::instance.
Referenced by Alah_Ex_Factory::createGod(), VeryHighDevLF_Ex_Factory::createGod(), createGod(), and Deus_Ex_Factory::createGod().
getInstanceOfGodCreated()
bool Deus_Ex_Factory::getInstanceOfGodCreated (void) static inherited
Returns the flag if a instance of class God was created.
Parameters
none.
Returns
True, if a instance of God was created, else False.
References Deus_Ex_Factory::InstanceOfGodCreatedYN.
Referenced by Deus_Ex_Factory::setInstanceOfGod().
setInstanceOfGod()
void Deus_Ex_Factory::setInstanceOfGod (God * _god) static inherited
Sets a instance of a class God.
Parameters
a instance of a class God.
Returns
none.
References Deus_Ex_Factory::getInstanceOfGodCreated(), Deus_Ex_Factory::instance, and Deus_Ex_Factory::setInstanceOfGodCreated().
Referenced by Alah_Ex_Factory::createGod(), VeryHighDevLF_Ex_Factory::createGod(), createGod(), and Deus_Ex_Factory::createGod().
setInstanceOfGodCreated()
void Deus_Ex_Factory::setInstanceOfGodCreated (void) static inherited
Sets the flag if a instance of class God was created.
Parameters
none.
Returns
none.
References Deus_Ex_Factory::InstanceOfGodCreatedYN.
Referenced by Deus_Ex_Factory::setInstanceOfGod().
Member Data Documentation
instance
God * Deus_Ex_Factory::instance = nullptr static private inherited
Is set once, once createGod is called. This controls the restriction to number of gods.
Referenced by Deus_Ex_Factory::getInstanceOfGod(), and Deus_Ex_Factory::setInstanceOfGod().
InstanceOfGodCreatedYN
bool Deus_Ex_Factory::InstanceOfGodCreatedYN = false static private inherited
Is set once, once createGod is called. This controls the restriction to number of gods.
Referenced by Deus_Ex_Factory::getInstanceOfGodCreated(), and Deus_Ex_Factory::setInstanceOfGodCreated().
The documentation for this class was generated from the following files:
jesusExFactory.h
jesusExFactory.cpp