MindWorld: CreatedThought Class Reference
CreatedThought Class Reference
Member of pattern Composite as Leaf.
Member of pattern Proxy as RealSubject.
Member of pattern Decorator as ConcreteComponent. Is a Thought, which is created by the Human, himself.
#include <implementations.h>
Public Member Functions
CreatedThought (char *thought)
Constructor of CreatedThought.
void ToWrite ()
Shows the CreatedThought object.
void change (char *text)
Changes the thought.
char * get_type ()
Gets the type of CreatedThought object.
virtual int get_change_count ()
void set_change_count (int new_count)
Private Attributes
char * _thought
int _change_count
Detailed Description
Member of pattern Composite as Leaf.
Member of pattern Proxy as RealSubject.
Member of pattern Decorator as ConcreteComponent. Is a Thought, which is created by the Human, himself.
Pattern
Constructor & Destructor Documentation
CreatedThought()
CreatedThought::CreatedThought (char * thought)
Constructor of CreatedThought.
Parameters
a string.
References _thought, and MindWorldComponent::set_change_count().
Member Function Documentation
change()
void CreatedThought::change (char * text) virtual
Changes the thought.
Parameters
a text.
Returns
none.
Implements MindWorldComponent.
References _thought, MindWorldComponent::get_change_count(), and MindWorldComponent::set_change_count().
Referenced by CreatedThoughtProxy::change().
get_change_count()
virtual int MindWorldComponent::get_change_count () inline virtual inherited
Implemented in Explainable.
References MindWorldComponent::_change_count.
Referenced by View::change(), Thought::change(), Feeling::change(), MindWorld::change(), change(), Thought::ReDo(), and Thought::UnDo().
get_type()
char * CreatedThought::get_type (void) virtual
Gets the type of CreatedThought object.
Parameters
none.
Returns
"CreatedThought".
Implements MindWorldComponent.
Referenced by CreatedThoughtProxy::get_type().
set_change_count()
void MindWorldComponent::set_change_count (int new_count) inline inherited
References MindWorldComponent::_change_count.
Referenced by View::change(), Thought::change(), Feeling::change(), MindWorld::change(), change(), CreatedThought(), Feeling::Feeling(), MindWorld::MindWorld(), Thought::ReDo(), Thought::Thought(), Thought::UnDo(), and View::View().
ToWrite()
void CreatedThought::ToWrite (void) virtual
Shows the CreatedThought object.
Parameters
none.
Returns
none.
Implements Thinkable.
References _thought.
Referenced by CreatedThoughtProxy::ToWrite().
Member Data Documentation
_change_count
int MindWorldComponent::_change_count private inherited
Referenced by MindWorldComponent::get_change_count(), and MindWorldComponent::set_change_count().
_thought
char* CreatedThought::_thought private
Referenced by change(), CreatedThought(), and ToWrite().
The documentation for this class was generated from the following files:
implementations.h
implementations.cpp