MindWorld: CreatedThoughtProxy Class Reference
CreatedThoughtProxy Class Reference
Member of pattern Proxy as Proxy. Is Proxy for CreatedThought objects.
Member of pattern Builder as Builder and as Product.
Member of pattern Composite as Leaf.
Member of pattern Decorator as ConcreteComponent.
#include <implementations.h>
Public Member Functions
CreatedThoughtProxy (char *thought)
Constructor of CreatedThoughtProxy.
void ToWrite ()
Shows the CreatedThought object.
void change (char *text)
Changes the thought.
char * get_type ()
Returns the type of the new thought.
virtual int get_change_count ()
void set_change_count (int new_count)
Private Attributes
char * _thought
CreatedThought * _created_thought
int _change_count
Detailed Description
Member of pattern Proxy as Proxy. Is Proxy for CreatedThought objects.
Member of pattern Builder as Builder and as Product.
Member of pattern Composite as Leaf.
Member of pattern Decorator as ConcreteComponent.
Constructor & Destructor Documentation
CreatedThoughtProxy()
CreatedThoughtProxy::CreatedThoughtProxy (char * thought)
Constructor of CreatedThoughtProxy.
Parameters
a string.
References _created_thought, and _thought.
Member Function Documentation
change()
void CreatedThoughtProxy::change (char * text) virtual
Changes the thought.
Parameters
a string.
Returns
none.
Implements MindWorldComponent.
References _created_thought, _thought, and CreatedThought::change().
get_change_count()
virtual int MindWorldComponent::get_change_count () inline virtual inherited
Implemented in Explainable.
References MindWorldComponent::_change_count.
Referenced by View::change(), Thought::change(), Feeling::change(), MindWorld::change(), CreatedThought::change(), Thought::ReDo(), and Thought::UnDo().
get_type()
char * CreatedThoughtProxy::get_type (void) virtual
Returns the type of the new thought.
Parameters
none.
Returns
a string.
Implements MindWorldComponent.
References _created_thought, _thought, and CreatedThought::get_type().
set_change_count()
void MindWorldComponent::set_change_count (int new_count) inline inherited
References MindWorldComponent::_change_count.
Referenced by View::change(), Thought::change(), Feeling::change(), MindWorld::change(), CreatedThought::change(), CreatedThought::CreatedThought(), Feeling::Feeling(), MindWorld::MindWorld(), Thought::ReDo(), Thought::Thought(), Thought::UnDo(), and View::View().
ToWrite()
void CreatedThoughtProxy::ToWrite (void) virtual
Shows the CreatedThought object.
Parameters
none.
Returns
none.
Implements Thinkable.
References _created_thought, _thought, and CreatedThought::ToWrite().
Member Data Documentation
_change_count
int MindWorldComponent::_change_count private inherited
Referenced by MindWorldComponent::get_change_count(), and MindWorldComponent::set_change_count().
_created_thought
CreatedThought* CreatedThoughtProxy::_created_thought private
Referenced by change(), CreatedThoughtProxy(), get_type(), and ToWrite().
_thought
char* CreatedThoughtProxy::_thought private
Referenced by change(), CreatedThoughtProxy(), get_type(), and ToWrite().
The documentation for this class was generated from the following files:
implementations.h
implementations.cpp