MindWorld: HighDev_LF Class Reference
HighDev_LF Class Reference
Member of pattern ChainOfresponsibility as ConcreteHandler. Member of pattern Adapter as Adaptee. An instance of this class represents a high developed life form. This kind of life form is capable of all skills of a middle developed life form. Additional to this it is able to solve problems by thinking a new meme.
#include <highDevLF.h>
Public Member Functions
HighDev_LF ()
Constructor of class HighDev_LF.
HighDev_LF (char *)
Constructor of class HighDev_LF - overloaded mathod.
~HighDev_LF ()
Destructor of class HighDev_LF.
virtual int getDevLvl ()
Get the development level of the liveform.
virtual bool solveProblem ()
Here it will be decided, which method to choose to solve a problem.
bool thinkNewMeme ()
One of the ways to solve a problem. (handle a request)
bool watchNature ()
One of the ways to solve a problem. (handle a request)
bool readBooks ()
One of the ways to solve a problem. (handle a request)
void knowSolution ()
The life form knows the solution of the problem.
void ignoreProblem ()
A problem was not solved and got igonred by the life form.
bool guessSolution ()
One of the ways to solve a problem. (handle a request)
CartesianCoordAdapter getPos ()
void addKownLF (LifeForm *)
A life form is added to the list of friends, the calling object has.
bool askKnownLF ()
One of the ways to solve a problem. The problem is "forwarded" to a higher life form.
Planet * getHomePlanet ()
Returns the home planet of the lifeform.
void startLife (Planet *)
The life begins on a planet.
Protected Attributes
vector< LifeForm * > knownLF
Planet * homePlanet
const char * believerOf
Static Protected Attributes
static int Dev_Level = MidDev_LF::Dev_Level+1
Detailed Description
Member of pattern ChainOfresponsibility as ConcreteHandler. Member of pattern Adapter as Adaptee. An instance of this class represents a high developed life form. This kind of life form is capable of all skills of a middle developed life form. Additional to this it is able to solve problems by thinking a new meme.
Constructor & Destructor Documentation
HighDev_LF() [1/2]
HighDev_LF::HighDev_LF ()
Constructor of class HighDev_LF.
HighDev_LF() [2/2]
HighDev_LF::HighDev_LF (char * godName)
Constructor of class HighDev_LF - overloaded mathod.
Parameters
a name of the god
References LifeForm::believerOf.
~HighDev_LF()
HighDev_LF::~HighDev_LF ()
Destructor of class HighDev_LF.
Member Function Documentation
addKownLF()
void LifeForm::addKownLF (LifeForm * LF) inherited
A life form is added to the list of friends, the calling object has.
\param LF life form to add to the friend list.
Returns
none.
References LifeForm::knownLF.
Referenced by LifeFormEntity::addKnownLFE(), LifeFormEntity::operator=(), and Destiny::rendevouzTwoLF().
askKnownLF()
bool LifeForm::askKnownLF (void) inherited
One of the ways to solve a problem. The problem is "forwarded" to a higher life form.
Parameters
none.
Returns
TRUE, if problem solved this way - else FALSE.
References LifeForm::getDevLvl(), LifeForm::knownLF, and LifeForm::solveProblem().
Referenced by solveProblem(), MidDev_LF::solveProblem(), LowDev_LF::solveProblem(), LowDev_LFEntity::solveProblem(), HighDev_LFEntity::solveProblem(), and MidDev_LFEntity::solveProblem().
getDevLvl()
int HighDev_LF::getDevLvl (void) virtual
Get the development level of the liveform.
Parameters
none.
Returns
The development level.
Reimplemented from MidDev_LF.
Reimplemented in HighDev_LFEntity.
References Dev_Level.
getHomePlanet()
Planet * LifeForm::getHomePlanet (void) inherited
Returns the home planet of the lifeform.
Parameters
none.
Returns
The Planet-Object (Client).
References LifeForm::homePlanet.
Referenced by Planet::addLF(), Destiny::devolveLF(), and Destiny::evolveLF().
getPos()
CartesianCoordAdapter LifeForm::getPos () inherited
guessSolution()
bool LowDev_LF::guessSolution (void) inherited
One of the ways to solve a problem. (handle a request)
Parameters
none.
Returns
true, if problem solved this way. else, no.
Referenced by LowDev_LFEntity::guessSolution(), solveProblem(), MidDev_LF::solveProblem(), LowDev_LF::solveProblem(), LowDev_LFEntity::solveProblem(), HighDev_LFEntity::solveProblem(), and MidDev_LFEntity::solveProblem().
ignoreProblem()
void LowDev_LF::ignoreProblem (void) inherited
A problem was not solved and got igonred by the life form.
Parameters
none.
Returns
none.
Referenced by LowDev_LFEntity::ignoreProblem(), solveProblem(), MidDev_LF::solveProblem(), LowDev_LF::solveProblem(), LowDev_LFEntity::solveProblem(), HighDev_LFEntity::solveProblem(), and MidDev_LFEntity::solveProblem().
knowSolution()
void LowDev_LF::knowSolution (void) inherited
The life form knows the solution of the problem.
Parameters
none.
Returns
none.
Referenced by LowDev_LFEntity::knowSolution(), solveProblem(), MidDev_LF::solveProblem(), LowDev_LF::solveProblem(), LowDev_LFEntity::solveProblem(), HighDev_LFEntity::solveProblem(), and MidDev_LFEntity::solveProblem().
readBooks()
bool MidDev_LF::readBooks (void) inherited
One of the ways to solve a problem. (handle a request)
Parameters
none.
Returns
true, if problem solved this way. else, no.
Referenced by MidDev_LFEntity::readBooks(), solveProblem(), MidDev_LF::solveProblem(), MidDev_LFEntity::solveProblem(), and HighDev_LFEntity::solveProblem().
solveProblem()
bool HighDev_LF::solveProblem (void) virtual
Here it will be decided, which method to choose to solve a problem.
Parameters
none.
Returns
true, if problem solved. else, no.
Reimplemented from MidDev_LF.
References LifeForm::askKnownLF(), LowDev_LF::guessSolution(), LowDev_LF::ignoreProblem(), LowDev_LF::knowSolution(), MidDev_LF::readBooks(), thinkNewMeme(), and MidDev_LF::watchNature().
startLife()
void LifeForm::startLife (Planet * planet) inherited
The life begins on a planet.
Parameters
the planet.
Returns
none.
References LifeForm::believerOf, and LifeForm::homePlanet.
Referenced by Planet::addLF(), God::createBigBang(), Destiny::devolveLF(), and Destiny::evolveLF().
thinkNewMeme()
bool HighDev_LF::thinkNewMeme (void)
One of the ways to solve a problem. (handle a request)
Parameters
none.
Returns
true, if problem solved this way. else, no.
Referenced by solveProblem(), HighDev_LFEntity::solveProblem(), and HighDev_LFEntity::thinkNewMeme().
watchNature()
bool MidDev_LF::watchNature (void) inherited
One of the ways to solve a problem. (handle a request)
Parameters
none.
Returns
true, if problem solved this way. else, no.
Referenced by solveProblem(), MidDev_LF::solveProblem(), MidDev_LFEntity::solveProblem(), HighDev_LFEntity::solveProblem(), and MidDev_LFEntity::watchNature().
Member Data Documentation
believerOf
const char* LifeForm::believerOf protected inherited
Referenced by LifeFormEntity::getGodName(), HighDev_LF(), LifeFormEntity::LifeFormEntity(), LowDev_LF::LowDev_LF(), MidDev_LF::MidDev_LF(), LifeFormEntity::operator=(), and LifeForm::startLife().
Dev_Level
int HighDev_LF::Dev_Level = MidDev_LF::Dev_Level+1 static protected
< The level of the lifeform (MidDev+1).
Referenced by getDevLvl(), and HighDev_LFEntity::getDevLvl().
homePlanet
Planet* LifeForm::homePlanet protected inherited
Referenced by LifeForm::getHomePlanet(), LifeFormEntity::inhabitPlanet(), LifeFormEntity::LifeFormEntity(), LifeFormEntity::operator=(), and LifeForm::startLife().
knownLF
vector<LifeForm*> LifeForm::knownLF protected inherited
Referenced by LifeForm::addKownLF(), LifeForm::askKnownLF(), and LifeFormEntity::forgetAboutLFE().
The documentation for this class was generated from the following files:
highDevLF.h
highDevLF.cpp