MindWorld: HumanBreeder Class Reference
HumanBreeder Class Reference
Member of pattern Prototype as Client. For cloning of a "Prototype" Human. The Human to clone can be set and cloned as often as desired.
#include <human.h>
Public Member Functions
HumanBreeder ()
Constructor of class HumanBreeder.
Human * createClone ()
Returns clone of the Human set by setPrototype(Human *human).Adds the cloned Human to the HumanLifeChain..
void setPrototype (Human *human)
Sets Human prototype to be cloned.
Private Attributes
Human * mPrototype
Detailed Description
Member of pattern Prototype as Client. For cloning of a "Prototype" Human. The Human to clone can be set and cloned as often as desired.
Constructor & Destructor Documentation
HumanBreeder()
HumanBreeder::HumanBreeder ()
Constructor of class HumanBreeder.
Member Function Documentation
createClone()
Human * HumanBreeder::createClone (void)
Returns clone of the Human set by setPrototype(Human *human).Adds the cloned Human to the HumanLifeChain..
Parameters
none.
Returns
the created Human.
References HumanLifeChain::addNewBorn(), Human::clone(), HumanLifeChain::Instance(), and mPrototype.
Referenced by CloneAdmin::createClone().
setPrototype()
void HumanBreeder::setPrototype (Human * human)
Sets Human prototype to be cloned.
Parameters
human prototype.
Returns
none.
References mPrototype.
Member Data Documentation
mPrototype
Human* HumanBreeder::mPrototype private
The prototype to be cloned.
Referenced by createClone(), and setPrototype().
The documentation for this class was generated from the following files:
human.h
human.cpp