MindWorld: ViewOfEntities Class Reference
ViewOfEntities Class Reference abstract
Member of pattern Composite as Composite. Defines an abstract graphical element that can contain other entities or views. It implements the basic functionality of Entity and adds additional features that affect every child it contains.
#include <viewOfEntities.h>
Public Member Functions
ViewOfEntities (QObject *parent)
Constructor of class ViewOfEntities.
virtual ~ViewOfEntities ()=0
Deconstructor of class ViewOfEntities.
virtual void setVisibility (bool v)
Sets the visibility for the view.
virtual bool isVisible ()
Returns the visibility of the view.
virtual void add (Entity *entity)
Adds entity to the list of children.
virtual void remove (Entity *entity)
Removes entity from the list of children.
virtual void clear ()
Clears the list of children.
virtual void destroy ()
Destroys all child instances currently held by the view.
virtual bool isEmpty ()
Returns true if this view has no children.
virtual bool contains (Entity *entity)
Returns true if entity is part of this view or part of any subview contained by this view.
virtual int getSize ()
Returns children list size.
virtual Entity * getChild (int i)
Returns specific child at index i.
virtual void init (QOpenGLShaderProgram *p)
Initialises all children (method runs in current OpenGL context)
virtual void draw ()
Draw the next frame for all children (method runs in current OpenGL context)
virtual void calcNextStep ()
Calculates the next step for every child.
Protected Attributes
QVector< Entity * > children
QVector< Entity * > uninitialised
bool visible
QOpenGLShaderProgram * program
Detailed Description
Member of pattern Composite as Composite. Defines an abstract graphical element that can contain other entities or views. It implements the basic functionality of Entity and adds additional features that affect every child it contains.
It gives the functionality to add to, remove from, access, clear and destroy the list of children.
Constructor & Destructor Documentation
ViewOfEntities()
ViewOfEntities::ViewOfEntities (QObject * parent) explicit
Constructor of class ViewOfEntities.
Parameters
parent QT parent pointer.
Returns
none.
~ViewOfEntities()
ViewOfEntities::~ViewOfEntities () pure virtual
Deconstructor of class ViewOfEntities.
Member Function Documentation
add()
void ViewOfEntities::add (Entity * entity) virtual
Adds entity to the list of children.
Parameters
entity that gets added.
Returns
none.
Reimplemented in UniverseEntity, PlanetEntity, and SolarSystemEntity.
References children, contains(), and uninitialised.
Referenced by SolarSystemEntity::add(), UniverseEntity::add(), PlanetEntity::addInhabitant(), and PlanetEntity::addSatellite().
calcNextStep()
void ViewOfEntities::calcNextStep () virtual
Calculates the next step for every child.
Parameters
none.
Returns
none.
Implements Entity.
Reimplemented in PlanetEntity, UniverseEntity, and SolarSystemEntity.
References Entity::calcNextStep(), children, and uninitialised.
Referenced by SolarSystemEntity::calcNextStep(), UniverseEntity::calcNextStep(), and PlanetEntity::calcNextStep().
clear()
void ViewOfEntities::clear () virtual
Clears the list of children.
Parameters
none.
Returns
none.
Reimplemented in PlanetEntity, UniverseEntity, and SolarSystemEntity.
References children, and uninitialised.
Referenced by SolarSystemEntity::clear(), UniverseEntity::clear(), and PlanetEntity::clear().
contains()
bool ViewOfEntities::contains (Entity * entity) virtual
Returns true if entity is part of this view or part of any subview contained by this view.
Parameters
entity to search for.
Returns
true if entity is contained by this.
Reimplemented in PlanetEntity, UniverseEntity, and SolarSystemEntity.
References children, and contains().
Referenced by add(), SolarSystemEntity::contains(), contains(), UniverseEntity::contains(), and PlanetEntity::contains().
destroy()
void ViewOfEntities::destroy () virtual
Destroys all child instances currently held by the view.
Parameters
none.
Returns
none.
Reimplemented in PlanetEntity, UniverseEntity, and SolarSystemEntity.
References children, and destroy().
Referenced by SolarSystemEntity::destroy(), destroy(), UniverseEntity::destroy(), and PlanetEntity::destroy().
draw()
void ViewOfEntities::draw () virtual
Draw the next frame for all children (method runs in current OpenGL context)
Parameters
none.
Returns
none.
Implements Entity.
Reimplemented in PlanetEntity, UniverseEntity, and SolarSystemEntity.
References children, Entity::program, uninitialised, and Entity::visible.
Referenced by SolarSystemEntity::draw(), UniverseEntity::draw(), and PlanetEntity::draw().
getChild()
Entity * ViewOfEntities::getChild (int i) virtual
Returns specific child at index i.
Parameters
i index.
Returns
entity with index i.
Reimplemented in PlanetEntity, UniverseEntity, and SolarSystemEntity.
References children.
getSize()
int ViewOfEntities::getSize () virtual
Returns children list size.
Parameters
none.
Returns
children list size.
Reimplemented in PlanetEntity, UniverseEntity, and SolarSystemEntity.
References children.
Referenced by PlanetEntity::getSize().
init()
void ViewOfEntities::init (QOpenGLShaderProgram * p) virtual
Initialises all children (method runs in current OpenGL context)
Parameters
p shader program to be set.
Returns
none.
Implements Entity.
Reimplemented in PlanetEntity, UniverseEntity, and SolarSystemEntity.
References children, Entity::program, and uninitialised.
Referenced by SolarSystemEntity::init(), UniverseEntity::init(), and PlanetEntity::init().
isEmpty()
bool ViewOfEntities::isEmpty () virtual
Returns true if this view has no children.
Parameters
none.
Returns
true if list of children is empty.
Reimplemented in PlanetEntity, UniverseEntity, and SolarSystemEntity.
References children.
Referenced by PlanetEntity::isEmpty().
isVisible()
bool ViewOfEntities::isVisible () virtual
Returns the visibility of the view.
Parameters
none.
Returns
current visibility.
Reimplemented from Entity.
Reimplemented in UniverseEntity, PlanetEntity, and SolarSystemEntity.
References Entity::isVisible().
Referenced by SolarSystemEntity::isVisible(), PlanetEntity::isVisible(), and UniverseEntity::isVisible().
remove()
void ViewOfEntities::remove (Entity * entity) virtual
Removes entity from the list of children.
Parameters
entity that gets removed.
Returns
none.
Reimplemented in PlanetEntity, UniverseEntity, and SolarSystemEntity.
References children, and uninitialised.
Referenced by SolarSystemEntity::remove(), UniverseEntity::remove(), PlanetEntity::removeInhabitant(), and PlanetEntity::removeSatellite().
setVisibility()
void ViewOfEntities::setVisibility (bool v) virtual
Sets the visibility for the view.
Parameters
v visibility to be set
Returns
none.
Reimplemented from Entity.
Reimplemented in UniverseEntity, PlanetEntity, and SolarSystemEntity.
References Entity::setVisibility().
Referenced by SolarSystemEntity::setVisibility(), PlanetEntity::setVisibility(), and UniverseEntity::setVisibility().
Member Data Documentation
children
QVector<Entity*> ViewOfEntities::children protected
Referenced by add(), calcNextStep(), clear(), contains(), destroy(), draw(), SolarSystemEntity::getChild(), getChild(), UniverseEntity::getChild(), PlanetEntity::getChild(), getSize(), init(), isEmpty(), and remove().
program
QOpenGLShaderProgram* Entity::program protected inherited
Referenced by LifeFormEntity::draw(), SolarSystemEntity::draw(), draw(), UniverseEntity::draw(), PlanetEntity::draw(), Entity::Entity(), SolarSystemEntity::init(), LifeFormEntity::init(), init(), UniverseEntity::init(), and PlanetEntity::init().
uninitialised
QVector<Entity*> ViewOfEntities::uninitialised protected
Referenced by add(), calcNextStep(), clear(), draw(), init(), and remove().
visible
bool Entity::visible protected inherited
Referenced by draw(), Entity::Entity(), Entity::isVisible(), and Entity::setVisibility().
The documentation for this class was generated from the following files:
viewOfEntities.h
viewOfEntities.cpp