MindWorld: ChangeCommand Class Reference
ChangeCommand Class Reference
Member of pattern Command as a ConcreteCommand. A Command to change an Thought in a Humans MindWorld. It stores the old Thought and it sets the new.
#include <implementations.h>
Public Member Functions
ChangeCommand (Thought *thought, char *old_value, char *new_value)
Constructor of ChangeCommand.
void Execute ()
Execute the command ChangeCommand.
void UnDo ()
Undos the command ChangeCommand.
void To_Write ()
Private Attributes
Thought * _thought
char * _old_value
char * _new_value
Detailed Description
Member of pattern Command as a ConcreteCommand. A Command to change an Thought in a Humans MindWorld. It stores the old Thought and it sets the new.
Constructor & Destructor Documentation
ChangeCommand()
ChangeCommand::ChangeCommand (Thought * thought, char * old_value, char * new_value)
Constructor of ChangeCommand.
Parameters
a pointer to a Thought object.
a string.
a string.
References Execute().
Member Function Documentation
Execute()
void ChangeCommand::Execute (void) virtual
Execute the command ChangeCommand.
Parameters
none.
Returns
none.
Implements Command.
References _new_value, _thought, and Thought::set_thought().
Referenced by ChangeCommand().
To_Write()
void ChangeCommand::To_Write () inline
References _new_value.
UnDo()
void ChangeCommand::UnDo (void) virtual
Undos the command ChangeCommand.
Parameters
none.
Returns
none.
Implements Command.
References _old_value, _thought, and Thought::set_thought().
Member Data Documentation
_new_value
char* ChangeCommand::_new_value private
Referenced by Execute(), and To_Write().
_old_value
char* ChangeCommand::_old_value private
Referenced by UnDo().
_thought
Thought* ChangeCommand::_thought private
Referenced by Execute(), and UnDo().
The documentation for this class was generated from the following files:
implementations.h
implementations.cpp