MindWorld: HumanDeathHerold Class Reference
HumanDeathHerold Class Reference
Member of pattern Observer as ConcreteObserver. Prints to the console that a Human died.
#include <human.h>
Public Member Functions
HumanDeathHerold ()
Constructor of class HumanDeathHerold.
void attachToSubject (HumanLifeChain *chain)
Attaches an observer to a subject.
void update ()
Protected Attributes
HumanLifeChain * mChain
The HumanLifeChain this is attached to.
Private Attributes
Human * mNextToDie
Stores the oldest Human of HumanLifeChain.
string mMessage
Stores the gender (Woman, Man) of the oldest Human to print it.
Detailed Description
Member of pattern Observer as ConcreteObserver. Prints to the console that a Human died.
Constructor & Destructor Documentation
HumanDeathHerold()
HumanDeathHerold::HumanDeathHerold ()
Constructor of class HumanDeathHerold.
References mNextToDie.
Member Function Documentation
attachToSubject()
void HumanDeathHerold::attachToSubject (HumanLifeChain * chain)
Attaches an observer to a subject.
Parameters
a an integer.
Returns
none.
References HumanHerold::attachToSubject(), HumanLifeChain::firstElement(), HumanLifeChainElement::getHuman(), and mNextToDie.
update()
void HumanDeathHerold::update (void) virtual
Should be called by the HumanLifeChain when it changes. If a Human left the HumanLifeChain since the last update() it is considered died and print to the console. Only the oldest Human can die..
Parameters
none.
Returns
none.
Implements HumanHerold.
References HumanLifeChain::firstElement(), HumanLifeChainElement::getHuman(), HumanLifeChain::Instance(), HumanHerold::mChain, mMessage, and mNextToDie.
Member Data Documentation
mChain
HumanLifeChain* HumanHerold::mChain protected inherited
The HumanLifeChain this is attached to.
Referenced by HumanHerold::attachToSubject(), HumanLifeHerold::update(), and update().
mMessage
string HumanDeathHerold::mMessage private
Stores the gender (Woman, Man) of the oldest Human to print it.
Referenced by update().
mNextToDie
Human* HumanDeathHerold::mNextToDie private
Stores the oldest Human of HumanLifeChain.
Referenced by attachToSubject(), HumanDeathHerold(), and update().
The documentation for this class was generated from the following files:
human.h
human.cpp