MindWorld: HumanLifeChainIterator Class Reference
HumanLifeChainIterator Class Reference
Member of pattern Iterator as ConcreteIterator. Iterator for HumanLifeChain.
#include <human.h>
Public Member Functions
HumanLifeChainIterator (HumanLifeChain *list)
Creates new HumanLifeChainIterator for the given HumanLifeChain. Sets current element to first element..
Human * firstHuman ()
Returns the first stored Human and sets pointer to next elemet of list.
Human * nextHuman ()
Returns stored Human of current element and sets current element to.
bool isDone ()
Indicates the end of the list.
Private Attributes
HumanLifeChain * mList
HumanLifeChainElement * mCurrentElement
The pointer to the current element.
Detailed Description
Member of pattern Iterator as ConcreteIterator. Iterator for HumanLifeChain.
Stores the List and the current element. Changing the List while using the Iterator can cause Problems. If the current element is removed from the list, you will get an error.
Constructor & Destructor Documentation
HumanLifeChainIterator()
HumanLifeChainIterator::HumanLifeChainIterator (HumanLifeChain * list)
Creates new HumanLifeChainIterator for the given HumanLifeChain. Sets current element to first element..
Parameters
a HumanLifeChain.
References HumanLifeChain::firstElement(), mCurrentElement, and mList.
Member Function Documentation
firstHuman()
Human * HumanLifeChainIterator::firstHuman (void)
Returns the first stored Human and sets pointer to next elemet of list.
Parameters
none.
Returns
oldest Human.
References HumanLifeChain::firstElement(), mCurrentElement, mList, and nextHuman().
Referenced by RandomPartnerFinderStrategy::searchPartnersAndCreateHuman().
isDone()
bool HumanLifeChainIterator::isDone (void)
Indicates the end of the list.
Parameters
none.
Returns
true if current element is in boundaries of list, false if current element points behind the end of list.
References mCurrentElement.
Referenced by God::createBigBang(), OldestPartnerFinderStrategy::searchPartnersAndCreateHuman(), and RandomPartnerFinderStrategy::searchPartnersAndCreateHuman().
nextHuman()
Human * HumanLifeChainIterator::nextHuman (void)
Returns stored Human of current element and sets current element to.
Parameters
none.
Returns
next element of the list (type Human).
References HumanLifeChainElement::getHuman(), HumanLifeChainElement::getNextElement(), and mCurrentElement.
Referenced by God::createBigBang(), firstHuman(), OldestPartnerFinderStrategy::searchPartnersAndCreateHuman(), and RandomPartnerFinderStrategy::searchPartnersAndCreateHuman().
Member Data Documentation
mCurrentElement
HumanLifeChainElement* HumanLifeChainIterator::mCurrentElement private
The pointer to the current element.
Referenced by firstHuman(), HumanLifeChainIterator(), isDone(), and nextHuman().
mList
HumanLifeChain* HumanLifeChainIterator::mList private
The list this Iterator is for. HumanLifeChain is a Singelton but the intention is clearer that way.
Referenced by firstHuman(), and HumanLifeChainIterator().
The documentation for this class was generated from the following files:
human.h
human.cpp