MindWorld: PartnerFinder Class Reference
PartnerFinder Class Reference
Member of pattern Strategy as Context. Used to find a Woman and a Man for a Partnership. Uses its PartnerFinderStrategy to find them and create a Human with them.
#include <human.h>
Public Member Functions
PartnerFinder ()
Constructor of class PartnerFinder.
Human * searchPartnersAndCreateHuman ()
void setPartnerFinderStrategy (PartnerFinderStrategy *strategy)
Sets the PartnerFinderStrategy..
Private Attributes
PartnerFinderStrategy * mStrategy
The PartnerFinderStrategy used to find a Woman and a Man.
Detailed Description
Member of pattern Strategy as Context. Used to find a Woman and a Man for a Partnership. Uses its PartnerFinderStrategy to find them and create a Human with them.
Constructor & Destructor Documentation
PartnerFinder()
PartnerFinder::PartnerFinder ()
Constructor of class PartnerFinder.
References mStrategy.
Member Function Documentation
searchPartnersAndCreateHuman()
Human * PartnerFinder::searchPartnersAndCreateHuman (void)
Calls searchPartnersAndCreateHuman() from the referenced PartnerFinderStrategy. The strategy searches the HumanLifeChain for a Woman and a Man and creates a Human with them. It will be returned. If no PartnerFinderStrategy is referenced 0 is returned..
Parameters
none.
Returns
instance of Human.
References mStrategy, and PartnerFinderStrategy::searchPartnersAndCreateHuman().
Referenced by HumanHandler::createHumanNaturally().
setPartnerFinderStrategy()
void PartnerFinder::setPartnerFinderStrategy (PartnerFinderStrategy * strategy)
Sets the PartnerFinderStrategy..
Parameters
a pointer to a PartnerFinderStrategy.
Returns
none.
References mStrategy.
Referenced by HumanHandler::createHumanNaturally().
Member Data Documentation
mStrategy
PartnerFinderStrategy* PartnerFinder::mStrategy private
The PartnerFinderStrategy used to find a Woman and a Man.
0..*
Referenced by PartnerFinder(), searchPartnersAndCreateHuman(), and setPartnerFinderStrategy().
The documentation for this class was generated from the following files:
human.h
human.cpp