MindWorld: Feeling Class Reference
Feeling Class Reference
Member of pattern Composite as Leaf. Is a feeling of an human.
Member of pattern Decorator as ConcreteComponent. The feeling can be changed thru change(char* text), and it can be written out thru ToWrite().
#include <implementations.h>
Public Member Functions
Feeling (char *feeling)
Constructor of Feeling.
void ToWrite ()
Shows the Feeling object.
void change (char *text)
Changes the feeling.
char * get_type ()
Returns the type of the feeling.
virtual int get_change_count ()
void set_change_count (int new_count)
Private Attributes
char * _feeling
int _change_count
Detailed Description
Member of pattern Composite as Leaf. Is a feeling of an human.
Member of pattern Decorator as ConcreteComponent. The feeling can be changed thru change(char* text), and it can be written out thru ToWrite().
Constructor & Destructor Documentation
Feeling()
Feeling::Feeling (char * feeling)
Constructor of Feeling.
Parameters
a string.
References _feeling, and MindWorldComponent::set_change_count().
Member Function Documentation
change()
void Feeling::change (char * text) virtual
Changes the feeling.
Parameters
a string.
Returns
none.
Implements MindWorldComponent.
References _feeling, MindWorldComponent::get_change_count(), and MindWorldComponent::set_change_count().
get_change_count()
virtual int MindWorldComponent::get_change_count () inline virtual inherited
Implemented in Explainable.
References MindWorldComponent::_change_count.
Referenced by View::change(), Thought::change(), change(), MindWorld::change(), CreatedThought::change(), Thought::ReDo(), and Thought::UnDo().
get_type()
char * Feeling::get_type (void) virtual
Returns the type of the feeling.
Parameters
none.
Returns
"leave of type Feeling".
Implements MindWorldComponent.
set_change_count()
void MindWorldComponent::set_change_count (int new_count) inline inherited
References MindWorldComponent::_change_count.
Referenced by View::change(), Thought::change(), change(), MindWorld::change(), CreatedThought::change(), CreatedThought::CreatedThought(), Feeling(), MindWorld::MindWorld(), Thought::ReDo(), Thought::Thought(), Thought::UnDo(), and View::View().
ToWrite()
void Feeling::ToWrite (void) virtual
Shows the Feeling object.
Parameters
none.
Returns
none.
Implements Thinkable.
References _feeling.
Member Data Documentation
_change_count
int MindWorldComponent::_change_count private inherited
Referenced by MindWorldComponent::get_change_count(), and MindWorldComponent::set_change_count().
_feeling
char* Feeling::_feeling private
Referenced by change(), Feeling(), and ToWrite().
The documentation for this class was generated from the following files:
implementations.h
implementations.cpp