MindWorld: SimWidgetDatamodel Class Reference
SimWidgetDatamodel Class Reference
Represents the View of the Model-View-Controller Builds the view chain and passes the OpenGL events from the view to the entities itself.
#include <simwidgetdatamodel.h>
Public Member Functions
SimWidgetDatamodel (SimulationWidget *sw, QObject *parent)
Constructor of class SimWidgetDatamodel.
~SimWidgetDatamodel ()
Deconstructor of class SimWidgetDatamodel.
void calcNextStep ()
Calculate next step for the whole universe.
void draw ()
Redraw the whole universe.
void init (QOpenGLShaderProgram *p)
Initialise the whole universe.
void challengeLifeForms ()
Calling the challenge life forms method of the current god.
Private Member Functions
void buildViewChain (QObject *parent)
Build view chain.
Private Attributes
SimulationWidget * mSimWidget
UniverseEntity * ourUniverseEntity
GodAdapter * god
Detailed Description
Represents the View of the Model-View-Controller Builds the view chain and passes the OpenGL events from the view to the entities itself.
Constructor & Destructor Documentation
SimWidgetDatamodel()
SimWidgetDatamodel::SimWidgetDatamodel (SimulationWidget * sw, QObject * parent)
Constructor of class SimWidgetDatamodel.
Parameters
SimulationWidget.
parent QT parent pointer.
Returns
none.
References buildViewChain(), and mSimWidget.
~SimWidgetDatamodel()
SimWidgetDatamodel::~SimWidgetDatamodel ()
Deconstructor of class SimWidgetDatamodel.
References god.
Member Function Documentation
buildViewChain()
void SimWidgetDatamodel::buildViewChain (QObject * parent) private
Build view chain.
Parameters
parent QT parent pointer.
Returns
none.
References GodAdapter::createBigBang(), Deus_Ex_Factory::createGod(), God::getName(), god, UniverseEntity::Instance(), and ourUniverseEntity.
Referenced by SimWidgetDatamodel().
calcNextStep()
void SimWidgetDatamodel::calcNextStep ()
Calculate next step for the whole universe.
Parameters
none.
Returns
none.
References UniverseEntity::calcNextStep(), PlanetEntity::getCurrentPosition(), GodAdapter::getPlanetToObserve(), god, mSimWidget, ourUniverseEntity, and SimulationWidget::setCameraPos().
Referenced by SimWidgetController::advanceOneStep().
challengeLifeForms()
void SimWidgetDatamodel::challengeLifeForms ()
Calling the challenge life forms method of the current god.
Parameters
none.
Returns
none.
References GodAdapter::challengeLFEs(), and god.
Referenced by SimWidgetController::onChallengeTimer().
draw()
void SimWidgetDatamodel::draw ()
Redraw the whole universe.
Parameters
none.
Returns
none.
References UniverseEntity::draw(), and ourUniverseEntity.
Referenced by SimulationWidget::paintGL().
init()
void SimWidgetDatamodel::init (QOpenGLShaderProgram * p)
Initialise the whole universe.
Parameters
none.
Returns
none.
References UniverseEntity::init(), and ourUniverseEntity.
Referenced by SimulationWidget::initializeGL().
Member Data Documentation
god
GodAdapter* SimWidgetDatamodel::god private
Referenced by buildViewChain(), calcNextStep(), challengeLifeForms(), and ~SimWidgetDatamodel().
mSimWidget
SimulationWidget* SimWidgetDatamodel::mSimWidget private
Referenced by calcNextStep(), and SimWidgetDatamodel().
ourUniverseEntity
UniverseEntity* SimWidgetDatamodel::ourUniverseEntity private
Referenced by buildViewChain(), calcNextStep(), draw(), and init().
The documentation for this class was generated from the following files:
simwidgetdatamodel.h
simwidgetdatamodel.cpp