MindWorld: SolarSystemEntity Class Reference
SolarSystemEntity Class Reference
Member of pattern Facade as Subsystem classes. Implements interface functionality from the class ViewOfEntities. This class defines a set of methods to render a solar system with a sun that emits light and add/remove planets.
#include <solarSystemEntity.h>
Public Member Functions
SolarSystemEntity (QObject *parent, CartesianCoordAdapter coord)
Constructor of class SolarSystemEntity.
~SolarSystemEntity ()
Deconstructor of class SolarSystemEntity.
void setVisibility (bool v)
Sets the visibility for the solar system.
bool isVisible ()
Returns the visibility of the solar system.
void add (Entity *entity)
Adds entity to the solar system.
void add (PlanetEntity *p)
Adds planet to the solar system.
void remove (Entity *entity)
Remove entity from the solar system.
void remove (PlanetEntity *p)
Remove planet from the solar system.
void clear ()
Remove all entities from the solarsystem.
void destroy ()
Destroy all entities held by the solarsystem.
bool isEmpty ()
Check if there are no planets in the solar system.
bool contains (Entity *entity)
Check if solar system contains specific entity.
int getSize ()
Returns number of planets in the solar system.
Entity * getChild (int i)
Returns entity with index i.
PlanetEntity * getPlanet (int i)
Returns planet with index i.
void init (QOpenGLShaderProgram *p)
Initialises the solar system (method runs in current OpenGL context)
void draw ()
Draw solar system (method runs in current OpenGL context)
void calcNextStep ()
Calculates the next step for the solar system.
void setSolarSystemCenter (QVector3D c)
Sets the center of the solar system.
void setSunTextureFileName (QString filename)
Sets texture filename for the sun of the solar system.
void setSunRadius (double r)
Sets the suns radius.
void setSunEmissiveKoeff (double kE)
Sets the suns emissive koefficient.
QVector3D getSolarSystemCenter ()
Returns current solar system center.
Protected Attributes
QVector< Entity * > children
QVector< Entity * > uninitialised
bool visible
QOpenGLShaderProgram * program
Private Attributes
PlanetEntity * sun
QVector< PlanetEntity * > planets
double emissiveKoeff
Detailed Description
Member of pattern Facade as Subsystem classes. Implements interface functionality from the class ViewOfEntities. This class defines a set of methods to render a solar system with a sun that emits light and add/remove planets.
Constructor & Destructor Documentation
SolarSystemEntity()
SolarSystemEntity::SolarSystemEntity (QObject * parent, CartesianCoordAdapter coord)
Constructor of class SolarSystemEntity.
Parameters
parent QT parent pointer.
position of the sun.
Returns
none.
References emissiveKoeff, CartesianCoordAdapter::getX(), CartesianCoordAdapter::getY(), CartesianCoordAdapter::getZ(), PlanetEntity::setOrbitCenter(), PlanetEntity::setOwnRotVelocity(), PlanetEntity::setPlanetColor(), PlanetEntity::setPlanetRadius(), PlanetEntity::setTextureFileName(), and sun.
~SolarSystemEntity()
SolarSystemEntity::~SolarSystemEntity ()
Deconstructor of class SolarSystemEntity.
References PlanetEntity::getOrbitCenter(), LightHandler::Instance(), LightHandler::removeLightAt(), and sun.
Member Function Documentation
add() [1/2]
void SolarSystemEntity::add (Entity * entity) virtual
Adds entity to the solar system.
Parameters
entity.
Returns
none.
Reimplemented from ViewOfEntities.
Referenced by GodAdapter::createBigBang().
add() [2/2]
void SolarSystemEntity::add (PlanetEntity * p)
Adds planet to the solar system.
Parameters
planet.
Returns
none.
References ViewOfEntities::add(), contains(), PlanetEntity::getOrbitCenter(), planets, PlanetEntity::setOrbitCenter(), and sun.
calcNextStep()
void SolarSystemEntity::calcNextStep () virtual
Calculates the next step for the solar system.
Parameters
none.
Returns
none.
Reimplemented from ViewOfEntities.
References ViewOfEntities::calcNextStep().
clear()
void SolarSystemEntity::clear () virtual
Remove all entities from the solarsystem.
Parameters
none.
Returns
none.
Reimplemented from ViewOfEntities.
References ViewOfEntities::clear(), and planets.
contains()
bool SolarSystemEntity::contains (Entity * entity) virtual
Check if solar system contains specific entity.
Parameters
entity.
Returns
true if the solar system contains the entity.
Reimplemented from ViewOfEntities.
References ViewOfEntities::contains().
Referenced by add().
destroy()
void SolarSystemEntity::destroy () virtual
Destroy all entities held by the solarsystem.
Parameters
none.
Returns
none.
Reimplemented from ViewOfEntities.
References ViewOfEntities::destroy().
draw()
void SolarSystemEntity::draw () virtual
Draw solar system (method runs in current OpenGL context)
Parameters
none.
Returns
none.
Reimplemented from ViewOfEntities.
References ViewOfEntities::draw(), PlanetEntity::draw(), emissiveKoeff, LightHandler::getLightKoeffs(), LightHandler::Instance(), Entity::program, LightHandler::setLightKoeffs(), and sun.
getChild()
Entity * SolarSystemEntity::getChild (int i) virtual
Returns entity with index i.
Parameters
index i.
Returns
entity with index i.
Reimplemented from ViewOfEntities.
References ViewOfEntities::children.
getPlanet()
PlanetEntity * SolarSystemEntity::getPlanet (int i)
Returns planet with index i.
Parameters
index i.
Returns
planet with index i.
References planets.
getSize()
int SolarSystemEntity::getSize () virtual
Returns number of planets in the solar system.
Parameters
none.
Returns
number of planets.
Reimplemented from ViewOfEntities.
References planets.
getSolarSystemCenter()
QVector3D SolarSystemEntity::getSolarSystemCenter ()
Returns current solar system center.
Parameters
none.
Returns
three dimensional vector.
References PlanetEntity::getOrbitCenter(), and sun.
init()
void SolarSystemEntity::init (QOpenGLShaderProgram * p) virtual
Initialises the solar system (method runs in current OpenGL context)
Parameters
p shader program to be set.
Returns
none.
Reimplemented from ViewOfEntities.
References LightHandler::addLightAt(), PlanetEntity::getOrbitCenter(), ViewOfEntities::init(), PlanetEntity::init(), LightHandler::initLightHandler(), LightHandler::Instance(), Entity::program, and sun.
isEmpty()
bool SolarSystemEntity::isEmpty () virtual
Check if there are no planets in the solar system.
Parameters
none.
Returns
true if there are no planets in the solar system.
Reimplemented from ViewOfEntities.
References planets.
isVisible()
bool SolarSystemEntity::isVisible () virtual
Returns the visibility of the solar system.
Parameters
none.
Returns
current visibility.
Reimplemented from ViewOfEntities.
References ViewOfEntities::isVisible().
remove() [1/2]
void SolarSystemEntity::remove (Entity * entity) virtual
Remove entity from the solar system.
Parameters
entity.
Returns
none.
Reimplemented from ViewOfEntities.
remove() [2/2]
void SolarSystemEntity::remove (PlanetEntity * p)
Remove planet from the solar system.
Parameters
planet.
Returns
none.
References planets, and ViewOfEntities::remove().
setSolarSystemCenter()
void SolarSystemEntity::setSolarSystemCenter (QVector3D c)
Sets the center of the solar system.
Parameters
center.
Returns
none.
References LightHandler::addLightAt(), PlanetEntity::getOrbitCenter(), LightHandler::Instance(), planets, LightHandler::removeLightAt(), PlanetEntity::setOrbitCenter(), and sun.
setSunEmissiveKoeff()
void SolarSystemEntity::setSunEmissiveKoeff (double kE)
Sets the suns emissive koefficient.
Parameters
emissive koefficient.
Returns
none.
References emissiveKoeff.
setSunRadius()
void SolarSystemEntity::setSunRadius (double r)
Sets the suns radius.
Parameters
radius.
Returns
none.
References PlanetEntity::setPlanetRadius(), and sun.
setSunTextureFileName()
void SolarSystemEntity::setSunTextureFileName (QString filename)
Sets texture filename for the sun of the solar system.
Parameters
filename.
Returns
none.
References PlanetEntity::setTextureFileName(), and sun.
setVisibility()
void SolarSystemEntity::setVisibility (bool v) virtual
Sets the visibility for the solar system.
Parameters
v visibility to be set
Returns
none.
Reimplemented from ViewOfEntities.
References ViewOfEntities::setVisibility().
Member Data Documentation
children
QVector<Entity*> ViewOfEntities::children protected inherited
Referenced by ViewOfEntities::add(), ViewOfEntities::calcNextStep(), ViewOfEntities::clear(), ViewOfEntities::contains(), ViewOfEntities::destroy(), ViewOfEntities::draw(), getChild(), ViewOfEntities::getChild(), UniverseEntity::getChild(), PlanetEntity::getChild(), ViewOfEntities::getSize(), ViewOfEntities::init(), ViewOfEntities::isEmpty(), and ViewOfEntities::remove().
emissiveKoeff
double SolarSystemEntity::emissiveKoeff private
Referenced by draw(), setSunEmissiveKoeff(), and SolarSystemEntity().
planets
QVector<PlanetEntity*> SolarSystemEntity::planets private
Referenced by add(), clear(), getPlanet(), getSize(), isEmpty(), remove(), and setSolarSystemCenter().
program
QOpenGLShaderProgram* Entity::program protected inherited
Referenced by LifeFormEntity::draw(), draw(), ViewOfEntities::draw(), UniverseEntity::draw(), PlanetEntity::draw(), Entity::Entity(), init(), LifeFormEntity::init(), ViewOfEntities::init(), UniverseEntity::init(), and PlanetEntity::init().
sun
PlanetEntity* SolarSystemEntity::sun private
Referenced by add(), draw(), getSolarSystemCenter(), init(), setSolarSystemCenter(), setSunRadius(), setSunTextureFileName(), SolarSystemEntity(), and ~SolarSystemEntity().
uninitialised
QVector<Entity*> ViewOfEntities::uninitialised protected inherited
Referenced by ViewOfEntities::add(), ViewOfEntities::calcNextStep(), ViewOfEntities::clear(), ViewOfEntities::draw(), ViewOfEntities::init(), and ViewOfEntities::remove().
visible
bool Entity::visible protected inherited
Referenced by ViewOfEntities::draw(), Entity::Entity(), Entity::isVisible(), and Entity::setVisibility().
The documentation for this class was generated from the following files:
solarSystemEntity.h
solarSystemEntity.cpp