MindWorld: Subject Class Reference
Subject Class Reference
Member of pattern Observer as Subject. Can be observed. Observers can be attached and detached. When the Subject changes notifyObservers() should be called.
#include <human.h>
Public Member Functions
virtual void attachObserver (Observer *obs)
Attaches an Observer.
virtual void detachObserver (Observer *obs)
Detaches an Observer.
virtual void notifyObservers ()
Should be called when the Subject changes. Calls update() of all attached Observers.
Private Attributes
vector< Observer * > mObservers
Detailed Description
Member of pattern Observer as Subject. Can be observed. Observers can be attached and detached. When the Subject changes notifyObservers() should be called.
Member Function Documentation
attachObserver()
void Subject::attachObserver (Observer * obs) virtual
Attaches an Observer.
Parameters
an Observer.
Returns
none.
References mObservers.
Referenced by HumanHerold::attachToSubject().
detachObserver()
void Subject::detachObserver (Observer * obs) virtual
Detaches an Observer.
Parameters
an instance of as Observer.
Returns
none.
References mObservers.
notifyObservers()
void Subject::notifyObservers (void) virtual
Should be called when the Subject changes. Calls update() of all attached Observers.
Parameters
none.
Returns
none.
References mObservers.
Referenced by HumanLifeChain::addNewBorn(), and HumanLifeChain::removeOldest().
Member Data Documentation
mObservers
vector<Observer*> Subject::mObservers private
Contains the observers.
Referenced by attachObserver(), detachObserver(), and notifyObservers().
The documentation for this class was generated from the following files:
human.h
human.cpp