MindWorld: DestinyAdapter Class Reference
DestinyAdapter Class Reference
Member of pattern Adapter as Adapter and Target. Member of pattern Adapter as Client. Member of pattern Singleton. Member of pattern ChainOfresponsibility as Client. This class holds the entirety of all life form instances that can be affected by a set of predefined actions, can give some basic quantitative informations and contains a few helper functions for the god.
#include <destinyAdapter.h>
Public Member Functions
void createProblemForLFE (LifeFormEntity *lf)
Creates a problem for a specific life form.
void rendevouzTwoLFEs (LifeFormEntity *lf, LifeFormEntity *otherLF)
The life form lf will meet otherLF and on arrival they add each other to there list of known life forms.
void killLFE (LifeFormEntity *lf)
Specific life form gets killed.
void mateTwoLFE (LifeFormEntity *lf, LifeFormEntity *otherLF)
Specific life form gets killed.
void evolveLFE (LifeFormEntity *lf)
Specific life form evolves by getting replaced with his higher developed form.
void devolveLFE (LifeFormEntity *lf)
Specific life form devolves by getting replaced with his lower developed form.
void addLFE (LifeFormEntity *lf)
Adds lf to the pool of life form instances.
void removeLFE (LifeFormEntity *lf)
Remove lf from the pool of life form instances.
unsigned long long getNumberOfAliveLFEs ()
Returns number of life forms that are actually active and initialised.
unsigned long long getNumberOfUnbornLFEs ()
Returns number of life forms that are queued up to be created.
unsigned long long getNumberOfDeadLFEs ()
Returns number of life forms that died.
LifeFormEntity * chooseRandomLFE ()
Returns an instance to an uniformly randomly chosen life form from the pool of life forms.
QString generateLFEName ()
Returns a randomly generated 4 letter long name.
Static Public Member Functions
static DestinyAdapter * Instance (QObject *parent)
Returns the unique DestinyAdapter. (Singleton)
Protected Member Functions
DestinyAdapter (QObject *parent)
Constructor of class DestinyAdapter.
~DestinyAdapter ()
Deconstructor of class DestinyAdapter.
Protected Attributes
QVector< LifeFormEntity * > LFEs
unsigned long long NumberOfDeadLFEs
LFJobHandler * ourJobHandler
Static Protected Attributes
static const int NUM_OF_CONCRETE_LIFEFORMS = 3
Private Member Functions
void createProblemForLifeForm (LifeForm *)
Create a problem for life form LF.
void rendevouzTwoLF (LifeForm *, LifeForm *)
Adds life form LF2 to the list of known life forms of LF1 and the other way around..
bool evolveLF (LifeForm *)
Creates a new lifeform.
bool devolveLF (LifeForm *)
Creates a new lifeform.
Static Private Member Functions
static Destiny * getDestiny ()
Returns the unique Destiny. (Singleton)
Static Private Attributes
static Destiny * ourDestiny = nullptr
Detailed Description
Member of pattern Adapter as Adapter and Target. Member of pattern Adapter as Client. Member of pattern Singleton. Member of pattern ChainOfresponsibility as Client. This class holds the entirety of all life form instances that can be affected by a set of predefined actions, can give some basic quantitative informations and contains a few helper functions for the god.
It can create problems for life form entities. It can manage to evolve or devolve life forms by replacing the object with a more or less developed form of itself. It can manage to kill a life form. It can manage two life forms mating with each other. It can manage two life forms meeting each other.
It's most important function is beeing an instance pool of naturally/artificial created life forms so the the god can randomly pick and alter the state of a life form easily.
Constructor & Destructor Documentation
DestinyAdapter()
DestinyAdapter::DestinyAdapter (QObject * parent) protected
Constructor of class DestinyAdapter.
Parameters
parent QT parent pointer.
Returns
none.
References LFJobHandler::Instance(), NumberOfDeadLFEs, and ourJobHandler.
~DestinyAdapter()
DestinyAdapter::~DestinyAdapter () protected
Deconstructor of class DestinyAdapter.
Member Function Documentation
addLFE()
void DestinyAdapter::addLFE (LifeFormEntity * lf)
Adds lf to the pool of life form instances.
Parameters
lf life form that gets added.
Returns
none.
References LFEs.
Referenced by LifeFormEntity::inhabitPlanet().
chooseRandomLFE()
LifeFormEntity * DestinyAdapter::chooseRandomLFE ()
Returns an instance to an uniformly randomly chosen life form from the pool of life forms.
Parameters
none.
Returns
pointer to randomly chosen life form.
References dist(), LFEs, and mt().
Referenced by GodAdapter::challengeLFEs().
createProblemForLFE()
void DestinyAdapter::createProblemForLFE (LifeFormEntity * lf)
Creates a problem for a specific life form.
Parameters
lf life form that has to solve a problem.
Returns
none.
References LifeFormEntity::solveProblem().
Referenced by GodAdapter::challengeLFEs().
createProblemForLifeForm()
void Destiny::createProblemForLifeForm (LifeForm * LF) inherited
Create a problem for life form LF.
Parameters
LF the life form for which problem is created.
Returns
none.
References LifeForm::solveProblem().
Referenced by God::SimulateTimeStep().
devolveLF()
bool Destiny::devolveLF (LifeForm * LF) inherited
Creates a new lifeform.
Parameters
a pointer of a lifeform.
Returns
FALSE.
References LifeForm::getDevLvl(), LifeForm::getHomePlanet(), NUM_OF_CONCRETE_LIFEFORMS, and LifeForm::startLife().
devolveLFE()
void DestinyAdapter::devolveLFE (LifeFormEntity * lf)
Specific life form devolves by getting replaced with his lower developed form.
Parameters
lf life form that devolves.
Returns
none.
References dist(), LifeFormEntity::getDevLvl(), LifeFormEntity::getHomePlanetEntity(), LifeFormEntity::getName(), LifeFormEntity::getRelativePos(), LifeFormEntity::inhabitPlanet(), LFEs, mt(), NUM_OF_CONCRETE_LIFEFORMS, ourJobHandler, and LFJobHandler::replaceLF().
Referenced by GodAdapter::challengeLFEs().
evolveLF()
bool Destiny::evolveLF (LifeForm * LF) inherited
Creates a new lifeform.
Parameters
a pointer of a lifeform.
Returns
FALSE.
References LifeForm::getDevLvl(), LifeForm::getHomePlanet(), NUM_OF_CONCRETE_LIFEFORMS, and LifeForm::startLife().
evolveLFE()
void DestinyAdapter::evolveLFE (LifeFormEntity * lf)
Specific life form evolves by getting replaced with his higher developed form.
Parameters
lf life form that evolves.
Returns
none.
References dist(), LifeFormEntity::getDevLvl(), LifeFormEntity::getHomePlanetEntity(), LifeFormEntity::getName(), LifeFormEntity::getRelativePos(), LifeFormEntity::inhabitPlanet(), LFEs, mt(), NUM_OF_CONCRETE_LIFEFORMS, ourJobHandler, and LFJobHandler::replaceLF().
Referenced by GodAdapter::challengeLFEs().
generateLFEName()
QString DestinyAdapter::generateLFEName ()
Returns a randomly generated 4 letter long name.
Parameters
none.
Returns
generated name.
References dist(), and mt().
Referenced by LFMateJob::createChild(), GodAdapter::createHighDevLFE(), GodAdapter::createLowDevLFE(), and GodAdapter::createMidDevLFE().
getDestiny()
Destiny * Destiny::getDestiny (void) static inherited
Returns the unique Destiny. (Singleton)
Parameters
none.
Returns
The single instance of class Destiny.
References Destiny::Destiny(), and Destiny::ourDestiny.
Referenced by God::createBigBang().
getNumberOfAliveLFEs()
unsigned long long DestinyAdapter::getNumberOfAliveLFEs ()
Returns number of life forms that are actually active and initialised.
Parameters
none.
Returns
number of living life forms.
References LFEs.
Referenced by GodAdapter::challengeLFEs().
getNumberOfDeadLFEs()
unsigned long long DestinyAdapter::getNumberOfDeadLFEs ()
Returns number of life forms that died.
Parameters
none.
Returns
counted number of life forms that have been killed.
References NumberOfDeadLFEs.
Referenced by GodAdapter::challengeLFEs().
getNumberOfUnbornLFEs()
unsigned long long DestinyAdapter::getNumberOfUnbornLFEs ()
Returns number of life forms that are queued up to be created.
Parameters
none.
Returns
number of active mating jobs over all life forms.
References LFMateJob::getMateJobCount().
Referenced by GodAdapter::challengeLFEs().
Instance()
DestinyAdapter * DestinyAdapter::Instance (QObject * parent) static
Returns the unique DestinyAdapter. (Singleton)
Parameters
parent QT parent pointer.
Returns
The single instance of class DestinyAdapter.
Referenced by GodAdapter::GodAdapter(), LFMateJob::LFMateJob(), LifeFormEntity::LifeFormEntity(), and LFMateJob::operator=().
killLFE()
void DestinyAdapter::killLFE (LifeFormEntity * lf)
Specific life form gets killed.
Parameters
lf life form that dies.
Returns
none.
References LFEs, and NumberOfDeadLFEs.
Referenced by GodAdapter::challengeLFEs().
mateTwoLFE()
void DestinyAdapter::mateTwoLFE (LifeFormEntity * lf, LifeFormEntity * otherLF)
Specific life form gets killed.
Parameters
lf life form that dies.
Returns
none.
References LifeFormEntity::mateWith().
Referenced by GodAdapter::challengeLFEs().
removeLFE()
void DestinyAdapter::removeLFE (LifeFormEntity * lf)
Remove lf from the pool of life form instances.
Parameters
lf life form that gets removed.
Returns
none.
References LFEs.
Referenced by LifeFormEntity::~LifeFormEntity().
rendevouzTwoLF()
void Destiny::rendevouzTwoLF (LifeForm * LF1, LifeForm * LF2) inherited
Adds life form LF2 to the list of known life forms of LF1 and the other way around..
Parameters
LF1 life form that is part of the rendevouz.
LF2 life form that is part of the rendevouz.
Returns
none.
References LifeForm::addKownLF().
Referenced by God::SimulateTimeStep().
rendevouzTwoLFEs()
void DestinyAdapter::rendevouzTwoLFEs (LifeFormEntity * lf, LifeFormEntity * otherLF)
The life form lf will meet otherLF and on arrival they add each other to there list of known life forms.
Parameters
lf life form that is part of the rendevouz.
otherLF life form that is part of the rendevouz.
Returns
none.
References LifeFormEntity::meetWith().
Referenced by GodAdapter::challengeLFEs().
Member Data Documentation
LFEs
QVector<LifeFormEntity*> DestinyAdapter::LFEs protected
Referenced by addLFE(), chooseRandomLFE(), devolveLFE(), evolveLFE(), getNumberOfAliveLFEs(), killLFE(), and removeLFE().
NUM_OF_CONCRETE_LIFEFORMS
const int DestinyAdapter::NUM_OF_CONCRETE_LIFEFORMS = 3 static protected
Referenced by devolveLFE(), and evolveLFE().
NumberOfDeadLFEs
unsigned long long DestinyAdapter::NumberOfDeadLFEs protected
Referenced by DestinyAdapter(), getNumberOfDeadLFEs(), and killLFE().
ourDestiny
Destiny * Destiny::ourDestiny = nullptr static protected inherited
Is set once, once getDestiny is called.(Singleton)
Referenced by Destiny::getDestiny().
ourJobHandler
LFJobHandler* DestinyAdapter::ourJobHandler protected
Referenced by DestinyAdapter(), devolveLFE(), and evolveLFE().
The documentation for this class was generated from the following files:
destinyAdapter.h
destinyAdapter.cpp