MindWorld: Universe Class Reference
Universe Class Reference
Member of pattern Singleton. Member of pattern Adapter as Adaptee. An instance of this class represents a universe. In our system only one Universe may exists at a time. It can contain a list of planets.
#include <universe.h>
Public Member Functions
void addNewPlanet (CartesianCoordAdapter)
Adds a new Plant.
Planet * getFirstPlanet ()
Returns the first planet of the universe.
Planet * getNextPlanet ()
Returns the next planet of the universe.
Planet * getLastPlanet ()
Returns the last planet of the universe.
unsigned long getTime ()
Returns the time of the universe.
Static Public Member Functions
static Universe * getUniverse ()
Gets the instance of the universe.
.
Protected Member Functions
Universe ()
Constructor.
~Universe ()
Destructor.
Protected Attributes
vector< Planet * > planets
Planet * actPlanet
unsigned long __creation_time
Static Protected Attributes
static Universe * ourUniverse = nullptr
Detailed Description
Member of pattern Singleton. Member of pattern Adapter as Adaptee. An instance of this class represents a universe. In our system only one Universe may exists at a time. It can contain a list of planets.
Constructor & Destructor Documentation
Universe()
Universe::Universe () protected
Constructor.
~Universe()
Universe::~Universe () protected
Destructor.
Member Function Documentation
addNewPlanet()
void Universe::addNewPlanet (CartesianCoordAdapter coords)
Adds a new Plant.
Parameters
a CartesianCoordAdapter.
Returns
none
Referenced by God::createBigBang().
getFirstPlanet()
Planet * Universe::getFirstPlanet (void)
Returns the first planet of the universe.
Parameters
none.
Returns
the first planet.
Referenced by God::createBigBang().
getLastPlanet()
Planet * Universe::getLastPlanet (void)
Returns the last planet of the universe.
Parameters
none.
Returns
the last planet.
getNextPlanet()
Planet * Universe::getNextPlanet (void)
Returns the next planet of the universe.
Parameters
none.
Returns
the next planet.
getTime()
unsigned long Universe::getTime (void)
Returns the time of the universe.
Parameters
none.
Returns
the time (DWORD).
Referenced by UniverseEntity::getTime(), and God::GetTimeOfUniverse().
getUniverse()
Universe * Universe::getUniverse (void) static
Gets the instance of the universe.
.
Parameters
none.
Returns
an instance of Universe.
Referenced by God::createBigBang(), and UniverseEntity::getTime().
Member Data Documentation
__creation_time
unsigned long Universe::__creation_time protected
actPlanet
Planet* Universe::actPlanet protected
ourUniverse
Universe * Universe::ourUniverse = nullptr static protected
< Is set once, once getUniverse() is called. Only one Universe object are allowed.
planets
vector<Planet*> Universe::planets protected
The documentation for this class was generated from the following files:
universe.h
universe.cpp