MindWorld: Planet Class Reference
Planet Class Reference
Member of pattern Adapter as Client. Member of pattern Adapter as Adaptee. An instance of this class represents a planet. Our planet system includes a localization system that uses cartesian coordinates.
#include <planet.h>
Public Member Functions
Planet (CartesianCoordAdapter)
Constructor of class Plant - overloaded method.
virtual ~Planet ()
Destructor.
bool addLF (LifeForm *)
Adds a lifeform to the planet.
Public Attributes
CartesianCoordAdapter coords
Protected Member Functions
Planet ()
Constructor of class Plant.
Protected Attributes
vector< LifeForm * > Inhabitants
Detailed Description
Member of pattern Adapter as Client. Member of pattern Adapter as Adaptee. An instance of this class represents a planet. Our planet system includes a localization system that uses cartesian coordinates.
Constructor & Destructor Documentation
Planet() [1/2]
Planet::Planet (CartesianCoordAdapter coord)
Constructor of class Plant - overloaded method.
Parameters
a instance of a class CartesianCoordAdapter.
References coords.
~Planet()
Planet::~Planet () virtual
Destructor.
Planet() [2/2]
Planet::Planet () protected
Constructor of class Plant.
Member Function Documentation
addLF()
bool Planet::addLF (LifeForm * LF)
Adds a lifeform to the planet.
Parameters
instance of a lifeform.
Returns
True, if it is the first lifeform, else False.
References LifeForm::getHomePlanet(), Inhabitants, and LifeForm::startLife().
Referenced by PlanetEntity::addInhabitant().
Member Data Documentation
coords
CartesianCoordAdapter Planet::coords
Referenced by PlanetEntity::calcRotAngles(), PlanetEntity::getInitialPlanetPos(), Planet(), and PlanetEntity::PlanetEntity().
Inhabitants
vector<LifeForm*> Planet::Inhabitants protected
Referenced by addLF().
The documentation for this class was generated from the following files:
planet.h
planet.cpp