MindWorld: Decorator Interface Reference
Decorator Interface Reference abstract
Member of pattern Decorator as Decorator. Adds additional functionality to MindWorldComponents, the method change() - if required.
#include <interfaces.h>
Public Member Functions
Decorator (MindWorldComponent *mwc)
Constructor of Decorator.
void change (char *text)
Changes a MindWorldComponent.
MindWorldComponent * get_mwc ()
virtual char * get_type ()=0
virtual int get_change_count ()
void set_change_count (int new_count)
virtual void ToWrite ()=0
prints the respective member attributes of Thinkable -primitives.
Private Attributes
MindWorldComponent * _mwc
int _change_count
Detailed Description
Member of pattern Decorator as Decorator. Adds additional functionality to MindWorldComponents, the method change() - if required.
Constructor & Destructor Documentation
Decorator()
Decorator::Decorator (MindWorldComponent * mwc)
Constructor of Decorator.
Parameters
a instance of MindWorldComponent.
References _mwc.
Member Function Documentation
change()
void Decorator::change (char * text) virtual
Changes a MindWorldComponent.
Parameters
a text.
Returns
none.
Implements MindWorldComponent.
References _mwc, and MindWorldComponent::change().
get_change_count()
virtual int MindWorldComponent::get_change_count () inline virtual inherited
Implemented in Explainable.
References MindWorldComponent::_change_count.
Referenced by View::change(), Thought::change(), Feeling::change(), MindWorld::change(), CreatedThought::change(), Thought::ReDo(), and Thought::UnDo().
get_mwc()
MindWorldComponent* Decorator::get_mwc () inline
References _mwc.
Referenced by Explainable::get_change_count(), Explainable::get_type(), and Explainable::ToWrite().
get_type()
virtual char* MindWorldComponent::get_type () pure virtual inherited
Implemented in Thought, View, CreatedThoughtProxy, CreatedThought, Explainable, OwnMW, MindWorld, and Feeling.
set_change_count()
void MindWorldComponent::set_change_count (int new_count) inline inherited
References MindWorldComponent::_change_count.
Referenced by View::change(), Thought::change(), Feeling::change(), MindWorld::change(), CreatedThought::change(), CreatedThought::CreatedThought(), Feeling::Feeling(), MindWorld::MindWorld(), Thought::ReDo(), Thought::Thought(), Thought::UnDo(), and View::View().
ToWrite()
virtual void Thinkable::ToWrite () pure virtual inherited
prints the respective member attributes of Thinkable -primitives.
Implemented in CreatedThoughtProxy, CreatedThought, Explainable, OwnMW, MindWorld, Feeling, Thought, and View.
Member Data Documentation
_change_count
int MindWorldComponent::_change_count private inherited
Referenced by MindWorldComponent::get_change_count(), and MindWorldComponent::set_change_count().
_mwc
MindWorldComponent* Decorator::_mwc private
0..*
Referenced by change(), Decorator(), and get_mwc().
The documentation for this interface was generated from the following files:
interfaces.h
decorator.cpp