MindWorld: LowDev_LF Class Reference
LowDev_LF Class Reference
Member of pattern ChainOfresponsibility as ConcreteHandler. Member of pattern Adapter as Adaptee. An instance of this class represents a low developed life form. This kind of life form has a 4 possibilities to react on problems: it may know or the solution, ignore the problem or ask a known life from, which is higher developed.
#include <lowDevLF.h>
Public Member Functions
LowDev_LF ()
Constructor of class LowDev_LF.
LowDev_LF (char *)
Constructor of class LowDev_LF - overloaded mathod.
~LowDev_LF ()
Destructor of class LowDev_LF.
virtual bool solveProblem ()
Here it will be decided, which method to choose to solve a problem.
virtual int getDevLvl ()
Get the development level of the liveform.
void knowSolution ()
The life form knows the solution of the problem.
void ignoreProblem ()
A problem was not solved and got igonred by the life form.
bool guessSolution ()
One of the ways to solve a problem. (handle a request)
CartesianCoordAdapter getPos ()
void addKownLF (LifeForm *)
A life form is added to the list of friends, the calling object has.
bool askKnownLF ()
One of the ways to solve a problem. The problem is "forwarded" to a higher life form.
Planet * getHomePlanet ()
Returns the home planet of the lifeform.
void startLife (Planet *)
The life begins on a planet.
Protected Attributes
vector< LifeForm * > knownLF
Planet * homePlanet
const char * believerOf
Static Protected Attributes
static int Dev_Level = 1
Detailed Description
Member of pattern ChainOfresponsibility as ConcreteHandler. Member of pattern Adapter as Adaptee. An instance of this class represents a low developed life form. This kind of life form has a 4 possibilities to react on problems: it may know or the solution, ignore the problem or ask a known life from, which is higher developed.
Constructor & Destructor Documentation
LowDev_LF() [1/2]
LowDev_LF::LowDev_LF ()
Constructor of class LowDev_LF.
LowDev_LF() [2/2]
LowDev_LF::LowDev_LF (char * godName)
Constructor of class LowDev_LF - overloaded mathod.
Parameters
a name of the god.
References LifeForm::believerOf.
~LowDev_LF()
LowDev_LF::~LowDev_LF ()
Destructor of class LowDev_LF.
Member Function Documentation
addKownLF()
void LifeForm::addKownLF (LifeForm * LF) inherited
A life form is added to the list of friends, the calling object has.
\param LF life form to add to the friend list.
Returns
none.
References LifeForm::knownLF.
Referenced by LifeFormEntity::addKnownLFE(), LifeFormEntity::operator=(), and Destiny::rendevouzTwoLF().
askKnownLF()
bool LifeForm::askKnownLF (void) inherited
One of the ways to solve a problem. The problem is "forwarded" to a higher life form.
Parameters
none.
Returns
TRUE, if problem solved this way - else FALSE.
References LifeForm::getDevLvl(), LifeForm::knownLF, and LifeForm::solveProblem().
Referenced by HighDev_LF::solveProblem(), MidDev_LF::solveProblem(), solveProblem(), LowDev_LFEntity::solveProblem(), HighDev_LFEntity::solveProblem(), and MidDev_LFEntity::solveProblem().
getDevLvl()
int LowDev_LF::getDevLvl (void) virtual
Get the development level of the liveform.
Parameters
none.
Returns
The development level.
Reimplemented from LifeForm.
Reimplemented in HighDev_LFEntity, LowDev_LFEntity, MidDev_LFEntity, MidDev_LF, and HighDev_LF.
References Dev_Level.
getHomePlanet()
Planet * LifeForm::getHomePlanet (void) inherited
Returns the home planet of the lifeform.
Parameters
none.
Returns
The Planet-Object (Client).
References LifeForm::homePlanet.
Referenced by Planet::addLF(), Destiny::devolveLF(), and Destiny::evolveLF().
getPos()
CartesianCoordAdapter LifeForm::getPos () inherited
guessSolution()
bool LowDev_LF::guessSolution (void)
One of the ways to solve a problem. (handle a request)
Parameters
none.
Returns
true, if problem solved this way. else, no.
Referenced by LowDev_LFEntity::guessSolution(), HighDev_LF::solveProblem(), MidDev_LF::solveProblem(), solveProblem(), MidDev_LFEntity::solveProblem(), HighDev_LFEntity::solveProblem(), and LowDev_LFEntity::solveProblem().
ignoreProblem()
void LowDev_LF::ignoreProblem (void)
A problem was not solved and got igonred by the life form.
Parameters
none.
Returns
none.
Referenced by LowDev_LFEntity::ignoreProblem(), HighDev_LF::solveProblem(), MidDev_LF::solveProblem(), solveProblem(), MidDev_LFEntity::solveProblem(), HighDev_LFEntity::solveProblem(), and LowDev_LFEntity::solveProblem().
knowSolution()
void LowDev_LF::knowSolution (void)
The life form knows the solution of the problem.
Parameters
none.
Returns
none.
Referenced by LowDev_LFEntity::knowSolution(), HighDev_LF::solveProblem(), MidDev_LF::solveProblem(), solveProblem(), MidDev_LFEntity::solveProblem(), HighDev_LFEntity::solveProblem(), and LowDev_LFEntity::solveProblem().
solveProblem()
bool LowDev_LF::solveProblem (void) virtual
Here it will be decided, which method to choose to solve a problem.
Parameters
none
Returns
true, if problem solved. else, no.
Reimplemented from LifeForm.
Reimplemented in HighDev_LF, and MidDev_LF.
References LifeForm::askKnownLF(), guessSolution(), ignoreProblem(), and knowSolution().
startLife()
void LifeForm::startLife (Planet * planet) inherited
The life begins on a planet.
Parameters
the planet.
Returns
none.
References LifeForm::believerOf, and LifeForm::homePlanet.
Referenced by Planet::addLF(), God::createBigBang(), Destiny::devolveLF(), and Destiny::evolveLF().
Member Data Documentation
believerOf
const char* LifeForm::believerOf protected inherited
Referenced by LifeFormEntity::getGodName(), HighDev_LF::HighDev_LF(), LifeFormEntity::LifeFormEntity(), LowDev_LF(), MidDev_LF::MidDev_LF(), LifeFormEntity::operator=(), and LifeForm::startLife().
Dev_Level
int LowDev_LF::Dev_Level = 1 static protected
< The level of the lifeform (LowDev).
Referenced by getDevLvl(), and LowDev_LFEntity::getDevLvl().
homePlanet
Planet* LifeForm::homePlanet protected inherited
Referenced by LifeForm::getHomePlanet(), LifeFormEntity::inhabitPlanet(), LifeFormEntity::LifeFormEntity(), LifeFormEntity::operator=(), and LifeForm::startLife().
knownLF
vector<LifeForm*> LifeForm::knownLF protected inherited
Referenced by LifeForm::addKownLF(), LifeForm::askKnownLF(), and LifeFormEntity::forgetAboutLFE().
The documentation for this class was generated from the following files:
lowDevLF.h
lowDefLF.cpp