MindWorld: CloneAdmin Class Reference
CloneAdmin Class Reference
Member of pattern Singleton. Used to administrate an Singleton.
Member of pattern Prototype as Client. Sets ConcretePrototype of the HumanBreeder. Stores a Woman and a Man as "clone prototype". They can be given to the breeder. Could be extended to administrate more than one HumanBreeder. Can exist only one time. This is realised using the Singleton Pattern.
#include <human.h>
Public Member Functions
void useClonePrototypeWoman ()
Let the HumanBreeder use the Woman as "clone prototype".
void useClonePrototypeMan ()
Let the HumanBreeder use the Man as "clone prototype".
Human * createClone ()
Let the HumanBreeder clone the given "clone prototype".
Static Public Member Functions
static CloneAdmin * Instance ()
Returns the single instance of CloneAdmin. Instantiates a HumanBreeder and a Woman and Man as "clone prototype".
Protected Member Functions
CloneAdmin ()
Creates new CloneAdmin. Use Instance() to get instance of CloneAdmin.
Private Attributes
HumanBreeder * mBreeder
The administrated HumanBreeder.
Woman * mPrototypeWoman
The Woman "clone pattern".
Man * mPrototypeMan
The Man "clone pattern".
Static Private Attributes
static CloneAdmin * mInstance = nullptr
The single instance of CloneAdmin.
Detailed Description
Member of pattern Singleton. Used to administrate an Singleton.
Member of pattern Prototype as Client. Sets ConcretePrototype of the HumanBreeder. Stores a Woman and a Man as "clone prototype". They can be given to the breeder. Could be extended to administrate more than one HumanBreeder. Can exist only one time. This is realised using the Singleton Pattern.
Constructor & Destructor Documentation
CloneAdmin()
CloneAdmin::CloneAdmin (void) protected
Creates new CloneAdmin. Use Instance() to get instance of CloneAdmin.
Parameters
none.
Returns
The one and only CloneAdmin.
References mBreeder, mPrototypeMan, and mPrototypeWoman.
Referenced by Instance().
Member Function Documentation
createClone()
Human * CloneAdmin::createClone (void)
Let the HumanBreeder clone the given "clone prototype".
Parameters
none.
Returns
a pointer to a cloned Human.
References HumanBreeder::createClone(), and mBreeder.
Referenced by HumanHandler::cloneHuman().
Instance()
CloneAdmin * CloneAdmin::Instance (void) static
Returns the single instance of CloneAdmin. Instantiates a HumanBreeder and a Woman and Man as "clone prototype".
Parameters
none.
Returns
instance of CloneAdmin.
References CloneAdmin(), and mInstance.
Referenced by HumanHandler::cloneHuman(), HumanHandler::useClonePrototypeMan(), and HumanHandler::useClonePrototypeWoman().
useClonePrototypeMan()
void CloneAdmin::useClonePrototypeMan (void)
Let the HumanBreeder use the Man as "clone prototype".
Parameters
none.
Returns
none.
Referenced by HumanHandler::useClonePrototypeMan().
useClonePrototypeWoman()
void CloneAdmin::useClonePrototypeWoman (void)
Let the HumanBreeder use the Woman as "clone prototype".
Parameters
none.
Returns
none.
Referenced by HumanHandler::useClonePrototypeWoman().
Member Data Documentation
mBreeder
HumanBreeder* CloneAdmin::mBreeder private
The administrated HumanBreeder.
Referenced by CloneAdmin(), and createClone().
mInstance
CloneAdmin * CloneAdmin::mInstance = nullptr static private
The single instance of CloneAdmin.
Is set once, once CloneAdmin::Instance is called. This controls the restriction to number of CloneAdmin objects.
Referenced by Instance().
mPrototypeMan
Man* CloneAdmin::mPrototypeMan private
The Man "clone pattern".
Referenced by CloneAdmin().
mPrototypeWoman
Woman* CloneAdmin::mPrototypeWoman private
The Woman "clone pattern".
Referenced by CloneAdmin().
The documentation for this class was generated from the following files:
human.h
human.cpp