MindWorld: HumanLifeChain Class Reference
HumanLifeChain Class Reference
Member of pattern Singleton.
Member of pattern Observer as ConcreteSubject.
Member of pattern Iterator. Is the list of Humans. All created Humans should be put into the List. Exceptions are clone prototypes for example. They are no "real" Humans. Extends Subject, so Observers can be attached. It will notify all Observers if an Human has been added or removed. It's the List for the Iterator HumanLifeChainIterator. Can exist only one time. This is realised using the Singleton Pattern.
#include <human.h>
Public Member Functions
void addNewBorn (Human *human)
Adds an Human to the list. It will be put on end of list. Creates an HumanLifeChainElement to store the Human.
void removeOldest ()
Returns the first element of list. It contains the oldest Human.
HumanLifeChainElement * firstElement ()
Returns the first element of list. It contains the oldest Human.
HumanLifeChainElement * lastElement ()
Returns the last element of list. It contains the youngest Human.
virtual void attachObserver (Observer *obs)
Attaches an Observer.
virtual void detachObserver (Observer *obs)
Detaches an Observer.
virtual void notifyObservers ()
Should be called when the Subject changes. Calls update() of all attached Observers.
Static Public Member Functions
static HumanLifeChain * Instance ()
Create and returns the single instance of HumanLifeChain (Pattern Singleton)
Protected Member Functions
HumanLifeChain ()
Constructor of class HumanLifeChain.
Private Attributes
HumanLifeChainElement * mFirstElement
HumanLifeChainElement * mLastElement
vector< Observer * > mObservers
Static Private Attributes
static HumanLifeChain * mInstance = nullptr
Detailed Description
Member of pattern Singleton.
Member of pattern Observer as ConcreteSubject.
Member of pattern Iterator. Is the list of Humans. All created Humans should be put into the List. Exceptions are clone prototypes for example. They are no "real" Humans. Extends Subject, so Observers can be attached. It will notify all Observers if an Human has been added or removed. It's the List for the Iterator HumanLifeChainIterator. Can exist only one time. This is realised using the Singleton Pattern.
Constructor & Destructor Documentation
HumanLifeChain()
HumanLifeChain::HumanLifeChain () protected
Constructor of class HumanLifeChain.
References mFirstElement, and mLastElement.
Referenced by Instance().
Member Function Documentation
addNewBorn()
void HumanLifeChain::addNewBorn (Human * human)
Adds an Human to the list. It will be put on end of list. Creates an HumanLifeChainElement to store the Human.
Parameters
a pointer to Human.
Returns
none.
References mFirstElement, mLastElement, Subject::notifyObservers(), and HumanLifeChainElement::setNextElement().
Referenced by HumanBreeder::createClone(), OldestPartnerFinderStrategy::searchPartnersAndCreateHuman(), and RandomPartnerFinderStrategy::searchPartnersAndCreateHuman().
attachObserver()
void Subject::attachObserver (Observer * obs) virtual inherited
Attaches an Observer.
Parameters
an Observer.
Returns
none.
References Subject::mObservers.
Referenced by HumanHerold::attachToSubject().
detachObserver()
void Subject::detachObserver (Observer * obs) virtual inherited
Detaches an Observer.
Parameters
an instance of as Observer.
Returns
none.
References Subject::mObservers.
firstElement()
HumanLifeChainElement * HumanLifeChain::firstElement (void)
Returns the first element of list. It contains the oldest Human.
Parameters
none.
Returns
a HumanLifeChainElement (the oldest Human).
References mFirstElement.
Referenced by HumanDeathHerold::attachToSubject(), HumanLifeChainIterator::firstHuman(), HumanLifeChainIterator::HumanLifeChainIterator(), and HumanDeathHerold::update().
Instance()
HumanLifeChain * HumanLifeChain::Instance (void) static
Create and returns the single instance of HumanLifeChain (Pattern Singleton)
Parameters
none.
Returns
instance of HumanLifeChain.
References HumanLifeChain(), and mInstance.
Referenced by God::createBigBang(), HumanBreeder::createClone(), Death::killOldest(), OldestPartnerFinderStrategy::searchPartnersAndCreateHuman(), RandomPartnerFinderStrategy::searchPartnersAndCreateHuman(), HumanLifeHerold::update(), and HumanDeathHerold::update().
lastElement()
HumanLifeChainElement * HumanLifeChain::lastElement (void)
Returns the last element of list. It contains the youngest Human.
Parameters
none.
Returns
The youngest Human.
References mLastElement.
Referenced by HumanLifeHerold::attachToSubject(), and HumanLifeHerold::update().
notifyObservers()
void Subject::notifyObservers (void) virtual inherited
Should be called when the Subject changes. Calls update() of all attached Observers.
Parameters
none.
Returns
none.
References Subject::mObservers.
Referenced by addNewBorn(), and removeOldest().
removeOldest()
void HumanLifeChain::removeOldest (void)
Returns the first element of list. It contains the oldest Human.
Parameters
none.
Returns
none.
References HumanLifeChainElement::getHuman(), HumanLifeChainElement::getNextElement(), mFirstElement, mLastElement, and Subject::notifyObservers().
Referenced by Death::killOldest().
Member Data Documentation
mFirstElement
HumanLifeChainElement* HumanLifeChain::mFirstElement private
Stores the first element of list. It contains the oldest Human.
Referenced by addNewBorn(), firstElement(), HumanLifeChain(), and removeOldest().
mInstance
HumanLifeChain * HumanLifeChain::mInstance = nullptr static private
Stores the single instance of HumanLifeChain.
Is set once, once HumanLifeChain::Instance is called. This controls the restriction to number of HumanLifeChain objects.
Referenced by Instance().
mLastElement
HumanLifeChainElement* HumanLifeChain::mLastElement private
Stores the last element of list. It contains the youngest Human.
Referenced by addNewBorn(), HumanLifeChain(), lastElement(), and removeOldest().
mObservers
vector<Observer*> Subject::mObservers private inherited
Contains the observers.
Referenced by Subject::attachObserver(), Subject::detachObserver(), and Subject::notifyObservers().
The documentation for this class was generated from the following files:
human.h
human.cpp