MindWorld: HumanHandler Class Reference
HumanHandler Class Reference
Member of pattern Singleton.
Member of pattern Facade as Facade. Its used as Interface for the Human subsystem.
#include <human.h>
Public Member Functions
void useClonePrototypeWoman ()
Sets the "clone prototype" to Woman. See also CloneAdmin.
void useClonePrototypeMan ()
Sets the "clone prototype" to Man. See also CloneAdmin.
void cloneHuman ()
Clones Human. See also CloneAdmin.
void createHumanNaturally ()
Creates a Human - having sex. See also PartnerFinder.
void killOldest ()
Kills oldest Human. See also Death.
Static Public Member Functions
static HumanHandler * Instance ()
Returns the single instance of HumanHandler.
Protected Member Functions
HumanHandler ()
Constructor of HumanHandler. Use Instance() to get instance of HumanHandler.
Static Private Attributes
static HumanHandler * mInstance = nullptr
The single instance of HumanHandler.
Detailed Description
Member of pattern Singleton.
Member of pattern Facade as Facade. Its used as Interface for the Human subsystem.
Constructor & Destructor Documentation
HumanHandler()
HumanHandler::HumanHandler () protected
Constructor of HumanHandler. Use Instance() to get instance of HumanHandler.
Referenced by Instance().
Member Function Documentation
cloneHuman()
void HumanHandler::cloneHuman (void)
Clones Human. See also CloneAdmin.
Parameters
none.
Returns
none.
References CloneAdmin::createClone(), and CloneAdmin::Instance().
createHumanNaturally()
void HumanHandler::createHumanNaturally (void)
Creates a Human - having sex. See also PartnerFinder.
Parameters
none.
Returns
none.
References PartnerFinder::searchPartnersAndCreateHuman(), and PartnerFinder::setPartnerFinderStrategy().
Instance()
HumanHandler * HumanHandler::Instance (void) static
Returns the single instance of HumanHandler.
Parameters
none.
Returns
single instance of HumanHandler.
References HumanHandler(), and mInstance.
Referenced by God::createBigBang().
killOldest()
void HumanHandler::killOldest (void)
Kills oldest Human. See also Death.
Parameters
none.
Returns
none.
References Death::Instance(), and Death::killOldest().
Referenced by God::createBigBang().
useClonePrototypeMan()
void HumanHandler::useClonePrototypeMan (void)
Sets the "clone prototype" to Man. See also CloneAdmin.
Parameters
none.
Returns
none.
References CloneAdmin::Instance(), and CloneAdmin::useClonePrototypeMan().
useClonePrototypeWoman()
void HumanHandler::useClonePrototypeWoman (void)
Sets the "clone prototype" to Woman. See also CloneAdmin.
Parameters
none.
Returns
none.
References CloneAdmin::Instance(), and CloneAdmin::useClonePrototypeWoman().
Member Data Documentation
mInstance
HumanHandler * HumanHandler::mInstance = nullptr static private
The single instance of HumanHandler.
Is set once, once HumanHandler::Instance is called. This controls the restriction to number of HumanHandler objects.
Referenced by Instance().
The documentation for this class was generated from the following files:
human.h
human.cpp