MindWorld: Man Class Reference
Man Class Reference
Member of pattern Prototype as ConcretePrototype. Can be cloned to create new Man Objects.
#include <human.h>
Public Member Functions
Man ()
Constructor of class Man.
Human * clone ()
Clones a human and builds a Man.
string getEyeColor ()
Returns the eye color of the human.
void setEyeColor (string str)
Sets the eye color of the human.
Private Attributes
OwnMW * mMindWorld
string mEyeColor
Static Private Attributes
static int mPossibleEyeColorsLength = 4
static string mPossibleEyeColors [] = {"green", "blue", "brown", "grey"}
Detailed Description
Member of pattern Prototype as ConcretePrototype. Can be cloned to create new Man Objects.
Constructor & Destructor Documentation
Man()
Man::Man ()
Constructor of class Man.
Referenced by clone().
Member Function Documentation
clone()
Human * Man::clone (void) virtual
Clones a human and builds a Man.
Parameters
none.
Returns
an instance of a Human.
Implements Human.
References Human::getEyeColor(), Man(), and Human::setEyeColor().
getEyeColor()
string Human::getEyeColor (void) inherited
Returns the eye color of the human.
Parameters
none.
Returns
the eye color (string).
References Human::mEyeColor.
Referenced by clone(), Woman::clone(), God::createBigBang(), and HumanLifeHerold::update().
setEyeColor()
void Human::setEyeColor (string str) inherited
Sets the eye color of the human.
Parameters
the eye color (string).
Returns
none.
References Human::mEyeColor.
Referenced by clone(), and Woman::clone().
Member Data Documentation
mEyeColor
string Human::mEyeColor private inherited
Referenced by Human::getEyeColor(), Human::Human(), and Human::setEyeColor().
mMindWorld
OwnMW* Human::mMindWorld private inherited
Referenced by Human::Human().
mPossibleEyeColors
string Human::mPossibleEyeColors = {"green", "blue", "brown", "grey"} static private inherited
Referenced by Human::Human().
mPossibleEyeColorsLength
int Human::mPossibleEyeColorsLength = 4 static private inherited
< Number of eye colours. Array of names of eye colours.
Referenced by Human::Human().
The documentation for this class was generated from the following files:
human.h
human.cpp