MindWorld: HumanLifeChainElement Class Reference
HumanLifeChainElement Class Reference
Member of pattern Singleton.
Member of pattern Iterator. Element of the HumanLifeChain. Stores one Human. Stores a pointer to the next element of the chain.
#include <human.h>
Public Member Functions
HumanLifeChainElement (Human *human)
Creates new HumanLifeChainElement. No empty element can exist..
void setNextElement (HumanLifeChainElement *element)
Sets the next element of the chain.
HumanLifeChainElement * getNextElement ()
Returns the next element of the chain.
Human * getHuman ()
Returns the Human given to the Constructor.
void deleteHuman ()
Deletes a instance of Human.
Private Attributes
HumanLifeChainElement * mNextElement
Stores the next element of the chain.
Human * mHuman
Stores the Human given to the Constructor.
Detailed Description
Member of pattern Singleton.
Member of pattern Iterator. Element of the HumanLifeChain. Stores one Human. Stores a pointer to the next element of the chain.
Constructor & Destructor Documentation
HumanLifeChainElement()
HumanLifeChainElement::HumanLifeChainElement (Human * human)
Creates new HumanLifeChainElement. No empty element can exist..
Parameters
human is the human to clone.
Returns
a HumanLifeChainElement.
References mHuman, and mNextElement.
Member Function Documentation
deleteHuman()
void HumanLifeChainElement::deleteHuman (void)
Deletes a instance of Human.
Parameters
none.
Returns
none.
References mHuman.
getHuman()
Human * HumanLifeChainElement::getHuman (void)
Returns the Human given to the Constructor.
Parameters
none.
Returns
Human given to the Constructor.
References mHuman.
Referenced by HumanLifeHerold::attachToSubject(), HumanDeathHerold::attachToSubject(), HumanLifeChainIterator::nextHuman(), HumanLifeChain::removeOldest(), HumanLifeHerold::update(), and HumanDeathHerold::update().
getNextElement()
HumanLifeChainElement * HumanLifeChainElement::getNextElement (void)
Returns the next element of the chain.
Parameters
none.
Returns
a pointer to a HumanLifeChainElement.
References mNextElement.
Referenced by HumanLifeChainIterator::nextHuman(), and HumanLifeChain::removeOldest().
setNextElement()
void HumanLifeChainElement::setNextElement (HumanLifeChainElement * element)
Sets the next element of the chain.
Parameters
a pointer to a HumanLifeChainElement.
Returns
none.
References mNextElement.
Referenced by HumanLifeChain::addNewBorn().
Member Data Documentation
mHuman
Human* HumanLifeChainElement::mHuman private
Stores the Human given to the Constructor.
Referenced by deleteHuman(), getHuman(), and HumanLifeChainElement().
mNextElement
HumanLifeChainElement* HumanLifeChainElement::mNextElement private
Stores the next element of the chain.
Referenced by getNextElement(), HumanLifeChainElement(), and setNextElement().
The documentation for this class was generated from the following files:
human.h
human.cpp