MindWorld: LFJobHandler Class Reference
LFJobHandler Class Reference
Member of pattern Singleton. Member of pattern Facade as Facade. Member of pattern Command as Caller. Defines a handler that holds a job queue for every existing life form to easily deal with situations like the death/deletion of a life form instance in a centralized manner so they don't have to deal with job specific problems.
#include <lfJobHandler.h>
Public Member Functions
void createJobQueue (LifeFormEntity *lf)
Creates a job queue for a specific life form.
void deleteJobQueue (LifeFormEntity *lf)
Deletes job queue for a specific life form.
void addJob (LifeFormEntity *lf, LFJob *j)
Adds job to job queue of an specific life form.
bool workOnTopJob (LifeFormEntity *lf)
Works on top priority job.
void copyJobQueue (LifeFormEntity *targetLF, LifeFormEntity *sourceLF)
Assigns job queue copy of sourceLF to targetLF.
void replaceLF (LifeFormEntity *oldLFRef, LifeFormEntity *newLFRef)
Replaces all occurences of oldLFRef with newLFRef.
void removeJobsWithParticipant (LifeFormEntity *targetLF, LifeFormEntity *pRef)
Removes all jobs that contain pRef from targetLFs job queue.
void removeJobsMutual (LifeFormEntity *lf, LifeFormEntity *orherLF)
Removes all jobs that contain otherLF from lfs job queue and the other way around.
Static Public Member Functions
static LFJobHandler * Instance (QObject *parent)
Returns the unique LFJobHandler. (Singleton)
Private Member Functions
std::priority_queue< LFJob * > * getCopyOfJobQueue (LifeFormEntity *targetLF, LifeFormEntity *workingLF=nullptr)
Returns exact copy of a job queue and replaces workingLF if specified.
void removeTopJob (std::priority_queue< LFJob * > *currentJobQueue)
Deletes top priority job from a job queue.
void clearJobQueue (std::priority_queue< LFJob * > *currentJobQueue)
Deletes all jobs of a job queue.
LFJobHandler (QObject *parent)
Constructor of class LFJobHandler.
~LFJobHandler ()
Deconstructor of class LFJobHandler.
Private Attributes
QVector< LifeFormEntity * > lifeforms
QVector< std::priority_queue< LFJob * > * > jobQueues
Detailed Description
Member of pattern Singleton. Member of pattern Facade as Facade. Member of pattern Command as Caller. Defines a handler that holds a job queue for every existing life form to easily deal with situations like the death/deletion of a life form instance in a centralized manner so they don't have to deal with job specific problems.
The main functionality of this class is to have the ability to replace references in jobs globally or remove jobs with a specific reference.
The basic functionality of adding jobs and working on the top priority job of a life form is also given.
Constructor & Destructor Documentation
LFJobHandler()
LFJobHandler::LFJobHandler (QObject * parent) private
Constructor of class LFJobHandler.
Parameters
parent QT parent pointer.
Returns
none.
~LFJobHandler()
LFJobHandler::~LFJobHandler () private
Deconstructor of class LFJobHandler.
Member Function Documentation
addJob()
void LFJobHandler::addJob (LifeFormEntity * lf, LFJob * j)
Adds job to job queue of an specific life form.
Parameters
address of life form
job instance
Returns
none.
References LFJob::getWorkingLF(), jobQueues, and lifeforms.
Referenced by LifeFormEntity::askKnownLFE(), LifeFormEntity::calcNextStep(), LifeFormEntity::mateWith(), LifeFormEntity::meetWith(), MidDev_LFEntity::solveProblem(), HighDev_LFEntity::solveProblem(), LowDev_LFEntity::solveProblem(), and LifeFormEntity::solveProblem().
clearJobQueue()
void LFJobHandler::clearJobQueue (std::priority_queue< LFJob * > * currentJobQueue) private
Deletes all jobs of a job queue.
Parameters
job queue
Returns
none.
References removeTopJob().
Referenced by copyJobQueue(), and deleteJobQueue().
copyJobQueue()
void LFJobHandler::copyJobQueue (LifeFormEntity * targetLF, LifeFormEntity * sourceLF)
Assigns job queue copy of sourceLF to targetLF.
Parameters
address of target life form
address of source life form
Returns
none.
References clearJobQueue(), getCopyOfJobQueue(), jobQueues, and lifeforms.
Referenced by LifeFormEntity::operator=().
createJobQueue()
void LFJobHandler::createJobQueue (LifeFormEntity * lf)
Creates a job queue for a specific life form.
Parameters
address of life form
Returns
none.
References jobQueues, and lifeforms.
Referenced by LifeFormEntity::LifeFormEntity().
deleteJobQueue()
void LFJobHandler::deleteJobQueue (LifeFormEntity * lf)
Deletes job queue for a specific life form.
Parameters
address of life form
Returns
none.
References clearJobQueue(), jobQueues, lifeforms, and removeJobsWithParticipant().
Referenced by replaceLF(), and LifeFormEntity::~LifeFormEntity().
getCopyOfJobQueue()
priority_queue< LFJob * > * LFJobHandler::getCopyOfJobQueue (LifeFormEntity * targetLF, LifeFormEntity * workingLF = nullptr) private
Returns exact copy of a job queue and replaces workingLF if specified.
Parameters
address of target life form
address of working life form
Returns
copy.
References LFJob::changeWorkingLF(), jobQueues, and lifeforms.
Referenced by copyJobQueue().
Instance()
LFJobHandler * LFJobHandler::Instance (QObject * parent) static
Returns the unique LFJobHandler. (Singleton)
Parameters
parent QT parent pointer.
Returns
The single instance of class LFJobHandler.
Referenced by DestinyAdapter::DestinyAdapter(), and LifeFormEntity::LifeFormEntity().
removeJobsMutual()
void LFJobHandler::removeJobsMutual (LifeFormEntity * lf, LifeFormEntity * orherLF)
Removes all jobs that contain otherLF from lfs job queue and the other way around.
Parameters
address of life form
address of other life form
Returns
none.
References removeJobsWithParticipant().
removeJobsWithParticipant()
void LFJobHandler::removeJobsWithParticipant (LifeFormEntity * targetLF, LifeFormEntity * pRef)
Removes all jobs that contain pRef from targetLFs job queue.
Parameters
address of target life form
address that will get jobs removed
Returns
none.
References LFJob::getParticipants(), jobQueues, and lifeforms.
Referenced by deleteJobQueue(), and removeJobsMutual().
removeTopJob()
void LFJobHandler::removeTopJob (std::priority_queue< LFJob * > * currentJobQueue) private
Deletes top priority job from a job queue.
Parameters
job queue
Returns
none.
Referenced by clearJobQueue(), and workOnTopJob().
replaceLF()
void LFJobHandler::replaceLF (LifeFormEntity * oldLFRef, LifeFormEntity * newLFRef)
Replaces all occurences of oldLFRef with newLFRef.
Parameters
address to be replaced.
new address.
Returns
none.
References LFJob::changeParticipants(), LFJob::changeWorkingLF(), deleteJobQueue(), LFJob::getParticipants(), LFJob::getWorkingLF(), jobQueues, and lifeforms.
Referenced by DestinyAdapter::devolveLFE(), and DestinyAdapter::evolveLFE().
workOnTopJob()
bool LFJobHandler::workOnTopJob (LifeFormEntity * lf)
Works on top priority job.
Parameters
address of life form
Returns
false if there are no jobs to work on.
References jobQueues, lifeforms, and removeTopJob().
Referenced by LifeFormEntity::calcNextStep().
Member Data Documentation
jobQueues
QVector<std::priority_queue<LFJob*>*> LFJobHandler::jobQueues private
Referenced by addJob(), copyJobQueue(), createJobQueue(), deleteJobQueue(), getCopyOfJobQueue(), removeJobsWithParticipant(), replaceLF(), and workOnTopJob().
lifeforms
QVector<LifeFormEntity*> LFJobHandler::lifeforms private
Referenced by addJob(), copyJobQueue(), createJobQueue(), deleteJobQueue(), getCopyOfJobQueue(), removeJobsWithParticipant(), replaceLF(), and workOnTopJob().
The documentation for this class was generated from the following files:
lfJobHandler.h
lfJobHandler.cpp