MindWorld: HumanHerold Class Reference
HumanHerold Class Reference abstract
Member of pattern Observer as Observer. Abstract Observer for HumanLifeChain.
#include <human.h>
Public Member Functions
void attachToSubject (HumanLifeChain *chain)
Attach this to the given HumanLifeChain.
void update ()=0
Should be called by the HumanLifeChain when it changes.
Protected Attributes
HumanLifeChain * mChain
The HumanLifeChain this is attached to.
Detailed Description
Member of pattern Observer as Observer. Abstract Observer for HumanLifeChain.
Member Function Documentation
attachToSubject()
void HumanHerold::attachToSubject (HumanLifeChain * chain)
Attach this to the given HumanLifeChain.
Parameters
a HumanLifeChain.
Returns
none.
References Subject::attachObserver(), and mChain.
Referenced by HumanLifeHerold::attachToSubject(), HumanDeathHerold::attachToSubject(), and God::createBigBang().
update()
void HumanHerold::update () pure virtual
Should be called by the HumanLifeChain when it changes.
Implements Observer.
Implemented in HumanDeathHerold, and HumanLifeHerold.
Member Data Documentation
mChain
HumanLifeChain* HumanHerold::mChain protected
The HumanLifeChain this is attached to.
Referenced by attachToSubject(), HumanLifeHerold::update(), and HumanDeathHerold::update().
The documentation for this class was generated from the following files:
human.h
human.cpp