MindWorld: LifeForm Class Reference
LifeForm Class Reference
Member of pattern ChainOfresponsibility as Handler. Member of pattern Adapter as Adaptee. An instance of this class represents a life form in general. This life form has the minimum set of members a life form needs in our system.
#include <lifeForm.h>
Public Member Functions
CartesianCoordAdapter getPos ()
virtual bool solveProblem ()
Solves a given problem..
virtual int getDevLvl ()
Get the development level of the liveform.
void addKownLF (LifeForm *)
A life form is added to the list of friends, the calling object has.
bool askKnownLF ()
One of the ways to solve a problem. The problem is "forwarded" to a higher life form.
Planet * getHomePlanet ()
Returns the home planet of the lifeform.
void startLife (Planet *)
The life begins on a planet.
Protected Attributes
vector< LifeForm * > knownLF
Planet * homePlanet
const char * believerOf
Static Protected Attributes
static int Dev_Level = 0
Detailed Description
Member of pattern ChainOfresponsibility as Handler. Member of pattern Adapter as Adaptee. An instance of this class represents a life form in general. This life form has the minimum set of members a life form needs in our system.
Member Function Documentation
addKownLF()
void LifeForm::addKownLF (LifeForm * LF)
A life form is added to the list of friends, the calling object has.
\param LF life form to add to the friend list.
Returns
none.
References knownLF.
Referenced by LifeFormEntity::addKnownLFE(), LifeFormEntity::operator=(), and Destiny::rendevouzTwoLF().
askKnownLF()
bool LifeForm::askKnownLF (void)
One of the ways to solve a problem. The problem is "forwarded" to a higher life form.
Parameters
none.
Returns
TRUE, if problem solved this way - else FALSE.
References getDevLvl(), knownLF, and solveProblem().
Referenced by HighDev_LF::solveProblem(), MidDev_LF::solveProblem(), LowDev_LF::solveProblem(), LowDev_LFEntity::solveProblem(), HighDev_LFEntity::solveProblem(), and MidDev_LFEntity::solveProblem().
getDevLvl()
int LifeForm::getDevLvl (void) virtual
Get the development level of the liveform.
Parameters
none.
Returns
The development level.
Reimplemented in LifeFormEntity, HighDev_LFEntity, LowDev_LFEntity, MidDev_LFEntity, LowDev_LF, MidDev_LF, and HighDev_LF.
References Dev_Level.
Referenced by askKnownLF(), Destiny::devolveLF(), and Destiny::evolveLF().
getHomePlanet()
Planet * LifeForm::getHomePlanet (void)
Returns the home planet of the lifeform.
Parameters
none.
Returns
The Planet-Object (Client).
References homePlanet.
Referenced by Planet::addLF(), Destiny::devolveLF(), and Destiny::evolveLF().
getPos()
CartesianCoordAdapter LifeForm::getPos ()
solveProblem()
bool LifeForm::solveProblem (void) virtual
Solves a given problem..
Parameters
none.
Returns
a status.
Reimplemented in LowDev_LF, HighDev_LF, and MidDev_LF.
Referenced by askKnownLF(), Destiny::createProblemForLifeForm(), and LifeFormEntity::solveProblem().
startLife()
void LifeForm::startLife (Planet * planet)
The life begins on a planet.
Parameters
the planet.
Returns
none.
References believerOf, and homePlanet.
Referenced by Planet::addLF(), God::createBigBang(), Destiny::devolveLF(), and Destiny::evolveLF().
Member Data Documentation
believerOf
const char* LifeForm::believerOf protected
Referenced by LifeFormEntity::getGodName(), HighDev_LF::HighDev_LF(), LifeFormEntity::LifeFormEntity(), LowDev_LF::LowDev_LF(), MidDev_LF::MidDev_LF(), LifeFormEntity::operator=(), and startLife().
Dev_Level
int LifeForm::Dev_Level = 0 static protected
< The level of the lifeform (0).
Referenced by getDevLvl(), and LifeFormEntity::getDevLvl().
homePlanet
Planet* LifeForm::homePlanet protected
Referenced by getHomePlanet(), LifeFormEntity::inhabitPlanet(), LifeFormEntity::LifeFormEntity(), LifeFormEntity::operator=(), and startLife().
knownLF
vector<LifeForm*> LifeForm::knownLF protected
Referenced by addKownLF(), askKnownLF(), and LifeFormEntity::forgetAboutLFE().
The documentation for this class was generated from the following files:
lifeForm.h
lifeForm.cpp