MindWorld: Explainable Class Reference
Explainable Class Reference
Member of pattern Decorator as ConcreteDecorator. Decorates the "ToWrite()"-Method of Thinkable objects.
#include <implementations.h>
Public Member Functions
Explainable (MindWorldComponent *mwc)
Constructor of Explainable.
void ToWrite ()
char * get_type ()
Returns the type of a mindworldcomponent.
virtual int get_change_count ()
void change (char *text)
Changes a MindWorldComponent.
MindWorldComponent * get_mwc ()
void set_change_count (int new_count)
Private Attributes
MindWorldComponent * _mwc
int _change_count
Detailed Description
Member of pattern Decorator as ConcreteDecorator. Decorates the "ToWrite()"-Method of Thinkable objects.
Constructor & Destructor Documentation
Explainable()
Explainable::Explainable (MindWorldComponent * mwc)
Constructor of Explainable.
Parameters
pointer to a MindWorldComponent object.
Member Function Documentation
change()
void Decorator::change (char * text) virtual inherited
Changes a MindWorldComponent.
Parameters
a text.
Returns
none.
Implements MindWorldComponent.
References Decorator::_mwc, and MindWorldComponent::change().
get_change_count()
virtual int Explainable::get_change_count () inline virtual
Implements MindWorldComponent.
References Decorator::get_mwc().
Referenced by ToWrite().
get_mwc()
MindWorldComponent* Decorator::get_mwc () inline inherited
References Decorator::_mwc.
Referenced by get_change_count(), get_type(), and ToWrite().
get_type()
char * Explainable::get_type (void) virtual
Returns the type of a mindworldcomponent.
Parameters
none.
Returns
a string.
Implements MindWorldComponent.
References Decorator::get_mwc().
Referenced by ToWrite().
set_change_count()
void MindWorldComponent::set_change_count (int new_count) inline inherited
References MindWorldComponent::_change_count.
Referenced by View::change(), Thought::change(), Feeling::change(), MindWorld::change(), CreatedThought::change(), CreatedThought::CreatedThought(), Feeling::Feeling(), MindWorld::MindWorld(), Thought::ReDo(), Thought::Thought(), Thought::UnDo(), and View::View().
ToWrite()
void Explainable::ToWrite (void) virtual
decorates the method Thinkable::ToWrite(), the decorated Object also prints his member attribute _change_count
Parameters
none.
Returns
none.
Implements Thinkable.
References get_change_count(), Decorator::get_mwc(), and get_type().
Member Data Documentation
_change_count
int MindWorldComponent::_change_count private inherited
Referenced by MindWorldComponent::get_change_count(), and MindWorldComponent::set_change_count().
_mwc
MindWorldComponent* Decorator::_mwc private inherited
0..*
Referenced by Decorator::change(), Decorator::Decorator(), and Decorator::get_mwc().
The documentation for this class was generated from the following files:
implementations.h
implementations.cpp