MindWorld: GodAdapter Class Reference
GodAdapter Class Reference
Member of pattern Composite as Client. Member of pattern Adapter as Adapter and Target. Member of pattern Adapter as Client. Redefines and adds to the interface functionality inherited from the class God.
#include <godAdapter.h>
Public Member Functions
GodAdapter (QObject *parent, char *godname=nullptr)
Constructor of class GodAdapter.
virtual ~GodAdapter ()
Deconstructor of class GodAdapter.
virtual void createBigBang ()
Creates predefined universe.
virtual char * getName ()
Returns name of the god.
virtual void SimulateTimeStep ()
Implements inherited god function for compatibility.
virtual unsigned long GetTimeOfUniverse ()
Returns universe time.
virtual LowDev_LFEntity * createLowDevLFE (QObject *parent)
Returns "artificial" low developed life form with random name.
virtual MidDev_LFEntity * createMidDevLFE (QObject *parent)
Returns "artificial" mid developed life form with random name.
virtual HighDev_LFEntity * createHighDevLFE (QObject *parent)
Returns "artificial" high developed life form with random name.
virtual void challengeLFEs ()
Challenges random life forms with a random task (gets called in a random amount of time)
bool isInitialised ()
Returns true if the big bang already happened.
PlanetEntity * getPlanetToObserve ()
Returns predefined planet that should be observed.
void setMinNumberOfLFs (unsigned int min)
Sets min as minimum number of life forms.
void setMaxNumberOfLFs (unsigned int max)
Sets max as maximum number of life forms.
Static Public Attributes
static char * godName = name
Protected Attributes
DestinyAdapter * ourDestinyAdapter
UniverseEntity * ourUniverseEntity
PlanetEntity * planetToObserve
bool initialised
Static Protected Attributes
static unsigned int maxNumberOfLFEs = 50
static unsigned int minNumberOfLFEs = 10
Private Member Functions
virtual LowDev_LF * createLowDevLF ()
Creates a instance of a LowDev lifeform.
virtual MidDev_LF * createMidDevLF ()
Creates a instance of a MidDev lifeform.
virtual HighDev_LF * createHighDevLF ()
Creates a instance of a HighDev lifeform.
Private Attributes
Destiny * ourDestiny
Universe * ourUniverse
LowDev_LF LF1
MidDev_LF LF2
MidDev_LF LF3
Static Private Attributes
static char * name = "Thor"
Detailed Description
Member of pattern Composite as Client. Member of pattern Adapter as Adapter and Target. Member of pattern Adapter as Client. Redefines and adds to the interface functionality inherited from the class God.
It gives the functionality to create a predefined universe,
challenge a random life form with a random task from a given set of tasks,
create "artificial" life forms and limit the amount of life forms that could develop.
Constructor & Destructor Documentation
GodAdapter()
GodAdapter::GodAdapter (QObject * parent, char * godname = nullptr)
Constructor of class GodAdapter.
Parameters
parent QT parent pointer.
godName name of the god.
Returns
none.
References godName, initialised, UniverseEntity::Instance(), DestinyAdapter::Instance(), ourDestinyAdapter, ourUniverseEntity, and planetToObserve.
~GodAdapter()
GodAdapter::~GodAdapter () virtual
Deconstructor of class GodAdapter.
References UniverseEntity::destroy(), and ourUniverseEntity.
Member Function Documentation
challengeLFEs()
void GodAdapter::challengeLFEs () virtual
Challenges random life forms with a random task (gets called in a random amount of time)
Parameters
none.
Returns
none.
References DestinyAdapter::chooseRandomLFE(), DestinyAdapter::createProblemForLFE(), DestinyAdapter::devolveLFE(), dist(), DestinyAdapter::evolveLFE(), LifeFormEntity::getName(), DestinyAdapter::getNumberOfAliveLFEs(), DestinyAdapter::getNumberOfDeadLFEs(), DestinyAdapter::getNumberOfUnbornLFEs(), UniverseEntity::getTimeinTicks(), initialised, DestinyAdapter::killLFE(), DestinyAdapter::mateTwoLFE(), maxNumberOfLFEs, minNumberOfLFEs, mt(), ourDestinyAdapter, ourUniverseEntity, and DestinyAdapter::rendevouzTwoLFEs().
Referenced by SimWidgetDatamodel::challengeLifeForms(), and SimulateTimeStep().
createBigBang()
void GodAdapter::createBigBang (void) virtual
Creates predefined universe.
Parameters
none.
Returns
none.
Reimplemented from God.
References SolarSystemEntity::add(), UniverseEntity::add(), PlanetEntity::addInhabitant(), PlanetEntity::addSatellite(), createHighDevLFE(), createLowDevLFE(), createMidDevLFE(), initialised, ourUniverseEntity, planetToObserve, PlanetEntity::setOwnRotVelocity(), PlanetEntity::setPlanetRadius(), PlanetEntity::setTextureFileName(), and PlanetEntity::setVelocityInOrbit().
Referenced by SimWidgetDatamodel::buildViewChain().
createHighDevLF()
HighDev_LF * God::createHighDevLF (void) virtual inherited
Creates a instance of a HighDev lifeform.
Parameters
none.
Returns
Instance of the new created lifeform.
References God::getName().
Referenced by God::createBigBang().
createHighDevLFE()
HighDev_LFEntity * GodAdapter::createHighDevLFE (QObject * parent) virtual
Returns "artificial" high developed life form with random name.
Parameters
parent QT parent pointer.
Returns
new HighDev_LFEntity.
References DestinyAdapter::generateLFEName(), getName(), God::name, and ourDestinyAdapter.
Referenced by createBigBang().
createLowDevLF()
LowDev_LF * God::createLowDevLF (void) virtual inherited
Creates a instance of a LowDev lifeform.
Parameters
none.
Returns
Instance of the new created lifeform.
References God::getName().
Referenced by God::createBigBang().
createLowDevLFE()
LowDev_LFEntity * GodAdapter::createLowDevLFE (QObject * parent) virtual
Returns "artificial" low developed life form with random name.
Parameters
parent QT parent pointer.
Returns
new LowDev_LFEntity.
References DestinyAdapter::generateLFEName(), getName(), God::name, and ourDestinyAdapter.
Referenced by createBigBang().
createMidDevLF()
MidDev_LF * God::createMidDevLF (void) virtual inherited
Creates a instance of a MidDev lifeform.
Parameters
none
Returns
Instance of the new created lifeform
References God::getName().
Referenced by God::createBigBang().
createMidDevLFE()
MidDev_LFEntity * GodAdapter::createMidDevLFE (QObject * parent) virtual
Returns "artificial" mid developed life form with random name.
Parameters
parent QT parent pointer.
Returns
new MidDev_LFEntity.
References DestinyAdapter::generateLFEName(), getName(), God::name, and ourDestinyAdapter.
Referenced by createBigBang().
getName()
char * GodAdapter::getName (void) virtual
Returns name of the god.
Parameters
none.
Returns
name of the god.
Reimplemented from God.
References godName.
Referenced by createHighDevLFE(), createLowDevLFE(), and createMidDevLFE().
getPlanetToObserve()
PlanetEntity * GodAdapter::getPlanetToObserve ()
Returns predefined planet that should be observed.
Parameters
none.
Returns
planet to observe.
References planetToObserve.
Referenced by SimWidgetDatamodel::calcNextStep().
GetTimeOfUniverse()
unsigned long GodAdapter::GetTimeOfUniverse (void) virtual
Returns universe time.
Parameters
none.
Returns
universe time.
Reimplemented from God.
References UniverseEntity::getTime(), and ourUniverseEntity.
isInitialised()
bool GodAdapter::isInitialised ()
Returns true if the big bang already happened.
Parameters
none.
Returns
true if initialised.
References initialised.
setMaxNumberOfLFs()
void GodAdapter::setMaxNumberOfLFs (unsigned int max)
Sets max as maximum number of life forms.
Parameters
maximum.
Returns
none.
References maxNumberOfLFEs, and minNumberOfLFEs.
setMinNumberOfLFs()
void GodAdapter::setMinNumberOfLFs (unsigned int min)
Sets min as minimum number of life forms.
Parameters
minimum.
Returns
none.
References minNumberOfLFEs.
SimulateTimeStep()
void GodAdapter::SimulateTimeStep (void) virtual
Implements inherited god function for compatibility.
Parameters
none.
Returns
none.
Reimplemented from God.
References challengeLFEs().
Member Data Documentation
godName
char * GodAdapter::godName = name static
Referenced by getName(), and GodAdapter().
initialised
bool GodAdapter::initialised protected
Referenced by challengeLFEs(), createBigBang(), GodAdapter(), and isInitialised().
LF1
LowDev_LF God::LF1 protected inherited
Referenced by God::createBigBang(), and God::SimulateTimeStep().
LF2
MidDev_LF God::LF2 protected inherited
Referenced by God::createBigBang(), and God::SimulateTimeStep().
LF3
MidDev_LF God::LF3 protected inherited
Referenced by God::createBigBang(), and God::SimulateTimeStep().
maxNumberOfLFEs
unsigned int GodAdapter::maxNumberOfLFEs = 50 static protected
Referenced by challengeLFEs(), and setMaxNumberOfLFs().
minNumberOfLFEs
unsigned int GodAdapter::minNumberOfLFEs = 10 static protected
Referenced by challengeLFEs(), setMaxNumberOfLFs(), and setMinNumberOfLFs().
name
char * God::name = "Thor" static inherited
< Predefined name of god.
Referenced by createHighDevLFE(), createLowDevLFE(), createMidDevLFE(), and God::getName().
ourDestiny
Destiny* God::ourDestiny protected inherited
Referenced by God::createBigBang(), and God::SimulateTimeStep().
ourDestinyAdapter
DestinyAdapter* GodAdapter::ourDestinyAdapter protected
Referenced by challengeLFEs(), createHighDevLFE(), createLowDevLFE(), createMidDevLFE(), and GodAdapter().
ourUniverse
Universe* God::ourUniverse protected inherited
Referenced by God::createBigBang(), God::GetTimeOfUniverse(), and God::SimulateTimeStep().
ourUniverseEntity
UniverseEntity* GodAdapter::ourUniverseEntity protected
Referenced by challengeLFEs(), createBigBang(), GetTimeOfUniverse(), GodAdapter(), and ~GodAdapter().
planetToObserve
PlanetEntity* GodAdapter::planetToObserve protected
Referenced by createBigBang(), getPlanetToObserve(), and GodAdapter().
The documentation for this class was generated from the following files:
godAdapter.h
godAdapter.cpp