MindWorld: OwnMW Class Reference
OwnMW Class Reference
Member of pattern Composite as Composite. Is the one MindWorld, each Human has one.
Member of pattern Singleton.
Member of pattern Decorator as ConcreteComponent. Is the Container of Thinkable objects on first level.
#include <implementations.h>
Public Member Functions
void ToWrite ()
Shows all MindWorlds.
char * get_type ()
Returns the type of OwnMW.
void initialize ()
Initializion of the OwnMW.
~OwnMW ()
Destructor of OwnMW.
void change (char *text)
Changes the quality of the mindworld.
void add (MindWorldComponent *mwc)
Adds a MindWorldComponent to the MindWorld.
void write_target (std::string type, int min_count)
bool can_write (std::string type, int min_count)
like "HasHelp()" in "Design Patterns" - Chain of Responsibility
void create_thought (ThoughtBuilder *builder)
Creates a thought.
char * get_quality ()
std::vector< MindWorldComponent * > & get_mwc ()
virtual int get_change_count ()
void set_change_count (int new_count)
Static Public Member Functions
static OwnMW * get_Instance (MindWorldComponent *mwc, char *quality)
Creates and returns a single instance of OwnMW.
Protected Member Functions
OwnMW (MindWorldComponent *mwc, char *quality)
Constructor of OwnMW.
Private Attributes
std::vector< MindWorldComponent * > _mwc
char * _quality
MindWorld * _parent_mw
int _change_count
Static Private Attributes
static OwnMW * _ownmw = nullptr
Detailed Description
Member of pattern Composite as Composite. Is the one MindWorld, each Human has one.
Member of pattern Singleton.
Member of pattern Decorator as ConcreteComponent. Is the Container of Thinkable objects on first level.
Constructor & Destructor Documentation
~OwnMW()
OwnMW::~OwnMW ()
Destructor of OwnMW.
OwnMW()
OwnMW::OwnMW (MindWorldComponent * mwc, char * quality) protected
Constructor of OwnMW.
Parameters
a pointer to a MindWorld object.
a string.
References initialize().
Referenced by get_Instance().
Member Function Documentation
add()
void MindWorld::add (MindWorldComponent * mwc) inherited
Adds a MindWorldComponent to the MindWorld.
Parameters
a pointer to a MindWorldComponent object.
Returns
none.
References MindWorld::_mwc.
Referenced by MindWorld::create_thought(), and initialize().
can_write()
bool MindWorld::can_write (std::string type, int min_count) inherited
like "HasHelp()" in "Design Patterns" - Chain of Responsibility
Parameters
a string.
minimum count (a integer).
Returns
true, if the write_target request can be handled from an object in this "MindWorld".
References MindWorld::_mwc.
Referenced by MindWorld::write_target().
change()
void MindWorld::change (char * text) virtual inherited
Changes the quality of the mindworld.
Parameters
a string.
Returns
none.
Implements MindWorldComponent.
References MindWorld::_quality, MindWorldComponent::get_change_count(), and MindWorldComponent::set_change_count().
create_thought()
void MindWorld::create_thought (ThoughtBuilder * builder) inherited
Creates a thought.
Parameters
a ThoughtBuilder.
Returns
none.
References MindWorld::add(), and ThoughtBuilder::create_thought().
Referenced by initialize().
get_change_count()
virtual int MindWorldComponent::get_change_count () inline virtual inherited
Implemented in Explainable.
References MindWorldComponent::_change_count.
Referenced by View::change(), Thought::change(), Feeling::change(), MindWorld::change(), CreatedThought::change(), Thought::ReDo(), and Thought::UnDo().
get_Instance()
OwnMW * OwnMW::get_Instance (MindWorldComponent * mwc, char * quality) static
Creates and returns a single instance of OwnMW.
Parameters
a pointer to a MindWorld object.
a string.
Returns
the single instance of OwnMW.
References _ownmw, and OwnMW().
Referenced by Human::Human().
get_mwc()
std::vector<MindWorldComponent*>& MindWorld::get_mwc () inline inherited
References MindWorld::_mwc.
Referenced by ToWrite().
get_quality()
char* MindWorld::get_quality () inline inherited
References MindWorld::_quality.
get_type()
char * OwnMW::get_type (void) virtual
Returns the type of OwnMW.
Parameters
none.
Returns
text "OwnMW".
Reimplemented from MindWorld.
initialize()
void OwnMW::initialize (void)
Initializion of the OwnMW.
Parameters
none.
Returns
none.
References MindWorld::add(), View::change(), Thought::change(), MindWorld::create_thought(), MindWorld::MindWorld(), Thought::ReDo(), Thought::ToWrite(), and Thought::UnDo().
Referenced by OwnMW().
set_change_count()
void MindWorldComponent::set_change_count (int new_count) inline inherited
References MindWorldComponent::_change_count.
Referenced by View::change(), Thought::change(), Feeling::change(), MindWorld::change(), CreatedThought::change(), CreatedThought::CreatedThought(), Feeling::Feeling(), MindWorld::MindWorld(), Thought::ReDo(), Thought::Thought(), Thought::UnDo(), and View::View().
ToWrite()
void OwnMW::ToWrite (void) virtual
Shows all MindWorlds.
Parameters
none.
Returns
none.
Reimplemented from MindWorld.
References MindWorld::get_mwc().
Referenced by Human::Human().
write_target()
void MindWorld::write_target (std::string type, int min_count) inherited
like "HandleHelp()" in "Design Patterns" - Chain of Responsibility searches for an "Thinkable"-Object with the same type defined in parameter "type" and with _change_count >= parameter min_count, calls write_target() of its successor, if not found
Parameters
a string.
minimum count (a integer).
Returns
none.
References MindWorld::_parent_mw, MindWorld::can_write(), and MindWorld::write_target().
Referenced by MindWorld::write_target().
Member Data Documentation
_change_count
int MindWorldComponent::_change_count private inherited
Referenced by MindWorldComponent::get_change_count(), and MindWorldComponent::set_change_count().
_mwc
std::vector<MindWorldComponent*> MindWorld::_mwc private inherited
0..*
Referenced by MindWorld::add(), MindWorld::can_write(), MindWorld::get_mwc(), MindWorld::MindWorld(), MindWorld::ToWrite(), and MindWorld::~MindWorld().
_ownmw
OwnMW * OwnMW::_ownmw = nullptr static private
0..* Is set once, once get_Instance() is called. Only one OwnMW object are allowed for each MindWorldComponent.
Referenced by get_Instance().
_parent_mw
MindWorld* MindWorld::_parent_mw private inherited
is successor, needed for the Chain of Responsibility Pattern. 0..*
Referenced by MindWorld::MindWorld(), and MindWorld::write_target().
_quality
char* MindWorld::_quality private inherited
Referenced by MindWorld::change(), MindWorld::get_quality(), MindWorld::MindWorld(), and MindWorld::ToWrite().
The documentation for this class was generated from the following files:
implementations.h
implementations.cpp