MindWorld: Woman Class Reference
Woman Class Reference
Member of pattern Prototype as ConcretePrototype. Can be cloned to create new Woman Objects with the same Properties.
#include <human.h>
Public Member Functions
Woman ()
Constructor of class Woman.
Human * clone ()
Clones a human and builds a Woman.
Human * createHuman (Man *man)
Creates a new Woman or Man by using a Man (having sex). The product is chosen randomly. Its the have sex and getting pregnant stuff.
string getEyeColor ()
Returns the eye color of the human.
void setEyeColor (string str)
Sets the eye color of the human.
Private Attributes
OwnMW * mMindWorld
string mEyeColor
Static Private Attributes
static int mPossibleEyeColorsLength = 4
static string mPossibleEyeColors [] = {"green", "blue", "brown", "grey"}
Detailed Description
Member of pattern Prototype as ConcretePrototype. Can be cloned to create new Woman Objects with the same Properties.
Constructor & Destructor Documentation
Woman()
Woman::Woman ()
Constructor of class Woman.
Referenced by clone(), and createHuman().
Member Function Documentation
clone()
Human * Woman::clone (void) virtual
Clones a human and builds a Woman.
Parameters
none.
Returns
instance of cloned Woman.
Implements Human.
References Human::getEyeColor(), Human::setEyeColor(), and Woman().
createHuman()
Human * Woman::createHuman (Man * man)
Creates a new Woman or Man by using a Man (having sex). The product is chosen randomly. Its the have sex and getting pregnant stuff.
Parameters
man is a pointer to an instance of the man class.
Returns
an instance of a Human.
References Woman().
Referenced by OldestPartnerFinderStrategy::searchPartnersAndCreateHuman(), and RandomPartnerFinderStrategy::searchPartnersAndCreateHuman().
getEyeColor()
string Human::getEyeColor (void) inherited
Returns the eye color of the human.
Parameters
none.
Returns
the eye color (string).
References Human::mEyeColor.
Referenced by Man::clone(), clone(), God::createBigBang(), and HumanLifeHerold::update().
setEyeColor()
void Human::setEyeColor (string str) inherited
Sets the eye color of the human.
Parameters
the eye color (string).
Returns
none.
References Human::mEyeColor.
Referenced by Man::clone(), and clone().
Member Data Documentation
mEyeColor
string Human::mEyeColor private inherited
Referenced by Human::getEyeColor(), Human::Human(), and Human::setEyeColor().
mMindWorld
OwnMW* Human::mMindWorld private inherited
Referenced by Human::Human().
mPossibleEyeColors
string Human::mPossibleEyeColors = {"green", "blue", "brown", "grey"} static private inherited
Referenced by Human::Human().
mPossibleEyeColorsLength
int Human::mPossibleEyeColorsLength = 4 static private inherited
< Number of eye colours. Array of names of eye colours.
Referenced by Human::Human().
The documentation for this class was generated from the following files:
human.h
human.cpp