MindWorld: Death Class Reference
Death Class Reference
Member of pattern Singleton. Used to kill the oldest Human.
.
#include <human.h>
Public Member Functions
void killOldest ()
Deletes the oldest Human and the storing
HumanLifeChainElement from HumanLifeChain.
Static Public Member Functions
static Death * Instance ()
Returns the single Instance of Death.
Protected Member Functions
Death ()
Constructor of Death. Use Instance() to get instance of Death.
Static Private Attributes
static Death * mInstance = nullptr
Stores the single instance.
Detailed Description
Member of pattern Singleton. Used to kill the oldest Human.
.
   Deletes the oldest Human and its HumanLifeChainElement from HumanLifeChain.
       Can exist only one time. This is realised using the Singleton Pattern.
   One Death should be enough. Imagine there were more...
Constructor & Destructor Documentation
Death()
Death::Death () protected
Constructor of Death. Use Instance() to get instance of Death.
Referenced by Instance().
Member Function Documentation
Instance()
Death * Death::Instance (void) static
Returns the single Instance of Death.
Parameters
none.
Returns
instance of Death.
References Death(), and mInstance.
Referenced by HumanHandler::killOldest().
killOldest()
void Death::killOldest (void)
Deletes the oldest Human and the storing
HumanLifeChainElement from HumanLifeChain.
Parameters
none.
Returns
none.
References HumanLifeChain::Instance(), and HumanLifeChain::removeOldest().
Referenced by HumanHandler::killOldest().
Member Data Documentation
mInstance
Death * Death::mInstance = nullptr static private
Stores the single instance.
Is set once, once Death::Instance is called. This controls the restriction to number of Death objects.
Referenced by Instance().
The documentation for this class was generated from the following files:
human.h
human.cpp