MindWorld: LFMateJob Class Reference
LFMateJob Class Reference
Member of pattern Command as ConcreteCommand. Defines a job that lets the working life form mate with another life form.
#include <lfJobs.h>
Public Member Functions
LFMateJob (LifeFormEntity *workLF, LifeFormEntity *partnerLF, unsigned int prio=1)
Constructor of class LFMateJob.
LFMateJob (LFJob &copy)
Copy constructor of class LFMateJob.
LFMateJob (LFMateJob &copy)
Copy constructor of class LFMateJob.
~LFMateJob ()
Deconstructor of class LFMateJob.
void changeWorkingLF (LifeFormEntity *workLF)
Sets working life form.
LFMateJob & operator= (LFMateJob &copy)
Overload of the operator =.
bool workOnJob ()
Works on the job.
void changeParticipants (QVector< LifeFormEntity * > participants)
Sets life forms that are involved with the job.
QVector< LifeFormEntity * > getParticipants ()
Returns life forms that are involved with the job.
LifeFormEntity * getWorkingLF ()
Returns working life form.
unsigned int getPrio ()
Returns job priority.
void setPrio (unsigned int prio)
Sets the job priotity.
bool operator== (LFJob &j)
Overload of the operator ==.
bool operator!= (LFJob &j)
Overload of the operator !=.
bool operator< (LFJob &j)
Overload of the operator <.
bool operator<= (LFJob &j)
Overload of the operator <=.
bool operator> (LFJob &j)
Overload of the operator >
bool operator>= (LFJob &j)
Overload of the operator >=.
Static Public Member Functions
static unsigned long long getMateJobCount ()
Returns number of mate jobs.
static unsigned long long getJobCount ()
Returns number of jobs.
Protected Attributes
unsigned int jobPriority
LifeFormEntity * workingLF
Static Protected Attributes
static unsigned long long jobCounter = 0
Private Member Functions
LifeFormEntity * createChild ()
Returns new life form instance created from attributes of parents.
Private Attributes
LifeFormEntity * partner
LFMeetJob * jMeet
DestinyAdapter * ourDestinyAdapter
Static Private Attributes
static unsigned long long mateJobCounter = 0
Detailed Description
Member of pattern Command as ConcreteCommand. Defines a job that lets the working life form mate with another life form.
Constructor & Destructor Documentation
LFMateJob() [1/3]
LFMateJob::LFMateJob (LifeFormEntity * workLF, LifeFormEntity * partnerLF, unsigned int prio = 1)
Constructor of class LFMateJob.
Parameters
life form that is working on the job.
life form to mate with.
priority.
Returns
none.
References DestinyAdapter::Instance(), jMeet, mateJobCounter, ourDestinyAdapter, partner, and LFJob::workingLF.
LFMateJob() [2/3]
LFMateJob::LFMateJob (LFJob & copy)
Copy constructor of class LFMateJob.
Parameters
job to copy from.
Returns
none.
References jMeet, mateJobCounter, ourDestinyAdapter, and partner.
LFMateJob() [3/3]
LFMateJob::LFMateJob (LFMateJob & copy)
Copy constructor of class LFMateJob.
Parameters
job to copy from.
Returns
none.
References mateJobCounter.
~LFMateJob()
LFMateJob::~LFMateJob ()
Deconstructor of class LFMateJob.
References jMeet, and mateJobCounter.
Member Function Documentation
changeParticipants()
void LFMateJob::changeParticipants (QVector< LifeFormEntity * > participants) virtual
Sets life forms that are involved with the job.
Parameters
vector of life forms in the constructor parameter order of the job.
Returns
none.
Implements LFJob.
References LFMeetJob::changeParticipants(), jMeet, and partner.
changeWorkingLF()
void LFMateJob::changeWorkingLF (LifeFormEntity * workLF) virtual
Sets working life form.
Parameters
life form that will be working on the job.
Returns
none.
Reimplemented from LFJob.
References LFJob::changeWorkingLF(), LFMeetJob::changeWorkingLF(), and jMeet.
createChild()
LifeFormEntity * LFMateJob::createChild () private
Returns new life form instance created from attributes of parents.
Parameters
none.
Returns
child.
References dist(), DestinyAdapter::generateLFEName(), LifeFormEntity::getDevLvl(), LifeFormEntity::getGodName(), mt(), ourDestinyAdapter, partner, and LFJob::workingLF.
Referenced by workOnJob().
getJobCount()
unsigned long long LFJob::getJobCount () static inherited
Returns number of jobs.
Parameters
none.
Returns
jobCounter.
References LFJob::jobCounter.
getMateJobCount()
unsigned long long LFMateJob::getMateJobCount () static
Returns number of mate jobs.
Parameters
none.
Returns
mateJobCounter.
References mateJobCounter.
Referenced by DestinyAdapter::getNumberOfUnbornLFEs().
getParticipants()
QVector< LifeFormEntity * > LFMateJob::getParticipants () virtual
Returns life forms that are involved with the job.
Parameters
none.
Returns
vector of life forms in the constructor parameter order of the job.
Implements LFJob.
References partner.
Referenced by operator=().
getPrio()
unsigned int LFJob::getPrio () inherited
Returns job priority.
Parameters
none.
Returns
priority.
References LFJob::jobPriority.
Referenced by LFJob::operator=().
getWorkingLF()
LifeFormEntity * LFJob::getWorkingLF () inherited
Returns working life form.
Parameters
none.
Returns
workingLF.
References LFJob::workingLF.
Referenced by LFJobHandler::addJob(), LFJob::operator=(), and LFJobHandler::replaceLF().
operator!=()
bool LFJob::operator!= (LFJob & j) inherited
Overload of the operator !=.
Parameters
job to compare with.
Returns
result of priority comparison.
operator<()
bool LFJob::operator< (LFJob & j) inherited
Overload of the operator <.
Parameters
job to compare with.
Returns
result of priority comparison.
References LFJob::jobPriority.
operator<=()
bool LFJob::operator<= (LFJob & j) inherited
Overload of the operator <=.
Parameters
job to compare with.
Returns
result of priority comparison.
operator=()
LFMateJob & LFMateJob::operator= (LFMateJob & copy)
Overload of the operator =.
Parameters
job to copy from.
Returns
reference of this.
References getParticipants(), DestinyAdapter::Instance(), jMeet, ourDestinyAdapter, partner, and LFJob::workingLF.
operator==()
bool LFJob::operator== (LFJob & j) inherited
Overload of the operator ==.
Parameters
job to compare with.
Returns
result of priority comparison.
References LFJob::jobPriority.
operator>()
bool LFJob::operator> (LFJob & j) inherited
Overload of the operator >
Parameters
job to compare with.
Returns
result of priority comparison.
operator>=()
bool LFJob::operator>= (LFJob & j) inherited
Overload of the operator >=.
Parameters
job to compare with.
Returns
result of priority comparison.
setPrio()
void LFJob::setPrio (unsigned int prio) inherited
Sets the job priotity.
Parameters
priority.
Returns
none.
References LFJob::jobPriority.
workOnJob()
bool LFMateJob::workOnJob () virtual
Works on the job.
Parameters
none.
Returns
true if done.
Implements LFJob.
References LifeFormEntity::addKnownLFE(), createChild(), LifeFormEntity::getDevLvl(), LifeFormEntity::getGeneration(), LifeFormEntity::getHomePlanetEntity(), LifeFormEntity::getName(), LifeFormEntity::getRelativePos(), LifeFormEntity::inhabitPlanet(), jMeet, partner, LFJob::workingLF, and LFMeetJob::workOnJob().
Member Data Documentation
jMeet
LFMeetJob* LFMateJob::jMeet private
Referenced by changeParticipants(), changeWorkingLF(), LFMateJob(), operator=(), workOnJob(), and ~LFMateJob().
jobCounter
unsigned long long LFJob::jobCounter = 0 static protected inherited
Referenced by LFJob::getJobCount(), LFJob::LFJob(), and LFJob::~LFJob().
jobPriority
unsigned int LFJob::jobPriority protected inherited
Referenced by LFJob::getPrio(), LFJob::LFJob(), LFJob::operator<(), LFJob::operator=(), LFJob::operator==(), and LFJob::setPrio().
mateJobCounter
unsigned long long LFMateJob::mateJobCounter = 0 static private
Referenced by getMateJobCount(), LFMateJob(), and ~LFMateJob().
ourDestinyAdapter
DestinyAdapter* LFMateJob::ourDestinyAdapter private
Referenced by createChild(), LFMateJob(), and operator=().
partner
LifeFormEntity* LFMateJob::partner private
Referenced by changeParticipants(), createChild(), getParticipants(), LFMateJob(), operator=(), and workOnJob().
workingLF
LifeFormEntity* LFJob::workingLF protected inherited
Referenced by LFJob::changeWorkingLF(), createChild(), LFJob::getWorkingLF(), LFAnswerJob::LFAnswerJob(), LFAskJob::LFAskJob(), LFJob::LFJob(), LFMateJob(), LFMeetJob::LFMeetJob(), LFJob::operator=(), LFMeetJob::operator=(), LFAskJob::operator=(), LFAnswerJob::operator=(), operator=(), LFMoveJob::workOnJob(), LFMeetJob::workOnJob(), LFAskJob::workOnJob(), LFAnswerJob::workOnJob(), and workOnJob().
The documentation for this class was generated from the following files:
lfJobs.h
lfJobs.cpp