MindWorld: Coordinates Class Reference
Coordinates Class Reference
Member of pattern Adapter as Adaptee. An instance of this class represents a point in a 3 dimensional space. It is coded in sphere coordinates.
#include <coordinates.h>
Public Member Functions
Coordinates ()
Constructor.
Coordinates (double horDegree, double verDegree, double radius)
Sets the coordinates.
~Coordinates ()
Destructor.
double getHorDeg ()
Returns the horizontal angle.
double getVerDeg ()
Returns the vertical angle.
double getRad ()
Returns the radius.
void setHorDeg (double)
Sets the horizontal angle.
void setVerDeg (double)
Sets the vertical angle.
void setRad (double)
Sets the radius.
Protected Attributes
double horDeg
double verDeg
double rad
Detailed Description
Member of pattern Adapter as Adaptee. An instance of this class represents a point in a 3 dimensional space. It is coded in sphere coordinates.
Constructor & Destructor Documentation
Coordinates() [1/2]
Coordinates::Coordinates ()
Constructor.
Coordinates() [2/2]
Coordinates::Coordinates (double horDegree, double verDegree, double radius)
Sets the coordinates.
Parameters
horizontal degree.
vertical degree.
radius.
Returns
none.
References setHorDeg(), setRad(), and setVerDeg().
~Coordinates()
Coordinates::~Coordinates ()
Destructor.
Member Function Documentation
getHorDeg()
double Coordinates::getHorDeg (void)
Returns the horizontal angle.
Parameters
none.
Returns
horizontal angle.
References horDeg.
Referenced by CartesianCoordAdapter::getX(), CartesianCoordAdapter::getY(), LifeFormEntity::inhabitPlanet(), CartesianCoordAdapter::isEqualTo(), and LifeFormEntity::moveTowardsDest().
getRad()
double Coordinates::getRad (void)
Returns the radius.
Parameters
none.
Returns
radius.
References rad.
Referenced by CartesianCoordAdapter::getX(), CartesianCoordAdapter::getY(), CartesianCoordAdapter::getZ(), and CartesianCoordAdapter::isEqualTo().
getVerDeg()
double Coordinates::getVerDeg (void)
Returns the vertical angle.
Parameters
none.
Returns
vertical angle.
References verDeg.
Referenced by CartesianCoordAdapter::getX(), CartesianCoordAdapter::getY(), CartesianCoordAdapter::getZ(), LifeFormEntity::inhabitPlanet(), CartesianCoordAdapter::isEqualTo(), and LifeFormEntity::moveTowardsDest().
setHorDeg()
void Coordinates::setHorDeg (double _horDeg)
Sets the horizontal angle.
Parameters
horizontal degree.
Returns
none.
References horDeg.
Referenced by CartesianCoordAdapter::CartesianCoordAdapter(), Coordinates(), LifeFormEntity::inhabitPlanet(), and LifeFormEntity::moveTowardsDest().
setRad()
void Coordinates::setRad (double _rad)
Sets the radius.
Parameters
radius.
Returns
none.
References rad.
Referenced by CartesianCoordAdapter::CartesianCoordAdapter(), Coordinates(), and LifeFormEntity::resetPlanetRadius().
setVerDeg()
void Coordinates::setVerDeg (double _verDeg)
Sets the vertical angle.
Parameters
vertical degree.
Returns
none.
References verDeg.
Referenced by CartesianCoordAdapter::CartesianCoordAdapter(), Coordinates(), LifeFormEntity::inhabitPlanet(), and LifeFormEntity::moveTowardsDest().
Member Data Documentation
horDeg
double Coordinates::horDeg protected
Referenced by getHorDeg(), CartesianCoordAdapter::isEqualTo(), and setHorDeg().
rad
double Coordinates::rad protected
Referenced by getRad(), CartesianCoordAdapter::isEqualTo(), and setRad().
verDeg
double Coordinates::verDeg protected
Referenced by getVerDeg(), CartesianCoordAdapter::isEqualTo(), and setVerDeg().
The documentation for this class was generated from the following files:
coordinates.h
coordinates.cpp