MindWorld: LifeFormEntity Class Reference
LifeFormEntity Class Reference abstract
Member of pattern Composite as Leaf. Member of pattern Adapter as Adapter and Target. Redefines and adds to the interface functionality inherited from the class LifeForm. Implements interface functionality from the class Entity. This class defines a set of methods to create jobs for the life form specific job queue, start it's life and calculate the necessary three dimensional information to render it as a colored point.
#include <lifeformEntity.h>
Public Member Functions
LifeFormEntity (QObject *parent, const char *name, const char *god, LifeFormEntity *father, LifeFormEntity *mother)
Constructor of class LifeFormEntity.
LifeFormEntity (LifeFormEntity &copy)
Copy constructor of class LifeFormEntity.
virtual ~LifeFormEntity ()=0
Deconstructor of class DestinyAdapter.
LifeFormEntity & operator= (LifeFormEntity &copy)
Overload of the operator =.
virtual void setVisibility (bool v)
Sets the visibility for the life form.
virtual bool isVisible ()
Returns the visibility of the life form.
virtual void init (QOpenGLShaderProgram *p)
Initialises the life form (method runs in current OpenGL context)
virtual void draw ()
Draw life form (method runs in current OpenGL context)
void calcNextStep () final
virtual bool solveProblem (LifeFormEntity *lfThatReceives=nullptr)
Adds AnswerJob to the job queue of the life form.
virtual int getDevLvl ()
Returns development level of the life form.
void addKnownLFE (LifeFormEntity *lf)
Adds lf to the list of known life forms.
void forgetAboutLFE (LifeFormEntity *lf)
Removes lf from the list of known life forms.
void askKnownLFE (LifeFormEntity *lfThatReceives=nullptr)
Adds AskJob to the job queue of the life form if a more developed life form is known.
void meetWith (LifeFormEntity *lf)
Adds MeetJob to the job queue of the life form.
void mateWith (LifeFormEntity *lf)
Adds MateJob to the job queue of the life form.
void receiveAnswer (LifeFormEntity *lf, bool answer)
Outputs console message if the life form receives an answer from lf.
bool moveTowardsDest (CartesianCoordAdapter dest)
bool isOnSamePlanetAs (LifeFormEntity *lf)
Checks if lf is on the same planet as this.
bool isParentOf (LifeFormEntity *lf)
Checks if lf is parent of this.
bool knows (LifeFormEntity *lf)
Checks if lf is known by this.
QString getName ()
Returns name of life form.
QString getGodName ()
Returns name of god that the life form believies in.
unsigned long long getLifetimeInTicks ()
Returns lifetime in ticks of life form.
QVector3D getAbsolutPosition ()
Returns absolute position of the life form.
CartesianCoordAdapter getRelativePos ()
Returns position relative to the planet the life form lives on.
QVector3D getHomePlanetPos ()
Returns absolut position of the planet the life form lives on.
PlanetEntity * getHomePlanetEntity ()
Returns address of the life forms home planet.
LifeFormEntity * getFather ()
Returns adress of the life forms father.
LifeFormEntity * getMother ()
Returns address of the life forms mother.
QVector< LifeFormEntity * > getKnownLFEntities ()
Returns vector of all known life forms.
unsigned long long getGeneration ()
Returns generation of the life form.
QVector3D getLFEColor ()
Returns color of the life form.
void setLFEColor (QVector3D c)
Sets color of the life form.
void inhabitPlanet (PlanetEntity *p, CartesianCoordAdapter *dest=nullptr)
Sets home planet and let's the life form begin it's life.
void resetPlanetRadius ()
Protected Member Functions
CartesianCoordAdapter calcRandDestination ()
Calculates random destination on the home planet.
Protected Attributes
QString lfName
QVector3D lfeColor
QVector< QVector3D > lfVert
QOpenGLVertexArrayObject lfVAO
QOpenGLBuffer lfPositionVBO
QMatrix4x4 model
PlanetEntity * homePlanetEntity
QVector< LifeFormEntity * > knownLFEntities
CartesianCoordAdapter currentRelativePos
unsigned long long lifetimeInTicks
unsigned long long gen
LifeFormEntity * lfFather
LifeFormEntity * lfMother
LFJobHandler * ourJobHandler
DestinyAdapter * ourDestinyAdapter
bool visible
QOpenGLShaderProgram * program
Private Member Functions
CartesianCoordAdapter getPos ()
virtual bool solveProblem ()
Solves a given problem..
void addKownLF (LifeForm *)
A life form is added to the list of friends, the calling object has.
bool askKnownLF ()
One of the ways to solve a problem. The problem is "forwarded" to a higher life form.
Planet * getHomePlanet ()
Returns the home planet of the lifeform.
void startLife (Planet *)
The life begins on a planet.
Private Attributes
vector< LifeForm * > knownLF
Planet * homePlanet
const char * believerOf
Static Private Attributes
static int Dev_Level = 0
Detailed Description
Member of pattern Composite as Leaf. Member of pattern Adapter as Adapter and Target. Redefines and adds to the interface functionality inherited from the class LifeForm. Implements interface functionality from the class Entity. This class defines a set of methods to create jobs for the life form specific job queue, start it's life and calculate the necessary three dimensional information to render it as a colored point.
Constructor & Destructor Documentation
LifeFormEntity() [1/2]
LifeFormEntity::LifeFormEntity (QObject * parent, const char * name, const char * god, LifeFormEntity * father, LifeFormEntity * mother)
Constructor of class LifeFormEntity.
Parameters
parent QT parent pointer.
name of the life form.
name of the god that the life form believes in.
father of this life form.
mother of this life form.
Returns
none.
References LifeForm::believerOf, calcRandDestination(), LFJobHandler::createJobQueue(), currentRelativePos, gen, getGeneration(), LifeForm::homePlanet, homePlanetEntity, LFJobHandler::Instance(), DestinyAdapter::Instance(), lfeColor, lfFather, lfMother, lfName, lifetimeInTicks, model, ourDestinyAdapter, and ourJobHandler.
LifeFormEntity() [2/2]
LifeFormEntity::LifeFormEntity (LifeFormEntity & copy)
Copy constructor of class LifeFormEntity.
Parameters
life form to copy from.
Returns
none.
References LFJobHandler::createJobQueue(), LFJobHandler::Instance(), DestinyAdapter::Instance(), ourDestinyAdapter, and ourJobHandler.
~LifeFormEntity()
LifeFormEntity::~LifeFormEntity () pure virtual
Deconstructor of class DestinyAdapter.
References LFJobHandler::deleteJobQueue(), homePlanetEntity, lfName, lfPositionVBO, lfVAO, lifetimeInTicks, ourDestinyAdapter, ourJobHandler, PlanetEntity::removeInhabitant(), and DestinyAdapter::removeLFE().
Member Function Documentation
addKnownLFE()
void LifeFormEntity::addKnownLFE (LifeFormEntity * lf)
Adds lf to the list of known life forms.
Parameters
lf to be known.
Returns
none.
References LifeForm::addKownLF(), getName(), isOnSamePlanetAs(), knownLFEntities, knows(), and lfName.
Referenced by LFMeetJob::workOnJob(), and LFMateJob::workOnJob().
addKownLF()
void LifeForm::addKownLF (LifeForm * LF) inherited
A life form is added to the list of friends, the calling object has.
\param LF life form to add to the friend list.
Returns
none.
References LifeForm::knownLF.
Referenced by addKnownLFE(), operator=(), and Destiny::rendevouzTwoLF().
askKnownLF()
bool LifeForm::askKnownLF (void) inherited
One of the ways to solve a problem. The problem is "forwarded" to a higher life form.
Parameters
none.
Returns
TRUE, if problem solved this way - else FALSE.
References LifeForm::getDevLvl(), LifeForm::knownLF, and LifeForm::solveProblem().
Referenced by HighDev_LF::solveProblem(), MidDev_LF::solveProblem(), LowDev_LF::solveProblem(), LowDev_LFEntity::solveProblem(), HighDev_LFEntity::solveProblem(), and MidDev_LFEntity::solveProblem().
askKnownLFE()
void LifeFormEntity::askKnownLFE (LifeFormEntity * lfThatReceives = nullptr)
Adds AskJob to the job queue of the life form if a more developed life form is known.
Parameters
life form that receives answer (Chain Of Responsibilities).
Returns
none.
References LFJobHandler::addJob(), dist(), getDevLvl(), getHomePlanetEntity(), getName(), isOnSamePlanetAs(), knownLFEntities, lfName, mt(), and ourJobHandler.
Referenced by HighDev_LFEntity::solveProblem(), LowDev_LFEntity::solveProblem(), and MidDev_LFEntity::solveProblem().
calcNextStep()
void LifeFormEntity::calcNextStep () final virtual
Calculates the next step for the life form by working on the specific job queue Adds filler job if there is no job in the queue (Idle or Move)
Parameters
none.
Returns
none.
Implements Entity.
References LFJobHandler::addJob(), calcRandDestination(), dist(), homePlanetEntity, lfName, lifetimeInTicks, mt(), ourJobHandler, and LFJobHandler::workOnTopJob().
calcRandDestination()
CartesianCoordAdapter LifeFormEntity::calcRandDestination () protected
Calculates random destination on the home planet.
Parameters
none.
Returns
CartesianCoordAdapter.
References dist(), PlanetEntity::getPlanetRadius(), homePlanetEntity, mt(), and rd.
Referenced by calcNextStep(), and LifeFormEntity().
draw()
void LifeFormEntity::draw () virtual
Draw life form (method runs in current OpenGL context)
Parameters
none.
Returns
none.
Implements Entity.
Reimplemented in HighDev_LFEntity, LowDev_LFEntity, and MidDev_LFEntity.
References getAbsolutPosition(), homePlanetEntity, lfeColor, lfPositionVBO, lfVAO, lfVert, model, and Entity::program.
Referenced by LowDev_LFEntity::draw().
forgetAboutLFE()
void LifeFormEntity::forgetAboutLFE (LifeFormEntity * lf)
Removes lf from the list of known life forms.
Parameters
lf to be removed.
Returns
none.
References getName(), LifeForm::knownLF, knownLFEntities, knows(), lfFather, lfMother, and lfName.
getAbsolutPosition()
QVector3D LifeFormEntity::getAbsolutPosition ()
Returns absolute position of the life form.
Parameters
none.
Returns
three dimensional vector.
References currentRelativePos, PlanetEntity::getCurrentPosition(), PlanetEntity::getRotAngle(), CartesianCoordAdapter::getX(), CartesianCoordAdapter::getY(), CartesianCoordAdapter::getZ(), and homePlanetEntity.
Referenced by draw(), and init().
getDevLvl()
int LifeFormEntity::getDevLvl (void) virtual
Returns development level of the life form.
Parameters
none.
Returns
development level.
Reimplemented from LifeForm.
Reimplemented in HighDev_LFEntity, LowDev_LFEntity, and MidDev_LFEntity.
References LifeForm::Dev_Level.
Referenced by askKnownLFE(), LFMateJob::createChild(), DestinyAdapter::devolveLFE(), DestinyAdapter::evolveLFE(), and LFMateJob::workOnJob().
getFather()
LifeFormEntity * LifeFormEntity::getFather ()
Returns adress of the life forms father.
Parameters
none.
Returns
father.
References lfFather.
Referenced by isParentOf(), and operator=().
getGeneration()
unsigned long long LifeFormEntity::getGeneration ()
Returns generation of the life form.
Parameters
none.
Returns
generation.
References gen.
Referenced by LifeFormEntity(), operator=(), and LFMateJob::workOnJob().
getGodName()
QString LifeFormEntity::getGodName ()
Returns name of god that the life form believies in.
Parameters
none.
Returns
name of god.
References LifeForm::believerOf.
Referenced by LFMateJob::createChild(), and operator=().
getHomePlanet()
Planet * LifeForm::getHomePlanet (void) inherited
Returns the home planet of the lifeform.
Parameters
none.
Returns
The Planet-Object (Client).
References LifeForm::homePlanet.
Referenced by Planet::addLF(), Destiny::devolveLF(), and Destiny::evolveLF().
getHomePlanetEntity()
PlanetEntity * LifeFormEntity::getHomePlanetEntity ()
Returns address of the life forms home planet.
Parameters
none.
Returns
home planet entity.
References homePlanetEntity.
Referenced by PlanetEntity::addInhabitant(), askKnownLFE(), DestinyAdapter::devolveLFE(), DestinyAdapter::evolveLFE(), isOnSamePlanetAs(), and LFMateJob::workOnJob().
getHomePlanetPos()
QVector3D LifeFormEntity::getHomePlanetPos ()
Returns absolut position of the planet the life form lives on.
Parameters
none.
Returns
three dimensional vector.
References PlanetEntity::getCurrentPosition(), and homePlanetEntity.
getKnownLFEntities()
QVector< LifeFormEntity * > LifeFormEntity::getKnownLFEntities ()
Returns vector of all known life forms.
Parameters
none.
Returns
vector of known life forms.
References knownLFEntities.
Referenced by operator=().
getLFEColor()
QVector3D LifeFormEntity::getLFEColor ()
Returns color of the life form.
Parameters
none.
Returns
rgb vector.
References lfeColor.
Referenced by operator=().
getLifetimeInTicks()
unsigned long long LifeFormEntity::getLifetimeInTicks ()
Returns lifetime in ticks of life form.
Parameters
none.
Returns
tick count.
References lifetimeInTicks.
Referenced by operator=().
getMother()
LifeFormEntity * LifeFormEntity::getMother ()
Returns address of the life forms mother.
Parameters
none.
Returns
mother.
References lfMother.
Referenced by isParentOf(), and operator=().
getName()
QString LifeFormEntity::getName (void)
Returns name of life form.
Parameters
none.
Returns
name.
References lfName.
Referenced by addKnownLFE(), askKnownLFE(), GodAdapter::challengeLFEs(), DestinyAdapter::devolveLFE(), DestinyAdapter::evolveLFE(), forgetAboutLFE(), mateWith(), meetWith(), operator=(), receiveAnswer(), PlanetEntity::removeInhabitant(), and LFMateJob::workOnJob().
getPos()
CartesianCoordAdapter LifeForm::getPos () inherited
getRelativePos()
CartesianCoordAdapter LifeFormEntity::getRelativePos ()
Returns position relative to the planet the life form lives on.
Parameters
none.
Returns
three dimensional vector.
References currentRelativePos.
Referenced by DestinyAdapter::devolveLFE(), DestinyAdapter::evolveLFE(), LFMeetJob::LFMeetJob(), operator=(), LFMeetJob::operator=(), LFMeetJob::workOnJob(), and LFMateJob::workOnJob().
inhabitPlanet()
void LifeFormEntity::inhabitPlanet (PlanetEntity * p, CartesianCoordAdapter * dest = nullptr)
Sets home planet and let's the life form begin it's life.
Parameters
planet to settle on.
destination on the planet where to start life.
Returns
none.
References PlanetEntity::addInhabitant(), DestinyAdapter::addLFE(), currentRelativePos, Coordinates::getHorDeg(), Coordinates::getVerDeg(), LifeForm::homePlanet, homePlanetEntity, ourDestinyAdapter, resetPlanetRadius(), Coordinates::setHorDeg(), and Coordinates::setVerDeg().
Referenced by DestinyAdapter::devolveLFE(), DestinyAdapter::evolveLFE(), and LFMateJob::workOnJob().
init()
void LifeFormEntity::init (QOpenGLShaderProgram * p) virtual
Initialises the life form (method runs in current OpenGL context)
Parameters
p shader program to be set.
Returns
none.
Implements Entity.
Reimplemented in HighDev_LFEntity, LowDev_LFEntity, and MidDev_LFEntity.
References getAbsolutPosition(), lfPositionVBO, lfVAO, lfVert, Entity::program, and PROGRAM_VERTEX_ATTRIBUTE.
Referenced by LowDev_LFEntity::init().
isOnSamePlanetAs()
bool LifeFormEntity::isOnSamePlanetAs (LifeFormEntity * lf)
Checks if lf is on the same planet as this.
Parameters
life form to test for.
Returns
true if they are on the same planet.
References getHomePlanetEntity(), and homePlanetEntity.
Referenced by addKnownLFE(), askKnownLFE(), mateWith(), and meetWith().
isParentOf()
bool LifeFormEntity::isParentOf (LifeFormEntity * lf)
Checks if lf is parent of this.
Parameters
life form to test for.
Returns
true if lf is parent of this.
References getFather(), and getMother().
isVisible()
bool LifeFormEntity::isVisible () virtual
Returns the visibility of the life form.
Parameters
none.
Returns
current visibility.
Reimplemented from Entity.
Reimplemented in HighDev_LFEntity, LowDev_LFEntity, and MidDev_LFEntity.
References Entity::isVisible().
Referenced by HighDev_LFEntity::isVisible(), MidDev_LFEntity::isVisible(), and LowDev_LFEntity::isVisible().
knows()
bool LifeFormEntity::knows (LifeFormEntity * lf)
Checks if lf is known by this.
Parameters
lf to test for.
Returns
true if lf is known by this.
References knownLFEntities.
Referenced by addKnownLFE(), and forgetAboutLFE().
mateWith()
void LifeFormEntity::mateWith (LifeFormEntity * lf)
Adds MateJob to the job queue of the life form.
Parameters
life form to mate with.
Returns
none.
References LFJobHandler::addJob(), getName(), isOnSamePlanetAs(), lfFather, lfMother, lfName, and ourJobHandler.
Referenced by DestinyAdapter::mateTwoLFE().
meetWith()
void LifeFormEntity::meetWith (LifeFormEntity * lf)
Adds MeetJob to the job queue of the life form.
Parameters
life form to meet.
Returns
none.
References LFJobHandler::addJob(), getName(), isOnSamePlanetAs(), lfName, and ourJobHandler.
Referenced by DestinyAdapter::rendevouzTwoLFEs().
moveTowardsDest()
bool LifeFormEntity::moveTowardsDest (CartesianCoordAdapter dest)
Calculates the next movement step and checks if the life form has a certain distance to the destination
Parameters
destination.
Returns
true if dest is reached.
References currentRelativePos, Coordinates::getHorDeg(), Coordinates::getVerDeg(), lfName, Coordinates::setHorDeg(), and Coordinates::setVerDeg().
Referenced by LFMoveJob::workOnJob().
operator=()
LifeFormEntity & LifeFormEntity::operator= (LifeFormEntity & copy)
Overload of the operator =.
Parameters
life form to copy from.
Returns
reference of this.
References LifeForm::addKownLF(), LifeForm::believerOf, LFJobHandler::copyJobQueue(), currentRelativePos, gen, getFather(), getGeneration(), getGodName(), getKnownLFEntities(), getLFEColor(), getLifetimeInTicks(), getMother(), getName(), getRelativePos(), LifeForm::homePlanet, homePlanetEntity, knownLFEntities, lfeColor, lfFather, lfMother, lfName, lifetimeInTicks, model, and ourJobHandler.
receiveAnswer()
void LifeFormEntity::receiveAnswer (LifeFormEntity * lf, bool answer)
Outputs console message if the life form receives an answer from lf.
Parameters
life form to receive from.
answer.
Returns
none.
References getName(), and lfName.
Referenced by LFAnswerJob::workOnJob().
resetPlanetRadius()
void LifeFormEntity::resetPlanetRadius ()
Sets the relative position radius (polar) to the radius of the currently set home planet Used if radius of the planet could have changed
Parameters
none.
Returns
none.
References currentRelativePos, PlanetEntity::getPlanetRadius(), homePlanetEntity, and Coordinates::setRad().
Referenced by inhabitPlanet().
setLFEColor()
void LifeFormEntity::setLFEColor (QVector3D c)
Sets color of the life form.
Parameters
rgb vector.
Returns
none.
References lfeColor.
setVisibility()
void LifeFormEntity::setVisibility (bool v) virtual
Sets the visibility for the life form.
Parameters
v visibility to be set
Returns
none.
Reimplemented from Entity.
Reimplemented in HighDev_LFEntity, LowDev_LFEntity, and MidDev_LFEntity.
References Entity::setVisibility().
Referenced by HighDev_LFEntity::setVisibility(), MidDev_LFEntity::setVisibility(), and LowDev_LFEntity::setVisibility().
solveProblem() [1/2]
bool LifeForm::solveProblem (void) virtual inherited
Solves a given problem..
Parameters
none.
Returns
a status.
Reimplemented in LowDev_LF, HighDev_LF, and MidDev_LF.
Referenced by LifeForm::askKnownLF(), Destiny::createProblemForLifeForm(), and solveProblem().
solveProblem() [2/2]
bool LifeFormEntity::solveProblem (LifeFormEntity * lfThatReceives = nullptr) virtual
Adds AnswerJob to the job queue of the life form.
Parameters
life form that receives answer (Chain Of Responsibilities).
Returns
answer.
Reimplemented in HighDev_LFEntity, LowDev_LFEntity, and MidDev_LFEntity.
References LFJobHandler::addJob(), ourJobHandler, and LifeForm::solveProblem().
Referenced by DestinyAdapter::createProblemForLFE(), and LFAskJob::workOnJob().
startLife()
void LifeForm::startLife (Planet * planet) inherited
The life begins on a planet.
Parameters
the planet.
Returns
none.
References LifeForm::believerOf, and LifeForm::homePlanet.
Referenced by Planet::addLF(), God::createBigBang(), Destiny::devolveLF(), and Destiny::evolveLF().
Member Data Documentation
believerOf
const char* LifeForm::believerOf protected inherited
Referenced by getGodName(), HighDev_LF::HighDev_LF(), LifeFormEntity(), LowDev_LF::LowDev_LF(), MidDev_LF::MidDev_LF(), operator=(), and LifeForm::startLife().
currentRelativePos
CartesianCoordAdapter LifeFormEntity::currentRelativePos protected
Referenced by getAbsolutPosition(), getRelativePos(), inhabitPlanet(), LifeFormEntity(), moveTowardsDest(), operator=(), and resetPlanetRadius().
Dev_Level
int LifeForm::Dev_Level = 0 static protected inherited
< The level of the lifeform (0).
Referenced by LifeForm::getDevLvl(), and getDevLvl().
gen
unsigned long long LifeFormEntity::gen protected
Referenced by getGeneration(), LifeFormEntity(), and operator=().
homePlanet
Planet* LifeForm::homePlanet protected inherited
Referenced by LifeForm::getHomePlanet(), inhabitPlanet(), LifeFormEntity(), operator=(), and LifeForm::startLife().
homePlanetEntity
PlanetEntity* LifeFormEntity::homePlanetEntity protected
Referenced by calcNextStep(), calcRandDestination(), draw(), getAbsolutPosition(), getHomePlanetEntity(), getHomePlanetPos(), inhabitPlanet(), isOnSamePlanetAs(), LifeFormEntity(), operator=(), resetPlanetRadius(), and ~LifeFormEntity().
knownLF
vector<LifeForm*> LifeForm::knownLF protected inherited
Referenced by LifeForm::addKownLF(), LifeForm::askKnownLF(), and forgetAboutLFE().
knownLFEntities
QVector<LifeFormEntity*> LifeFormEntity::knownLFEntities protected
Referenced by addKnownLFE(), askKnownLFE(), forgetAboutLFE(), getKnownLFEntities(), knows(), and operator=().
lfeColor
QVector3D LifeFormEntity::lfeColor protected
Referenced by draw(), getLFEColor(), HighDev_LFEntity::HighDev_LFEntity(), LifeFormEntity(), LowDev_LFEntity::LowDev_LFEntity(), MidDev_LFEntity::MidDev_LFEntity(), operator=(), and setLFEColor().
lfFather
LifeFormEntity* LifeFormEntity::lfFather protected
Referenced by forgetAboutLFE(), getFather(), LifeFormEntity(), mateWith(), and operator=().
lfMother
LifeFormEntity* LifeFormEntity::lfMother protected
Referenced by forgetAboutLFE(), getMother(), LifeFormEntity(), mateWith(), and operator=().
lfName
QString LifeFormEntity::lfName protected
Referenced by addKnownLFE(), askKnownLFE(), calcNextStep(), forgetAboutLFE(), getName(), LifeFormEntity(), mateWith(), meetWith(), moveTowardsDest(), operator=(), receiveAnswer(), LowDev_LFEntity::solveProblem(), MidDev_LFEntity::solveProblem(), HighDev_LFEntity::solveProblem(), and ~LifeFormEntity().
lfPositionVBO
QOpenGLBuffer LifeFormEntity::lfPositionVBO protected
Referenced by draw(), init(), and ~LifeFormEntity().
lfVAO
QOpenGLVertexArrayObject LifeFormEntity::lfVAO protected
Referenced by draw(), init(), and ~LifeFormEntity().
lfVert
QVector<QVector3D> LifeFormEntity::lfVert protected
Referenced by draw(), and init().
lifetimeInTicks
unsigned long long LifeFormEntity::lifetimeInTicks protected
Referenced by calcNextStep(), getLifetimeInTicks(), LifeFormEntity(), operator=(), and ~LifeFormEntity().
model
QMatrix4x4 LifeFormEntity::model protected
Referenced by draw(), LifeFormEntity(), and operator=().
ourDestinyAdapter
DestinyAdapter* LifeFormEntity::ourDestinyAdapter protected
Referenced by inhabitPlanet(), LifeFormEntity(), and ~LifeFormEntity().
ourJobHandler
LFJobHandler* LifeFormEntity::ourJobHandler protected
Referenced by askKnownLFE(), calcNextStep(), LifeFormEntity(), mateWith(), meetWith(), operator=(), HighDev_LFEntity::solveProblem(), MidDev_LFEntity::solveProblem(), LowDev_LFEntity::solveProblem(), solveProblem(), and ~LifeFormEntity().
program
QOpenGLShaderProgram* Entity::program protected inherited
Referenced by draw(), SolarSystemEntity::draw(), ViewOfEntities::draw(), UniverseEntity::draw(), PlanetEntity::draw(), Entity::Entity(), SolarSystemEntity::init(), init(), ViewOfEntities::init(), UniverseEntity::init(), and PlanetEntity::init().
visible
bool Entity::visible protected inherited
Referenced by ViewOfEntities::draw(), Entity::Entity(), Entity::isVisible(), and Entity::setVisibility().
The documentation for this class was generated from the following files:
lifeformEntity.h
lifeformEntity.cpp