MindWorld: HumanLifeHerold Class Reference
HumanLifeHerold Class Reference
Member of pattern Observer as ConcreteObserver. Prints a newborn Human to the console.
#include <human.h>
Public Member Functions
void attachToSubject (HumanLifeChain *chain)
Attaches the obsrever to a subject.
HumanLifeHerold ()
Constructor of class HumanHerold.
void update ()
Protected Attributes
HumanLifeChain * mChain
The HumanLifeChain this is attached to.
Private Attributes
Human * mLastNewBorn
Stores the last newborn Human. Needed to determine if a new Human was born.
Detailed Description
Member of pattern Observer as ConcreteObserver. Prints a newborn Human to the console.
Constructor & Destructor Documentation
HumanLifeHerold()
HumanLifeHerold::HumanLifeHerold (void)
Constructor of class HumanHerold.
References mLastNewBorn.
Member Function Documentation
attachToSubject()
void HumanLifeHerold::attachToSubject (HumanLifeChain * chain)
Attaches the obsrever to a subject.
Parameters
a HumanLifeChain.
Returns
none.
References HumanHerold::attachToSubject(), HumanLifeChainElement::getHuman(), HumanLifeChain::lastElement(), and mLastNewBorn.
update()
void HumanLifeHerold::update (void) virtual
Should be called by the HumanLifeChain when it changes. If a new Human is put into the HumanLifeChain since the last update() it is considered newborn and print to the console..
Parameters
none.
Returns
none.
Implements HumanHerold.
References Human::getEyeColor(), HumanLifeChainElement::getHuman(), HumanLifeChain::Instance(), HumanLifeChain::lastElement(), HumanHerold::mChain, and mLastNewBorn.
Member Data Documentation
mChain
HumanLifeChain* HumanHerold::mChain protected inherited
The HumanLifeChain this is attached to.
Referenced by HumanHerold::attachToSubject(), update(), and HumanDeathHerold::update().
mLastNewBorn
Human* HumanLifeHerold::mLastNewBorn private
Stores the last newborn Human. Needed to determine if a new Human was born.
Referenced by attachToSubject(), HumanLifeHerold(), and update().
The documentation for this class was generated from the following files:
human.h
human.cpp