MindWorld: PlanetEntity Class Reference
PlanetEntity Class Reference
Member of pattern Adapter as Adapter and Target. Redefines and adds to the interface functionality inherited from the class Planet. Implements interface functionality from the class ViewOfEntities. This class defines a set of methods to render a planet with custom texture that is orbiting around a given center point, add/remove satellites and lifeforms and make the data accessible.
#include <planetEntity.h>
Public Member Functions
PlanetEntity (QObject *parent, const char *name, CartesianCoordAdapter const &coord)
Constructor of class PlanetEntity.
~PlanetEntity ()
Deconstructor of class PlanetEntity.
void setVisibility (bool v)
Sets the visibility for the planet.
bool isVisible ()
Returns the visibility of the planet.
void add (Entity *entity)
Adds entity to the planet.
void addSatellite (PlanetEntity *p)
Adds satellite to the planet.
void addInhabitant (LifeFormEntity *lf)
Adds inhabitant to the planet.
void remove (Entity *entity)
Removes entity from the planet.
void removeSatellite (PlanetEntity *p)
Removes satellite from the planet.
void removeInhabitant (LifeFormEntity *lf)
Removes inhabitant from the planet.
void clear ()
Removes all entities from the planet.
void clearSatellites ()
Removes all satellites from the planet.
void clearInhabitants ()
Removes all inhabitants from the planet.
void destroy ()
Destroy all entities held by the planet.
bool isEmpty ()
Checks if planet holds no entities.
bool hasNoSatellites ()
Checks if planet has no satellites.
bool hasNoInhabitants ()
Checks if planet has no inhabitants.
bool contains (Entity *entity)
Checks if planet contains entity.
bool containsSatellite (PlanetEntity *p)
Checks if planet has satellite p.
bool containsInhabitant (LifeFormEntity *lf)
Checks if planet has inhabitant lf.
int getSize ()
Returns amount of children.
int getSatelliteCount ()
Returns amount of satellites.
int getInhabitantCount ()
Returns amount of inhabitants.
Entity * getChild (int i)
Returns entity with index i.
PlanetEntity * getSatellite (int i)
Returns satellite with index i.
LifeFormEntity * getInhabitant (int i)
Returns inhabitant with index i.
void init (QOpenGLShaderProgram *p)
Initialises the planet (method runs in current OpenGL context)
void draw ()
Draw planet (method runs in current OpenGL context)
void calcNextStep ()
void setOrbitCenter (QVector3D c)
Sets new center for the orbit of the planet.
void setPlanetRadius (double r)
Sets new radius for the planet.
void setOwnRotVelocity (double v)
Sets rotation velocity for the planet.
void setVelocityInOrbit (double v)
Sets velocity in orbit for the planet.
void setOrbitColor (QVector3D c)
Sets orbit color.
void setPlanetColor (QVector3D c)
Sets planet color.
void setTextureFileName (QString filename)
Sets filename (for example Earth.jpg) for the planet texture.
QString getName ()
Returns name of the planet.
QVector3D getCurrentPosition ()
Returns absolut position of the planet.
QVector3D getOrbitCenter ()
Returns center of the orbit.
QVector2D getOrbitRadii ()
Returns orbit radii.
double getOwnRotVelocity ()
Returns rot velocity of the planet.
double getRotAngle ()
Returns rot angle of the planet.
double getVerlocitiyInOrbit ()
Returns velocity in orbit of the planet.
double getPlanetRadius ()
Returns planet radius.
CartesianCoordAdapter getInitialPlanetPos ()
Returns initial planet position.
Protected Attributes
QVector< Entity * > children
QVector< Entity * > uninitialised
bool visible
QOpenGLShaderProgram * program
Private Member Functions
void calcRotAngles ()
void calcSphere (int lats, int longs)
Calculate sphere and texture coordinates.
void calcEllipse (int num_segments)
Calculate the orbit coordinates.
bool addLF (LifeForm *)
Adds a lifeform to the planet.
Private Attributes
double orbitRadiusY
double orbitRadiusX
double sphereRadius
double currentPosXY [2]
double orbitCenterPos [3]
double ownRotVelocity
double currentRotAngle
double orbitVelocity
double rotAngleXY
double rotAngleYZ
QVector3D orbitColor
QVector3D planetColor
QMatrix4x4 model
QOpenGLTexture * texture
QString textureFileName
bool textureChanged
QVector< PlanetEntity * > satellites
QVector< LifeFormEntity * > inhabitants
QOpenGLVertexArrayObject sphereVAO
QOpenGLBuffer spherePositionVBO
QOpenGLBuffer sphereTexCoordVBO
QOpenGLBuffer sphereNormalVBO
QVector< QVector3D > sphereVert
QVector< QVector2D > sphereTexCoord
QOpenGLVertexArrayObject ellipseVAO
QOpenGLBuffer ellipsePositionVBO
QVector< QVector3D > ellipseVert
QString planetName
CartesianCoordAdapter coords
vector< LifeForm * > Inhabitants
Detailed Description
Member of pattern Adapter as Adapter and Target. Redefines and adds to the interface functionality inherited from the class Planet. Implements interface functionality from the class ViewOfEntities. This class defines a set of methods to render a planet with custom texture that is orbiting around a given center point, add/remove satellites and lifeforms and make the data accessible.
Constructor & Destructor Documentation
PlanetEntity()
PlanetEntity::PlanetEntity (QObject * parent, const char * name, CartesianCoordAdapter const & coord)
Constructor of class PlanetEntity.
Parameters
parent QT parent pointer.
name of the life form.
initial starting position of the planet.
Returns
none.
References calcRotAngles(), Planet::coords, currentPosXY, currentRotAngle, CartesianCoordAdapter::getX(), CartesianCoordAdapter::getY(), CartesianCoordAdapter::getZ(), model, orbitCenterPos, orbitColor, orbitRadiusX, orbitRadiusY, orbitVelocity, ownRotVelocity, planetColor, planetName, sphereRadius, texture, and textureChanged.
~PlanetEntity()
PlanetEntity::~PlanetEntity ()
Deconstructor of class PlanetEntity.
References ellipsePositionVBO, ellipseVAO, sphereNormalVBO, spherePositionVBO, sphereTexCoordVBO, sphereVAO, and texture.
Member Function Documentation
add()
void PlanetEntity::add (Entity * entity) virtual
Adds entity to the planet.
Parameters
entity.
Returns
none.
Reimplemented from ViewOfEntities.
References addInhabitant(), and addSatellite().
addInhabitant()
void PlanetEntity::addInhabitant (LifeFormEntity * lf)
Adds inhabitant to the planet.
Parameters
life form.
Returns
none.
References ViewOfEntities::add(), Planet::addLF(), containsInhabitant(), LifeFormEntity::getHomePlanetEntity(), inhabitants, and planetName.
Referenced by add(), GodAdapter::createBigBang(), and LifeFormEntity::inhabitPlanet().
addLF()
bool Planet::addLF (LifeForm * LF) inherited
Adds a lifeform to the planet.
Parameters
instance of a lifeform.
Returns
True, if it is the first lifeform, else False.
References LifeForm::getHomePlanet(), Planet::Inhabitants, and LifeForm::startLife().
Referenced by addInhabitant().
addSatellite()
void PlanetEntity::addSatellite (PlanetEntity * p)
Adds satellite to the planet.
Parameters
planet.
Returns
none.
References ViewOfEntities::add(), contains(), getCurrentPosition(), getName(), planetName, satellites, and setOrbitCenter().
Referenced by add(), and GodAdapter::createBigBang().
calcEllipse()
void PlanetEntity::calcEllipse (int num_segments) private
Calculate the orbit coordinates.
Parameters
amount of line segments the orbit contains of.
Returns
none.
References ellipsePositionVBO, ellipseVert, orbitRadiusX, and orbitRadiusY.
Referenced by init().
calcNextStep()
void PlanetEntity::calcNextStep () virtual
Calculates the next step for the planet on the orbit and sets the center of all satellites to the new position Also calculates the next rotation step
Parameters
none.
Returns
none.
Reimplemented from ViewOfEntities.
References ViewOfEntities::calcNextStep(), currentPosXY, currentRotAngle, getCurrentPosition(), orbitVelocity, ownRotVelocity, and satellites.
calcRotAngles()
void PlanetEntity::calcRotAngles () private
Calculate rotation angles to rotate the planet from the center of the world space to the correct position
Parameters
none.
Returns
none.
References Planet::coords, CartesianCoordAdapter::getX(), CartesianCoordAdapter::getY(), CartesianCoordAdapter::getZ(), rotAngleXY, and rotAngleYZ.
Referenced by PlanetEntity().
calcSphere()
void PlanetEntity::calcSphere (int lats, int longs) private
Calculate sphere and texture coordinates.
Parameters
amount of latitudes the sphere has.
amount of longitudes the sphere has.
Returns
none.
References sphereNormalVBO, spherePositionVBO, sphereRadius, sphereTexCoord, sphereTexCoordVBO, and sphereVert.
Referenced by init(), and setPlanetRadius().
clear()
void PlanetEntity::clear () virtual
Removes all entities from the planet.
Parameters
none.
Returns
none.
Reimplemented from ViewOfEntities.
References ViewOfEntities::clear(), clearInhabitants(), and clearSatellites().
clearInhabitants()
void PlanetEntity::clearInhabitants ()
Removes all inhabitants from the planet.
Parameters
none.
Returns
none.
References inhabitants, and removeInhabitant().
Referenced by clear().
clearSatellites()
void PlanetEntity::clearSatellites ()
Removes all satellites from the planet.
Parameters
none.
Returns
none.
References removeSatellite(), and satellites.
Referenced by clear().
contains()
bool PlanetEntity::contains (Entity * entity) virtual
Checks if planet contains entity.
Parameters
entity.
Returns
true if planet contains entity.
Reimplemented from ViewOfEntities.
References ViewOfEntities::contains().
Referenced by addSatellite(), removeInhabitant(), and removeSatellite().
containsInhabitant()
bool PlanetEntity::containsInhabitant (LifeFormEntity * lf)
Checks if planet has inhabitant lf.
Parameters
lf.
Returns
true if planet contains lf.
References inhabitants.
Referenced by addInhabitant().
containsSatellite()
bool PlanetEntity::containsSatellite (PlanetEntity * p)
Checks if planet has satellite p.
Parameters
planet.
Returns
true if planet contains p.
References satellites.
destroy()
void PlanetEntity::destroy () virtual
Destroy all entities held by the planet.
Parameters
none.
Returns
none.
Reimplemented from ViewOfEntities.
References ViewOfEntities::destroy().
draw()
void PlanetEntity::draw () virtual
Draw planet (method runs in current OpenGL context)
Parameters
none.
Returns
none.
Reimplemented from ViewOfEntities.
References currentPosXY, currentRotAngle, ViewOfEntities::draw(), ellipseVAO, model, orbitCenterPos, orbitColor, orbitRadiusX, orbitRadiusY, planetColor, Entity::program, rotAngleXY, rotAngleYZ, sphereVAO, texture, textureChanged, and textureFileName.
Referenced by SolarSystemEntity::draw().
getChild()
Entity * PlanetEntity::getChild (int i) virtual
Returns entity with index i.
Parameters
index.
Returns
entity with index i.
Reimplemented from ViewOfEntities.
References ViewOfEntities::children.
getCurrentPosition()
QVector3D PlanetEntity::getCurrentPosition ()
Returns absolut position of the planet.
Parameters
none.
Returns
three dimensional vector.
References currentPosXY, orbitCenterPos, orbitRadiusX, orbitRadiusY, rotAngleXY, and rotAngleYZ.
Referenced by addSatellite(), SimWidgetDatamodel::calcNextStep(), calcNextStep(), LifeFormEntity::getAbsolutPosition(), LifeFormEntity::getHomePlanetPos(), and setOrbitCenter().
getInhabitant()
LifeFormEntity * PlanetEntity::getInhabitant (int i)
Returns inhabitant with index i.
Parameters
index.
Returns
inhabitant with index i.
References inhabitants.
getInhabitantCount()
int PlanetEntity::getInhabitantCount ()
Returns amount of inhabitants.
Parameters
none.
Returns
amount of inhabitants.
References inhabitants.
getInitialPlanetPos()
CartesianCoordAdapter PlanetEntity::getInitialPlanetPos ()
Returns initial planet position.
Parameters
none.
Returns
CartesianCoordAdapter.
References Planet::coords.
getName()
QString PlanetEntity::getName (void)
Returns name of the planet.
Parameters
none.
Returns
name.
References planetName.
Referenced by addSatellite(), and removeSatellite().
getOrbitCenter()
QVector3D PlanetEntity::getOrbitCenter ()
Returns center of the orbit.
Parameters
none.
Returns
three dimensional vector.
References orbitCenterPos.
Referenced by SolarSystemEntity::add(), SolarSystemEntity::getSolarSystemCenter(), SolarSystemEntity::init(), SolarSystemEntity::setSolarSystemCenter(), and SolarSystemEntity::~SolarSystemEntity().
getOrbitRadii()
QVector2D PlanetEntity::getOrbitRadii ()
Returns orbit radii.
Parameters
none.
Returns
two dimensional vector.
References orbitRadiusX, and orbitRadiusY.
getOwnRotVelocity()
double PlanetEntity::getOwnRotVelocity ()
Returns rot velocity of the planet.
Parameters
none.
Returns
velocity.
References ownRotVelocity.
getPlanetRadius()
double PlanetEntity::getPlanetRadius ()
Returns planet radius.
Parameters
none.
Returns
radius.
References sphereRadius.
Referenced by LifeFormEntity::calcRandDestination(), and LifeFormEntity::resetPlanetRadius().
getRotAngle()
double PlanetEntity::getRotAngle ()
Returns rot angle of the planet.
Parameters
none.
Returns
angle.
References currentRotAngle.
Referenced by LifeFormEntity::getAbsolutPosition().
getSatellite()
PlanetEntity * PlanetEntity::getSatellite (int i)
Returns satellite with index i.
Parameters
index.
Returns
satellite with index i.
References satellites.
getSatelliteCount()
int PlanetEntity::getSatelliteCount ()
Returns amount of satellites.
Parameters
none.
Returns
amount of satellites.
References satellites.
getSize()
int PlanetEntity::getSize () virtual
Returns amount of children.
Parameters
none.
Returns
amount of children.
Reimplemented from ViewOfEntities.
References ViewOfEntities::getSize().
getVerlocitiyInOrbit()
double PlanetEntity::getVerlocitiyInOrbit ()
Returns velocity in orbit of the planet.
Parameters
none.
Returns
velocity.
References orbitVelocity.
hasNoInhabitants()
bool PlanetEntity::hasNoInhabitants ()
Checks if planet has no inhabitants.
Parameters
none.
Returns
true if planet has no inhabitants.
References inhabitants.
hasNoSatellites()
bool PlanetEntity::hasNoSatellites ()
Checks if planet has no satellites.
Parameters
none.
Returns
true if planet has no satellites.
References satellites.
init()
void PlanetEntity::init (QOpenGLShaderProgram * p) virtual
Initialises the planet (method runs in current OpenGL context)
Parameters
p shader program to be set.
Returns
none.
Reimplemented from ViewOfEntities.
References calcEllipse(), calcSphere(), ellipsePositionVBO, ellipseVAO, ViewOfEntities::init(), Entity::program, PROGRAM_NORMAL_ATTRIBUTE, PROGRAM_TEXCOORD_ATTRIBUTE, PROGRAM_VERTEX_ATTRIBUTE, sphereNormalVBO, spherePositionVBO, sphereTexCoordVBO, sphereVAO, texture, and textureFileName.
Referenced by SolarSystemEntity::init().
isEmpty()
bool PlanetEntity::isEmpty () virtual
Checks if planet holds no entities.
Parameters
none.
Returns
true if planet holds no entities.
Reimplemented from ViewOfEntities.
References ViewOfEntities::isEmpty().
isVisible()
bool PlanetEntity::isVisible () virtual
Returns the visibility of the planet.
Parameters
none.
Returns
current visibility.
Reimplemented from ViewOfEntities.
References ViewOfEntities::isVisible().
remove()
void PlanetEntity::remove (Entity * entity) virtual
Removes entity from the planet.
Parameters
entity.
Returns
none.
Reimplemented from ViewOfEntities.
References removeInhabitant(), and removeSatellite().
removeInhabitant()
void PlanetEntity::removeInhabitant (LifeFormEntity * lf)
Removes inhabitant from the planet.
Parameters
life form.
Returns
none.
References contains(), LifeFormEntity::getName(), inhabitants, planetName, and ViewOfEntities::remove().
Referenced by clearInhabitants(), remove(), and LifeFormEntity::~LifeFormEntity().
removeSatellite()
void PlanetEntity::removeSatellite (PlanetEntity * p)
Removes satellite from the planet.
Parameters
planet.
Returns
none.
References contains(), getName(), planetName, ViewOfEntities::remove(), and satellites.
Referenced by clearSatellites(), and remove().
setOrbitCenter()
void PlanetEntity::setOrbitCenter (QVector3D c)
Sets new center for the orbit of the planet.
Parameters
center.
Returns
none.
References getCurrentPosition(), orbitCenterPos, and satellites.
Referenced by SolarSystemEntity::add(), addSatellite(), SolarSystemEntity::setSolarSystemCenter(), and SolarSystemEntity::SolarSystemEntity().
setOrbitColor()
void PlanetEntity::setOrbitColor (QVector3D c)
Sets orbit color.
Parameters
rgb vector.
Returns
none.
References orbitColor.
setOwnRotVelocity()
void PlanetEntity::setOwnRotVelocity (double v)
Sets rotation velocity for the planet.
Parameters
velocity [-100, 100].
Returns
none.
References ownRotVelocity.
Referenced by GodAdapter::createBigBang(), and SolarSystemEntity::SolarSystemEntity().
setPlanetColor()
void PlanetEntity::setPlanetColor (QVector3D c)
Sets planet color.
Parameters
rgb vector.
Returns
none.
References planetColor.
Referenced by SolarSystemEntity::SolarSystemEntity().
setPlanetRadius()
void PlanetEntity::setPlanetRadius (double r)
Sets new radius for the planet.
Parameters
radius.
Returns
none.
References calcSphere(), inhabitants, sphereRadius, and sphereVAO.
Referenced by GodAdapter::createBigBang(), SolarSystemEntity::setSunRadius(), and SolarSystemEntity::SolarSystemEntity().
setTextureFileName()
void PlanetEntity::setTextureFileName (QString filename)
Sets filename (for example Earth.jpg) for the planet texture.
Parameters
filename.
Returns
none.
References textureChanged, and textureFileName.
Referenced by GodAdapter::createBigBang(), SolarSystemEntity::setSunTextureFileName(), and SolarSystemEntity::SolarSystemEntity().
setVelocityInOrbit()
void PlanetEntity::setVelocityInOrbit (double v)
Sets velocity in orbit for the planet.
Parameters
velocity [-100, 100].
Returns
none.
References orbitVelocity.
Referenced by GodAdapter::createBigBang().
setVisibility()
void PlanetEntity::setVisibility (bool v) virtual
Sets the visibility for the planet.
Parameters
v visibility to be set
Returns
none.
Reimplemented from ViewOfEntities.
References ViewOfEntities::setVisibility().
Member Data Documentation
children
QVector<Entity*> ViewOfEntities::children protected inherited
Referenced by ViewOfEntities::add(), ViewOfEntities::calcNextStep(), ViewOfEntities::clear(), ViewOfEntities::contains(), ViewOfEntities::destroy(), ViewOfEntities::draw(), SolarSystemEntity::getChild(), ViewOfEntities::getChild(), UniverseEntity::getChild(), getChild(), ViewOfEntities::getSize(), ViewOfEntities::init(), ViewOfEntities::isEmpty(), and ViewOfEntities::remove().
coords
CartesianCoordAdapter Planet::coords inherited
Referenced by calcRotAngles(), getInitialPlanetPos(), Planet::Planet(), and PlanetEntity().
currentPosXY
double PlanetEntity::currentPosXY[2] private
Referenced by calcNextStep(), draw(), getCurrentPosition(), and PlanetEntity().
currentRotAngle
double PlanetEntity::currentRotAngle private
Referenced by calcNextStep(), draw(), getRotAngle(), and PlanetEntity().
ellipsePositionVBO
QOpenGLBuffer PlanetEntity::ellipsePositionVBO private
Referenced by calcEllipse(), init(), and ~PlanetEntity().
ellipseVAO
QOpenGLVertexArrayObject PlanetEntity::ellipseVAO private
Referenced by draw(), init(), and ~PlanetEntity().
ellipseVert
QVector<QVector3D> PlanetEntity::ellipseVert private
Referenced by calcEllipse().
Inhabitants
vector<LifeForm*> Planet::Inhabitants protected inherited
Referenced by Planet::addLF().
inhabitants
QVector<LifeFormEntity*> PlanetEntity::inhabitants private
Referenced by addInhabitant(), clearInhabitants(), containsInhabitant(), getInhabitant(), getInhabitantCount(), hasNoInhabitants(), removeInhabitant(), and setPlanetRadius().
model
QMatrix4x4 PlanetEntity::model private
Referenced by draw(), and PlanetEntity().
orbitCenterPos
double PlanetEntity::orbitCenterPos[3] private
Referenced by draw(), getCurrentPosition(), getOrbitCenter(), PlanetEntity(), and setOrbitCenter().
orbitColor
QVector3D PlanetEntity::orbitColor private
Referenced by draw(), PlanetEntity(), and setOrbitColor().
orbitRadiusX
double PlanetEntity::orbitRadiusX private
Referenced by calcEllipse(), draw(), getCurrentPosition(), getOrbitRadii(), and PlanetEntity().
orbitRadiusY
double PlanetEntity::orbitRadiusY private
Referenced by calcEllipse(), draw(), getCurrentPosition(), getOrbitRadii(), and PlanetEntity().
orbitVelocity
double PlanetEntity::orbitVelocity private
Referenced by calcNextStep(), getVerlocitiyInOrbit(), PlanetEntity(), and setVelocityInOrbit().
ownRotVelocity
double PlanetEntity::ownRotVelocity private
Referenced by calcNextStep(), getOwnRotVelocity(), PlanetEntity(), and setOwnRotVelocity().
planetColor
QVector3D PlanetEntity::planetColor private
Referenced by draw(), PlanetEntity(), and setPlanetColor().
planetName
QString PlanetEntity::planetName private
Referenced by addInhabitant(), addSatellite(), getName(), PlanetEntity(), removeInhabitant(), and removeSatellite().
program
QOpenGLShaderProgram* Entity::program protected inherited
Referenced by LifeFormEntity::draw(), SolarSystemEntity::draw(), ViewOfEntities::draw(), UniverseEntity::draw(), draw(), Entity::Entity(), LifeFormEntity::init(), SolarSystemEntity::init(), ViewOfEntities::init(), UniverseEntity::init(), and init().
rotAngleXY
double PlanetEntity::rotAngleXY private
Referenced by calcRotAngles(), draw(), and getCurrentPosition().
rotAngleYZ
double PlanetEntity::rotAngleYZ private
Referenced by calcRotAngles(), draw(), and getCurrentPosition().
satellites
QVector<PlanetEntity*> PlanetEntity::satellites private
Referenced by addSatellite(), calcNextStep(), clearSatellites(), containsSatellite(), getSatellite(), getSatelliteCount(), hasNoSatellites(), removeSatellite(), and setOrbitCenter().
sphereNormalVBO
QOpenGLBuffer PlanetEntity::sphereNormalVBO private
Referenced by calcSphere(), init(), and ~PlanetEntity().
spherePositionVBO
QOpenGLBuffer PlanetEntity::spherePositionVBO private
Referenced by calcSphere(), init(), and ~PlanetEntity().
sphereRadius
double PlanetEntity::sphereRadius private
Referenced by calcSphere(), getPlanetRadius(), PlanetEntity(), and setPlanetRadius().
sphereTexCoord
QVector<QVector2D> PlanetEntity::sphereTexCoord private
Referenced by calcSphere().
sphereTexCoordVBO
QOpenGLBuffer PlanetEntity::sphereTexCoordVBO private
Referenced by calcSphere(), init(), and ~PlanetEntity().
sphereVAO
QOpenGLVertexArrayObject PlanetEntity::sphereVAO private
Referenced by draw(), init(), setPlanetRadius(), and ~PlanetEntity().
sphereVert
QVector<QVector3D> PlanetEntity::sphereVert private
Referenced by calcSphere().
texture
QOpenGLTexture* PlanetEntity::texture private
Referenced by draw(), init(), PlanetEntity(), and ~PlanetEntity().
textureChanged
bool PlanetEntity::textureChanged private
Referenced by draw(), PlanetEntity(), and setTextureFileName().
textureFileName
QString PlanetEntity::textureFileName private
Referenced by draw(), init(), and setTextureFileName().
uninitialised
QVector<Entity*> ViewOfEntities::uninitialised protected inherited
Referenced by ViewOfEntities::add(), ViewOfEntities::calcNextStep(), ViewOfEntities::clear(), ViewOfEntities::draw(), ViewOfEntities::init(), and ViewOfEntities::remove().
visible
bool Entity::visible protected inherited
Referenced by ViewOfEntities::draw(), Entity::Entity(), Entity::isVisible(), and Entity::setVisibility().
The documentation for this class was generated from the following files:
planetEntity.h
planetEntity.cpp