MindWorld: MindWorldComponent Interface Reference
MindWorldComponent Interface Reference abstract
Member of pattern Decorator as Component. Defines basic functionality for MindWorldComponents.
#include <interfaces.h>
Public Member Functions
virtual void change (char *text)=0
virtual char * get_type ()=0
virtual int get_change_count ()
void set_change_count (int new_count)
virtual void ToWrite ()=0
prints the respective member attributes of Thinkable -primitives.
Private Attributes
int _change_count
Detailed Description
Member of pattern Decorator as Component. Defines basic functionality for MindWorldComponents.
Member Function Documentation
change()
virtual void MindWorldComponent::change (char * text) pure virtual
Implemented in CreatedThoughtProxy, CreatedThought, MindWorld, Feeling, Decorator, Thought, and View.
Referenced by Decorator::change().
get_change_count()
virtual int MindWorldComponent::get_change_count () inline virtual
Implemented in Explainable.
References _change_count.
Referenced by View::change(), Thought::change(), Feeling::change(), MindWorld::change(), CreatedThought::change(), Thought::ReDo(), and Thought::UnDo().
get_type()
virtual char* MindWorldComponent::get_type () pure virtual
Implemented in Thought, View, CreatedThoughtProxy, CreatedThought, Explainable, OwnMW, MindWorld, and Feeling.
set_change_count()
void MindWorldComponent::set_change_count (int new_count) inline
References _change_count.
Referenced by View::change(), Thought::change(), Feeling::change(), MindWorld::change(), CreatedThought::change(), CreatedThought::CreatedThought(), Feeling::Feeling(), MindWorld::MindWorld(), Thought::ReDo(), Thought::Thought(), Thought::UnDo(), and View::View().
ToWrite()
virtual void Thinkable::ToWrite () pure virtual inherited
prints the respective member attributes of Thinkable -primitives.
Implemented in CreatedThoughtProxy, CreatedThought, Explainable, OwnMW, MindWorld, Feeling, Thought, and View.
Member Data Documentation
_change_count
int MindWorldComponent::_change_count private
Referenced by get_change_count(), and set_change_count().
The documentation for this interface was generated from the following file:
interfaces.h