MindWorld: SimWidgetController Class Reference
SimWidgetController Class Reference
Represents the Controller of the Model-View-Controller Triggers the calculation of the next step, the update of the view and the godly challenges. Processes all input events.
#include <simwidgetcontroller.h>
Public Member Functions
SimWidgetController (SimulationWidget *sw, SimWidgetDatamodel *dm, QObject *parent)
Constructor of class SimWidgetController.
~SimWidgetController ()
Deconstructor of class SimWidgetController.
Protected Slots
void advanceOneStep ()
Advance one step by calculating the next step and updating the view with the new data.
void onChallengeTimer ()
Trigger godly event and set the challenge timer interval to a random value.
Private Member Functions
bool eventFilter (QObject *obj, QEvent *ev)
Check if any relevant input event was triggered.
bool isPaused ()
Check if paused.
Private Attributes
SimulationWidget * mSimWidget
SimWidgetDatamodel * mDM
QTimer * simTimer
QTimer * challengeTimer
bool paused
bool stepMode
double fpsCount
Detailed Description
Represents the Controller of the Model-View-Controller Triggers the calculation of the next step, the update of the view and the godly challenges. Processes all input events.
Constructor & Destructor Documentation
SimWidgetController()
SimWidgetController::SimWidgetController (SimulationWidget * sw, SimWidgetDatamodel * dm, QObject * parent)
Constructor of class SimWidgetController.
Parameters
SimulationWidget.
SimWidgetDatamodel.
parent QT parent pointer.
Returns
none.
References advanceOneStep(), challengeTimer, fpsCount, mDM, mSimWidget, onChallengeTimer(), paused, simTimer, and stepMode.
~SimWidgetController()
SimWidgetController::~SimWidgetController ()
Deconstructor of class SimWidgetController.
References advanceOneStep(), challengeTimer, mSimWidget, onChallengeTimer(), and simTimer.
Member Function Documentation
advanceOneStep
void SimWidgetController::advanceOneStep () protected slot
Advance one step by calculating the next step and updating the view with the new data.
Parameters
none.
Returns
none.
References SimWidgetDatamodel::calcNextStep(), mDM, mSimWidget, and paused.
Referenced by eventFilter(), SimWidgetController(), and ~SimWidgetController().
eventFilter()
bool SimWidgetController::eventFilter (QObject * obj, QEvent * ev) private
Check if any relevant input event was triggered.
Parameters
current QObject.
current event.
Returns
true if event was handled.
References advanceOneStep(), challengeTimer, onChallengeTimer(), paused, simTimer, and stepMode.
isPaused()
bool SimWidgetController::isPaused () private
Check if paused.
Parameters
none.
Returns
true if paused.
References paused.
onChallengeTimer
void SimWidgetController::onChallengeTimer () protected slot
Trigger godly event and set the challenge timer interval to a random value.
Parameters
none.
Returns
none.
References SimWidgetDatamodel::challengeLifeForms(), challengeTimer, dist(), mDM, mt(), and paused.
Referenced by eventFilter(), SimWidgetController(), and ~SimWidgetController().
Member Data Documentation
challengeTimer
QTimer* SimWidgetController::challengeTimer private
Referenced by eventFilter(), onChallengeTimer(), SimWidgetController(), and ~SimWidgetController().
fpsCount
double SimWidgetController::fpsCount private
Referenced by SimWidgetController().
mDM
SimWidgetDatamodel* SimWidgetController::mDM private
Referenced by advanceOneStep(), onChallengeTimer(), and SimWidgetController().
mSimWidget
SimulationWidget* SimWidgetController::mSimWidget private
Referenced by advanceOneStep(), SimWidgetController(), and ~SimWidgetController().
paused
bool SimWidgetController::paused private
Referenced by advanceOneStep(), eventFilter(), isPaused(), onChallengeTimer(), and SimWidgetController().
simTimer
QTimer* SimWidgetController::simTimer private
Referenced by eventFilter(), SimWidgetController(), and ~SimWidgetController().
stepMode
bool SimWidgetController::stepMode private
Referenced by eventFilter(), and SimWidgetController().
The documentation for this class was generated from the following files:
simwidgetcontroller.h
simwidgetcontroller.cpp