MindWorld: View Class Reference
View Class Reference
Member of pattern Composite as Leaf. Is a view of an human.
Member of pattern Decorator as ConcreteComponent. The view can be changed, change(char* text), and it can be written out, (ToWrite()).
#include <implementations.h>
Public Member Functions
View (char *view)
Constructor of View.
void ToWrite ()
Shows the View object.
void change (char *text)
char * get_type (void)
Gets the type of the view object.
virtual int get_change_count ()
void set_change_count (int new_count)
Private Attributes
char * _view
int _change_count
Detailed Description
Member of pattern Composite as Leaf. Is a view of an human.
Member of pattern Decorator as ConcreteComponent. The view can be changed, change(char* text), and it can be written out, (ToWrite()).
Constructor & Destructor Documentation
View()
View::View (char * view)
Constructor of View.
Parameters
a string.
References _view, and MindWorldComponent::set_change_count().
Member Function Documentation
change()
void View::change (char * text) virtual
Parameters
a string.
Returns
none.
Implements MindWorldComponent.
References _view, MindWorldComponent::get_change_count(), and MindWorldComponent::set_change_count().
Referenced by OwnMW::initialize().
get_change_count()
virtual int MindWorldComponent::get_change_count () inline virtual inherited
Implemented in Explainable.
References MindWorldComponent::_change_count.
Referenced by change(), Thought::change(), Feeling::change(), MindWorld::change(), CreatedThought::change(), Thought::ReDo(), and Thought::UnDo().
get_type()
char * View::get_type (void) virtual
Gets the type of the view object.
Parameters
none.
Returns
"leave of type View".
Implements MindWorldComponent.
set_change_count()
void MindWorldComponent::set_change_count (int new_count) inline inherited
References MindWorldComponent::_change_count.
Referenced by change(), Thought::change(), Feeling::change(), MindWorld::change(), CreatedThought::change(), CreatedThought::CreatedThought(), Feeling::Feeling(), MindWorld::MindWorld(), Thought::ReDo(), Thought::Thought(), Thought::UnDo(), and View().
ToWrite()
void View::ToWrite (void) virtual
Shows the View object.
Parameters
none.
Returns
none.
Implements Thinkable.
References _view.
Member Data Documentation
_change_count
int MindWorldComponent::_change_count private inherited
Referenced by MindWorldComponent::get_change_count(), and MindWorldComponent::set_change_count().
_view
char* View::_view private
Referenced by change(), ToWrite(), and View().
The documentation for this class was generated from the following files:
implementations.h
implementations.cpp