MindWorld: God Class Reference
God Class Reference
Member of pattern Factory as Product. Member of pattern Adapter as Adaptee. This is the interface for all gods. This is the abstraction of a god and its minimum of general characteristics. Every concrete subclass has no more than this methods and variables.
#include <god.h>
Public Member Functions
God ()
Constructor of class God.
virtual ~God ()
Destructor of class God.
virtual void createBigBang ()
Creates the destiny and universe. Main output/input routine.
virtual char * getName ()
Returns the name of god.
virtual void SimulateTimeStep ()
Simluates a single timestep - it is used for doing something...
virtual unsigned long GetTimeOfUniverse ()
Returns the time of the by god created universe.
virtual LowDev_LF * createLowDevLF ()
Creates a instance of a LowDev lifeform.
virtual MidDev_LF * createMidDevLF ()
Creates a instance of a MidDev lifeform.
virtual HighDev_LF * createHighDevLF ()
Creates a instance of a HighDev lifeform.
Static Public Attributes
static char * name = "Thor"
Protected Attributes
Destiny * ourDestiny
Universe * ourUniverse
LowDev_LF LF1
MidDev_LF LF2
MidDev_LF LF3
Detailed Description
Member of pattern Factory as Product. Member of pattern Adapter as Adaptee. This is the interface for all gods. This is the abstraction of a god and its minimum of general characteristics. Every concrete subclass has no more than this methods and variables.
Constructor & Destructor Documentation
God()
God::God ()
Constructor of class God.
~God()
God::~God () virtual
Destructor of class God.
Member Function Documentation
createBigBang()
void God::createBigBang (void) virtual
Creates the destiny and universe. Main output/input routine.
Parameters
none.
Returns
none.
Reimplemented in GodAdapter.
References Universe::addNewPlanet(), HumanHerold::attachToSubject(), createHighDevLF(), createLowDevLF(), createMidDevLF(), Destiny::getDestiny(), Human::getEyeColor(), Universe::getFirstPlanet(), GetTimeOfUniverse(), Universe::getUniverse(), HumanLifeChain::Instance(), HumanHandler::Instance(), HumanLifeChainIterator::isDone(), HumanHandler::killOldest(), LF1, LF2, LF3, HumanLifeChainIterator::nextHuman(), ourDestiny, ourUniverse, SimulateTimeStep(), and LifeForm::startLife().
createHighDevLF()
HighDev_LF * God::createHighDevLF (void) virtual
Creates a instance of a HighDev lifeform.
Parameters
none.
Returns
Instance of the new created lifeform.
References getName().
Referenced by createBigBang().
createLowDevLF()
LowDev_LF * God::createLowDevLF (void) virtual
Creates a instance of a LowDev lifeform.
Parameters
none.
Returns
Instance of the new created lifeform.
References getName().
Referenced by createBigBang().
createMidDevLF()
MidDev_LF * God::createMidDevLF (void) virtual
Creates a instance of a MidDev lifeform.
Parameters
none
Returns
Instance of the new created lifeform
References getName().
Referenced by createBigBang().
getName()
char * God::getName (void) virtual
Returns the name of god.
Parameters
none.
Returns
The name of god.
Reimplemented in GodAdapter, VeryHighDev_LF, Jesus, and Alah.
References name.
Referenced by SimWidgetDatamodel::buildViewChain(), createHighDevLF(), createLowDevLF(), and createMidDevLF().
GetTimeOfUniverse()
unsigned long God::GetTimeOfUniverse (void) virtual
Returns the time of the by god created universe.
Parameters
none.
Returns
the time (DWORD).
Reimplemented in GodAdapter.
References Universe::getTime(), and ourUniverse.
Referenced by createBigBang(), and SimulateTimeStep().
SimulateTimeStep()
void God::SimulateTimeStep (void) virtual
Simluates a single timestep - it is used for doing something...
Parameters
none.
Returns
none.
Reimplemented in GodAdapter.
References Destiny::createProblemForLifeForm(), GetTimeOfUniverse(), LF1, LF2, LF3, ourDestiny, ourUniverse, and Destiny::rendevouzTwoLF().
Referenced by createBigBang().
Member Data Documentation
LF1
LowDev_LF God::LF1 protected
Referenced by createBigBang(), and SimulateTimeStep().
LF2
MidDev_LF God::LF2 protected
Referenced by createBigBang(), and SimulateTimeStep().
LF3
MidDev_LF God::LF3 protected
Referenced by createBigBang(), and SimulateTimeStep().
name
char * God::name = "Thor" static
< Predefined name of god.
Referenced by GodAdapter::createHighDevLFE(), GodAdapter::createLowDevLFE(), GodAdapter::createMidDevLFE(), and getName().
ourDestiny
Destiny* God::ourDestiny protected
Referenced by createBigBang(), and SimulateTimeStep().
ourUniverse
Universe* God::ourUniverse protected
Referenced by createBigBang(), GetTimeOfUniverse(), and SimulateTimeStep().
The documentation for this class was generated from the following files:
god.h
god.cpp