MindWorld: LFMeetJob Class Reference
LFMeetJob Class Reference
Member of pattern Command as ConcreteCommand. Defines a job that lets the working life form meet another life form.
#include <lfJobs.h>
Public Member Functions
LFMeetJob (LifeFormEntity *workLF, LifeFormEntity *lfToMeet, unsigned int prio=1)
Constructor of class LFMeet.
LFMeetJob (LFJob &copy)
Copy constructor of class LFMeetJob.
LFMeetJob (LFMeetJob &copy)
Copy constructor of class LFMeetJob.
~LFMeetJob ()
Deconstructor of class LFMeetJob.
void changeWorkingLF (LifeFormEntity *workLF)
Sets working life form.
LFMeetJob & operator= (LFMeetJob &copy)
Overload of the operator =.
bool workOnJob ()
Works on the job.
void changeParticipants (QVector< LifeFormEntity * > participants)
Sets life forms that are involved with the job.
QVector< LifeFormEntity * > getParticipants ()
Returns life forms that are involved with the job.
LifeFormEntity * getWorkingLF ()
Returns working life form.
unsigned int getPrio ()
Returns job priority.
void setPrio (unsigned int prio)
Sets the job priotity.
bool operator== (LFJob &j)
Overload of the operator ==.
bool operator!= (LFJob &j)
Overload of the operator !=.
bool operator< (LFJob &j)
Overload of the operator <.
bool operator<= (LFJob &j)
Overload of the operator <=.
bool operator> (LFJob &j)
Overload of the operator >
bool operator>= (LFJob &j)
Overload of the operator >=.
Static Public Member Functions
static unsigned long long getMeetJobCount ()
Returns number of meet jobs.
static unsigned long long getJobCount ()
Returns number of jobs.
Protected Attributes
unsigned int jobPriority
LifeFormEntity * workingLF
Static Protected Attributes
static unsigned long long jobCounter = 0
Private Attributes
LifeFormEntity * LFToMeet
LFMoveJob * jMove
Static Private Attributes
static unsigned long long meetJobCounter = 0
Detailed Description
Member of pattern Command as ConcreteCommand. Defines a job that lets the working life form meet another life form.
Constructor & Destructor Documentation
LFMeetJob() [1/3]
LFMeetJob::LFMeetJob (LifeFormEntity * workLF, LifeFormEntity * lfToMeet, unsigned int prio = 1)
Constructor of class LFMeet.
Parameters
life form that is working on the job.
life form to meet with.
priority.
Returns
none.
References LifeFormEntity::getRelativePos(), jMove, LFToMeet, meetJobCounter, and LFJob::workingLF.
LFMeetJob() [2/3]
LFMeetJob::LFMeetJob (LFJob & copy)
Copy constructor of class LFMeetJob.
Parameters
job to copy from.
Returns
none.
References jMove, LFToMeet, and meetJobCounter.
LFMeetJob() [3/3]
LFMeetJob::LFMeetJob (LFMeetJob & copy)
Copy constructor of class LFMeetJob.
Parameters
job to copy from.
Returns
none.
References meetJobCounter.
~LFMeetJob()
LFMeetJob::~LFMeetJob ()
Deconstructor of class LFMeetJob.
References jMove, and meetJobCounter.
Member Function Documentation
changeParticipants()
void LFMeetJob::changeParticipants (QVector< LifeFormEntity * > participants) virtual
Sets life forms that are involved with the job.
Parameters
vector of life forms in the constructor parameter order of the job.
Returns
none.
Implements LFJob.
References LFMoveJob::changeParticipants(), jMove, and LFToMeet.
Referenced by LFAskJob::changeParticipants(), LFAnswerJob::changeParticipants(), and LFMateJob::changeParticipants().
changeWorkingLF()
void LFMeetJob::changeWorkingLF (LifeFormEntity * workLF) virtual
Sets working life form.
Parameters
life form that will be working on the job.
Returns
none.
Reimplemented from LFJob.
References LFJob::changeWorkingLF(), LFMoveJob::changeWorkingLF(), and jMove.
Referenced by LFAskJob::changeWorkingLF(), LFAnswerJob::changeWorkingLF(), and LFMateJob::changeWorkingLF().
getJobCount()
unsigned long long LFJob::getJobCount () static inherited
Returns number of jobs.
Parameters
none.
Returns
jobCounter.
References LFJob::jobCounter.
getMeetJobCount()
unsigned long long LFMeetJob::getMeetJobCount () static
Returns number of meet jobs.
Parameters
none.
Returns
meetJobCounter.
References meetJobCounter.
getParticipants()
QVector< LifeFormEntity * > LFMeetJob::getParticipants () virtual
Returns life forms that are involved with the job.
Parameters
none.
Returns
vector of life forms in the constructor parameter order of the job.
Implements LFJob.
References LFToMeet.
Referenced by operator=().
getPrio()
unsigned int LFJob::getPrio () inherited
Returns job priority.
Parameters
none.
Returns
priority.
References LFJob::jobPriority.
Referenced by LFJob::operator=().
getWorkingLF()
LifeFormEntity * LFJob::getWorkingLF () inherited
Returns working life form.
Parameters
none.
Returns
workingLF.
References LFJob::workingLF.
Referenced by LFJobHandler::addJob(), LFJob::operator=(), and LFJobHandler::replaceLF().
operator!=()
bool LFJob::operator!= (LFJob & j) inherited
Overload of the operator !=.
Parameters
job to compare with.
Returns
result of priority comparison.
operator<()
bool LFJob::operator< (LFJob & j) inherited
Overload of the operator <.
Parameters
job to compare with.
Returns
result of priority comparison.
References LFJob::jobPriority.
operator<=()
bool LFJob::operator<= (LFJob & j) inherited
Overload of the operator <=.
Parameters
job to compare with.
Returns
result of priority comparison.
operator=()
LFMeetJob & LFMeetJob::operator= (LFMeetJob & copy)
Overload of the operator =.
Parameters
job to copy from.
Returns
reference of this.
References getParticipants(), LifeFormEntity::getRelativePos(), jMove, LFToMeet, and LFJob::workingLF.
operator==()
bool LFJob::operator== (LFJob & j) inherited
Overload of the operator ==.
Parameters
job to compare with.
Returns
result of priority comparison.
References LFJob::jobPriority.
operator>()
bool LFJob::operator> (LFJob & j) inherited
Overload of the operator >
Parameters
job to compare with.
Returns
result of priority comparison.
operator>=()
bool LFJob::operator>= (LFJob & j) inherited
Overload of the operator >=.
Parameters
job to compare with.
Returns
result of priority comparison.
setPrio()
void LFJob::setPrio (unsigned int prio) inherited
Sets the job priotity.
Parameters
priority.
Returns
none.
References LFJob::jobPriority.
workOnJob()
bool LFMeetJob::workOnJob () virtual
Works on the job.
Parameters
none.
Returns
true if done.
Implements LFJob.
References LifeFormEntity::addKnownLFE(), LFMoveJob::changeDestination(), LifeFormEntity::getRelativePos(), jMove, LFToMeet, LFJob::workingLF, and LFMoveJob::workOnJob().
Referenced by LFAskJob::workOnJob(), LFAnswerJob::workOnJob(), and LFMateJob::workOnJob().
Member Data Documentation
jMove
LFMoveJob* LFMeetJob::jMove private
Referenced by changeParticipants(), changeWorkingLF(), LFMeetJob(), operator=(), workOnJob(), and ~LFMeetJob().
jobCounter
unsigned long long LFJob::jobCounter = 0 static protected inherited
Referenced by LFJob::getJobCount(), LFJob::LFJob(), and LFJob::~LFJob().
jobPriority
unsigned int LFJob::jobPriority protected inherited
Referenced by LFJob::getPrio(), LFJob::LFJob(), LFJob::operator<(), LFJob::operator=(), LFJob::operator==(), and LFJob::setPrio().
LFToMeet
LifeFormEntity* LFMeetJob::LFToMeet private
Referenced by changeParticipants(), getParticipants(), LFMeetJob(), operator=(), and workOnJob().
meetJobCounter
unsigned long long LFMeetJob::meetJobCounter = 0 static private
Referenced by getMeetJobCount(), LFMeetJob(), and ~LFMeetJob().
workingLF
LifeFormEntity* LFJob::workingLF protected inherited
Referenced by LFJob::changeWorkingLF(), LFMateJob::createChild(), LFJob::getWorkingLF(), LFAnswerJob::LFAnswerJob(), LFAskJob::LFAskJob(), LFJob::LFJob(), LFMateJob::LFMateJob(), LFMeetJob(), LFJob::operator=(), operator=(), LFAskJob::operator=(), LFAnswerJob::operator=(), LFMateJob::operator=(), LFMoveJob::workOnJob(), workOnJob(), LFAskJob::workOnJob(), LFAnswerJob::workOnJob(), and LFMateJob::workOnJob().
The documentation for this class was generated from the following files:
lfJobs.h
lfJobs.cpp