MindWorld: LFJob Class Reference
LFJob Class Reference abstract
Member of pattern Facade as Subsystem classes. Member of pattern Command as Command. Defines an abstract job interface with minimal functionality so it can be used in a priority queue. It also has the basic functionality of working on it with returning true if the job is done and some methods to access or change the defined addresses and attributes.
#include <lfJobs.h>
Public Member Functions
LFJob (LifeFormEntity *workLF, unsigned int prio=1)
Constructor of class LFJob.
LFJob (LFJob &copy)
Copy constructor of class LFJob.
virtual ~LFJob ()
Deconstructor of class LFJob.
LifeFormEntity * getWorkingLF ()
Returns working life form.
unsigned int getPrio ()
Returns job priority.
virtual void changeWorkingLF (LifeFormEntity *workLF)
Sets working life form.
void setPrio (unsigned int prio)
Sets the job priotity.
bool operator== (LFJob &j)
Overload of the operator ==.
bool operator!= (LFJob &j)
Overload of the operator !=.
bool operator< (LFJob &j)
Overload of the operator <.
bool operator<= (LFJob &j)
Overload of the operator <=.
bool operator> (LFJob &j)
Overload of the operator >
bool operator>= (LFJob &j)
Overload of the operator >=.
LFJob & operator= (LFJob &copy)
Overload of the operator =.
virtual bool workOnJob ()=0
virtual void changeParticipants (QVector< LifeFormEntity * > participants)=0
virtual QVector< LifeFormEntity * > getParticipants ()=0
Static Public Member Functions
static unsigned long long getJobCount ()
Returns number of jobs.
Protected Attributes
unsigned int jobPriority
LifeFormEntity * workingLF
Static Protected Attributes
static unsigned long long jobCounter = 0
Detailed Description
Member of pattern Facade as Subsystem classes. Member of pattern Command as Command. Defines an abstract job interface with minimal functionality so it can be used in a priority queue. It also has the basic functionality of working on it with returning true if the job is done and some methods to access or change the defined addresses and attributes.
Constructor & Destructor Documentation
LFJob() [1/2]
LFJob::LFJob (LifeFormEntity * workLF, unsigned int prio = 1)
Constructor of class LFJob.
Parameters
life form that is working on the job.
priority.
Returns
none.
References jobCounter, jobPriority, and workingLF.
LFJob() [2/2]
LFJob::LFJob (LFJob & copy)
Copy constructor of class LFJob.
Parameters
job to copy from.
Returns
none.
References jobCounter.
~LFJob()
LFJob::~LFJob () virtual
Deconstructor of class LFJob.
References jobCounter.
Member Function Documentation
changeParticipants()
virtual void LFJob::changeParticipants (QVector< LifeFormEntity * > participants) pure virtual
Implemented in LFMateJob, LFIdleJob, LFAnswerJob, LFAskJob, LFMeetJob, and LFMoveJob.
Referenced by LFJobHandler::replaceLF().
changeWorkingLF()
void LFJob::changeWorkingLF (LifeFormEntity * workLF) virtual
Sets working life form.
Parameters
life form that will be working on the job.
Returns
none.
Reimplemented in LFMateJob, LFIdleJob, LFAnswerJob, LFAskJob, LFMeetJob, and LFMoveJob.
References workingLF.
Referenced by LFMoveJob::changeWorkingLF(), LFMeetJob::changeWorkingLF(), LFAskJob::changeWorkingLF(), LFAnswerJob::changeWorkingLF(), LFIdleJob::changeWorkingLF(), LFMateJob::changeWorkingLF(), LFJobHandler::getCopyOfJobQueue(), and LFJobHandler::replaceLF().
getJobCount()
unsigned long long LFJob::getJobCount () static
Returns number of jobs.
Parameters
none.
Returns
jobCounter.
References jobCounter.
getParticipants()
virtual QVector<LifeFormEntity*> LFJob::getParticipants () pure virtual
Implemented in LFMateJob, LFIdleJob, LFAnswerJob, LFAskJob, LFMeetJob, and LFMoveJob.
Referenced by LFJobHandler::removeJobsWithParticipant(), and LFJobHandler::replaceLF().
getPrio()
unsigned int LFJob::getPrio ()
Returns job priority.
Parameters
none.
Returns
priority.
References jobPriority.
Referenced by operator=().
getWorkingLF()
LifeFormEntity * LFJob::getWorkingLF ()
Returns working life form.
Parameters
none.
Returns
workingLF.
References workingLF.
Referenced by LFJobHandler::addJob(), operator=(), and LFJobHandler::replaceLF().
operator!=()
bool LFJob::operator!= (LFJob & j)
Overload of the operator !=.
Parameters
job to compare with.
Returns
result of priority comparison.
operator<()
bool LFJob::operator< (LFJob & j)
Overload of the operator <.
Parameters
job to compare with.
Returns
result of priority comparison.
References jobPriority.
operator<=()
bool LFJob::operator<= (LFJob & j)
Overload of the operator <=.
Parameters
job to compare with.
Returns
result of priority comparison.
operator=()
LFJob & LFJob::operator= (LFJob & copy)
Overload of the operator =.
Parameters
job to copy from.
Returns
reference of this.
References getPrio(), getWorkingLF(), jobPriority, and workingLF.
operator==()
bool LFJob::operator== (LFJob & j)
Overload of the operator ==.
Parameters
job to compare with.
Returns
result of priority comparison.
References jobPriority.
operator>()
bool LFJob::operator> (LFJob & j)
Overload of the operator >
Parameters
job to compare with.
Returns
result of priority comparison.
operator>=()
bool LFJob::operator>= (LFJob & j)
Overload of the operator >=.
Parameters
job to compare with.
Returns
result of priority comparison.
setPrio()
void LFJob::setPrio (unsigned int prio)
Sets the job priotity.
Parameters
priority.
Returns
none.
References jobPriority.
workOnJob()
virtual bool LFJob::workOnJob () pure virtual
Implemented in LFMateJob, LFIdleJob, LFAnswerJob, LFAskJob, LFMeetJob, and LFMoveJob.
Member Data Documentation
jobCounter
unsigned long long LFJob::jobCounter = 0 static protected
Referenced by getJobCount(), LFJob(), and ~LFJob().
jobPriority
unsigned int LFJob::jobPriority protected
Referenced by getPrio(), LFJob(), operator<(), operator=(), operator==(), and setPrio().
workingLF
LifeFormEntity* LFJob::workingLF protected
Referenced by changeWorkingLF(), LFMateJob::createChild(), getWorkingLF(), LFAnswerJob::LFAnswerJob(), LFAskJob::LFAskJob(), LFJob(), LFMateJob::LFMateJob(), LFMeetJob::LFMeetJob(), operator=(), LFMeetJob::operator=(), LFAskJob::operator=(), LFAnswerJob::operator=(), LFMateJob::operator=(), LFMoveJob::workOnJob(), LFMeetJob::workOnJob(), LFAskJob::workOnJob(), LFAnswerJob::workOnJob(), and LFMateJob::workOnJob().
The documentation for this class was generated from the following files:
lfJobs.h
lfJobs.cpp