MindWorld: Thought Class Reference
Thought Class Reference
Member of pattern Composite as Leaf. Is a thought of an human.
Member of pattern Decorator as ConcreteComponent.
Member of pattern Command as Receiver and also as Invoker.
#include <implementations.h>
Public Member Functions
Thought (char *thought)
Constructor of Thought.
void ToWrite ()
Shows the Thought object.
void change (char *text)
Changes the Thought.
char * get_type (void)
Returns the type of the thought.
void set_thought (char *new_value)
Sets a new thought.
void UnDo (void)
Undos an executed command.
void ReDo (void)
Redos an executed command.
virtual int get_change_count ()
void set_change_count (int new_count)
Private Attributes
char * _thought
std::vector< ChangeCommand * > _commands
std::vector< ChangeCommand * >::iterator _command_pos
int _change_count
Detailed Description
Member of pattern Composite as Leaf. Is a thought of an human.
Member of pattern Decorator as ConcreteComponent.
Member of pattern Command as Receiver and also as Invoker.
Thoughts can be changed, change(char* text), and they can get back to old values.
This is realized through the UnDo() and ReDo() functionality. Each ChangeCommand is stored into the vector _commands, and UnDo() and ReDo() operates on this vector.
Constructor & Destructor Documentation
Thought()
Thought::Thought (char * thought)
Constructor of Thought.
Parameters
a string.
References _command_pos, _commands, _thought, and MindWorldComponent::set_change_count().
Member Function Documentation
change()
void Thought::change (char * text) virtual
Changes the Thought.
Parameters
a string.
Returns
none.
Implements MindWorldComponent.
References _command_pos, _commands, _thought, MindWorldComponent::get_change_count(), and MindWorldComponent::set_change_count().
Referenced by OwnMW::initialize().
get_change_count()
virtual int MindWorldComponent::get_change_count () inline virtual inherited
Implemented in Explainable.
References MindWorldComponent::_change_count.
Referenced by View::change(), change(), Feeling::change(), MindWorld::change(), CreatedThought::change(), ReDo(), and UnDo().
get_type()
char * Thought::get_type (void) virtual
Returns the type of the thought.
Parameters
none.
Returns
"leave of type Thought".
Implements MindWorldComponent.
ReDo()
void Thought::ReDo (void)
Redos an executed command.
Parameters
none.
Returns
none.
References _command_pos, _commands, MindWorldComponent::get_change_count(), and MindWorldComponent::set_change_count().
Referenced by OwnMW::initialize().
set_change_count()
void MindWorldComponent::set_change_count (int new_count) inline inherited
References MindWorldComponent::_change_count.
Referenced by View::change(), change(), Feeling::change(), MindWorld::change(), CreatedThought::change(), CreatedThought::CreatedThought(), Feeling::Feeling(), MindWorld::MindWorld(), ReDo(), Thought(), UnDo(), and View::View().
set_thought()
void Thought::set_thought (char * new_value)
Sets a new thought.
Parameters
a string.
Returns
none.
References _thought.
Referenced by ChangeCommand::Execute(), and ChangeCommand::UnDo().
ToWrite()
void Thought::ToWrite (void) virtual
Shows the Thought object.
Parameters
none.
Returns
none.
Implements Thinkable.
References _thought.
Referenced by OwnMW::initialize().
UnDo()
void Thought::UnDo (void)
Undos an executed command.
Parameters
none.
Returns
none.
References _command_pos, _commands, MindWorldComponent::get_change_count(), and MindWorldComponent::set_change_count().
Referenced by OwnMW::initialize().
Member Data Documentation
_change_count
int MindWorldComponent::_change_count private inherited
Referenced by MindWorldComponent::get_change_count(), and MindWorldComponent::set_change_count().
_command_pos
std::vector<ChangeCommand*>::iterator Thought::_command_pos private
Referenced by change(), ReDo(), Thought(), and UnDo().
_commands
std::vector<ChangeCommand*> Thought::_commands private
0..*
Referenced by change(), ReDo(), Thought(), and UnDo().
_thought
char* Thought::_thought private
Referenced by change(), set_thought(), Thought(), and ToWrite().
The documentation for this class was generated from the following files:
implementations.h
implementations.cpp