MindWorld: destinyAdapter.cpp File Reference
destinyAdapter.cpp File Reference
Contains the implementation of class DestinyAdapter.
#include "destinyAdapter.h"
#include <QDebug>
#include <QString>
#include <QVector>
#include "planetEntity.h"
#include "lowDevLFEntity.h"
#include "midDevLFEntity.h"
#include "highDevLFEntity.h"
#include <random>
Functions
static std::mt19937_64 mt (rd())
static std::uniform_int_distribution< unsigned int > dist (0)
Variables
static std::random_device rd
Detailed Description
Contains the implementation of class DestinyAdapter.
Function Documentation
dist()
static std::uniform_int_distribution<unsigned int> dist (0) static
Referenced by DestinyAdapter::chooseRandomLFE(), DestinyAdapter::devolveLFE(), DestinyAdapter::evolveLFE(), and DestinyAdapter::generateLFEName().
mt()
static std::mt19937_64 mt (rd()) static
Referenced by DestinyAdapter::chooseRandomLFE(), DestinyAdapter::devolveLFE(), DestinyAdapter::evolveLFE(), and DestinyAdapter::generateLFEName().
Variable Documentation
rd
std::random_device rd static