MindWorld: lifeformEntity.cpp File Reference
lifeformEntity.cpp File Reference
Contains the implementation of class LifeFormEntity.
#include "lifeformEntity.h"
Functions
static std::mt19937_64 mt (rd())
static std::uniform_int_distribution< unsigned int > dist (0)
Variables
static std::random_device rd
Detailed Description
Contains the implementation of class LifeFormEntity.
Function Documentation
dist()
static std::uniform_int_distribution<unsigned int> dist (0) static
Referenced by LifeFormEntity::askKnownLFE(), LifeFormEntity::calcNextStep(), and LifeFormEntity::calcRandDestination().
mt()
static std::mt19937_64 mt (rd()) static
Referenced by LifeFormEntity::askKnownLFE(), LifeFormEntity::calcNextStep(), and LifeFormEntity::calcRandDestination().
Variable Documentation
rd
std::random_device rd static
Referenced by LifeFormEntity::calcRandDestination().